/* Formatted on 05/03/2014 10:42:25 (QP5 v5.215.12089.38647) */

-- NOK
-- KHÔNG CH?C PH?N NW_GROUP, ZONE

select * from zone_map;

DROP TABLE ZONE_MAP CASCADE CONSTRAINTS;

CREATE TABLE ZONE_MAP
(
   SERVICE_ID        NUMBER (2),
   SERVICE_NAME      VARCHAR2 (255 BYTE),
   CODE              VARCHAR2 (23 BYTE),
   NW_GROUP          VARCHAR2 (31 BYTE),
   ZONE              VARCHAR2 (63 BYTE),
   timezone          VARCHAR2 (31 BYTE),
   hierarchy_level   NUMBER (2)
)
TABLESPACE pcat_filter
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX ZONE_MAP_CODE
   ON ZONE_MAP (CODE)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


CREATE INDEX ZONE_MAP_NW_GROUP
   ON ZONE_MAP (NW_GROUP)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


CREATE INDEX ZONE_MAP_SERVICE_ID
   ON ZONE_MAP (SERVICE_ID)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


ALTER TABLE ZONE_MAP ADD (
  CONSTRAINT ZONE_MAP_R01
  FOREIGN KEY (SERVICE_ID)
  REFERENCES SERVICE (SERVICE_ID)
  ENABLE VALIDATE);