/* Formatted on 11/03/2014 21:59:24 (QP5 v5.215.12089.38647) */
--ALTER TABLE PRODUCT_OFFER DROP PRIMARY KEY CASCADE;
--
--DROP TABLE PRODUCT_OFFER CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT_OFFER
(
   PRODUCT_OFFER_ID             NUMBER (7) NOT NULL,
   PRODUCT_OFFER_NAME           VARCHAR2 (63 BYTE) NOT NULL,
   PRODUCT_OFFER_ABBREVIATION   VARCHAR2 (15 BYTE),
   UNBILL                       CHAR (1 BYTE) DEFAULT '0' NOT NULL,
   B_NUMBER_ENRICH              VARCHAR2 (87 BYTE),
   PRODUCT_GROUP_TYPE           VARCHAR2 (23 BYTE),
   PARENT_ID                    NUMBER (7)
)
TABLESPACE pcat_filter
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX PRODUCT_OFFER_B_NUMBER_ENRICH
   ON PRODUCT_OFFER (B_NUMBER_ENRICH)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


CREATE INDEX PRODUCT_OFFER_GROUP_TYPE
   ON PRODUCT_OFFER (PRODUCT_GROUP_TYPE)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


CREATE UNIQUE INDEX PRODUCT_OFFER_PK
   ON PRODUCT_OFFER (PRODUCT_OFFER_ID)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


ALTER TABLE PRODUCT_OFFER ADD (
  CONSTRAINT PRODUCT_OFFER_PK
  PRIMARY KEY
  (PRODUCT_OFFER_ID)
  USING INDEX PRODUCT_OFFER_PK
  ENABLE VALIDATE);