DROP VIEW VNP_COMMON.ALIAS_SELECT;

/* Formatted on 7/5/2014 07:58:06 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW VNP_COMMON.ALIAS_SELECT
(
   ACCOUNT_VERSION_ID,
   ALIAS,
   ACCOUNT_ID,
   SUBSCRIBER_NO,
   FROM_DATE_TEST,
   FROM_DATE,
   TO_DATE_TEST,
   TO_DATE,
   MODIFIED_DATE_TEST,
   MODIFIED_DATE
)
AS
   SELECT ACCOUNT_VERSION_ID,
          SUBSCRIBER_NO AS ALIAS,
          ACCOUNT_ID,
          SUBSCRIBER_NO SUBSCRIBER_NO,
          ACCOUNT_VERSION.FROM_DATE AS FROM_DATE_TEST,
            (ACCOUNT_VERSION.FROM_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
          * 24
          * 60
          * 60
             AS FROM_DATE,
          ACCOUNT_VERSION.FROM_DATE AS TO_DATE_TEST,
            (ACCOUNT_VERSION.TO_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
          * 24
          * 60
          * 60
             AS TO_DATE,
          ACCOUNT_VERSION.MODIFIED_DATE AS MODIFIED_DATE_TEST,
            (  ACCOUNT_VERSION.MODIFIED_DATE
             - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
          * 24
          * 60
          * 60
             AS MODIFIED_DATE
     FROM SUBSCRIBER
          INNER JOIN ACCOUNT_VERSION
             ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID);
