/* Formatted on 3/29/2014 11:59:22 AM (QP5 v5.227.12220.39754) */
SELECT t1.ATTRIBUTE_ID AS attributeId,
       t2.SERVICE_VERSION_ID AS serviceVersionId,
       t2.DATA_TYPE AS dataType,
       t6.DISPLAY_VALUE AS segmentationKeyIdKey,
       t2.SEGMENTATION_KEY_ID AS segmentationKeyId,
       t2.ATTRIBUTE_TYPE AS attributeType,
       t2.ATTRIBUTE_SOURCE AS attributeSource,
       t3.LANGUAGE_CODE AS languageCode,
       t3.DISPLAY_VALUE AS displayValue,
       t3.DESCRIPTION AS description
  FROM cbs_owner.SEGMENTATION_KEY_ATTR_KEY t1
       INNER JOIN cbs_owner.SEGMENTATION_KEY_ATTR_REF t2
          ON t1.ATTRIBUTE_ID = t2.ATTRIBUTE_ID
       INNER JOIN
       cbs_owner.SEGMENTATION_KEY_ATTR_VALUES t3
          ON     t2.ATTRIBUTE_ID = t3.ATTRIBUTE_ID
             AND t2.SERVICE_VERSION_ID = t3.SERVICE_VERSION_ID
       INNER JOIN cbs_owner.SEGMENTATION_KEY_ID_KEY t4
          ON t2.SEGMENTATION_KEY_ID = t4.SEGMENTATION_KEY_ID
       INNER JOIN
       cbs_owner.SEGMENTATION_KEY_ID_REF t5
          ON     t4.SEGMENTATION_KEY_ID = t5.SEGMENTATION_KEY_ID
             AND t5.SERVICE_VERSION_ID = t2.SERVICE_VERSION_ID
       INNER JOIN
       cbs_owner.SEGMENTATION_KEY_ID_VALUES t6
          ON     t4.SEGMENTATION_KEY_ID = t6.SEGMENTATION_KEY_ID
             AND t6.SERVICE_VERSION_ID = t2.SERVICE_VERSION_ID
             AND t6.LANGUAGE_CODE = t3.LANGUAGE_CODE
 WHERE t2.SERVICE_VERSION_ID = 1 AND t3.LANGUAGE_CODE = 1;