/* Formatted on 9/22/2014 3:41:22 PM (QP5 v5.215.12089.38647) */
CREATE TABLESPACE cbs_owner
  DATAFILE '+DATA/eonerate/datafile/cbs_owner01.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 2 G;

CREATE USER cbs_owner
          IDENTIFIED BY cbs_owner
          DEFAULT TABLESPACE cbs_owner
          TEMPORARY TABLESPACE TEMP
          PROFILE DEFAULT
          ACCOUNT UNLOCK;

GRANT CREATE SESSION TO cbs_owner;

-- 8 Roles for cbs_owner
GRANT EXP_FULL_DATABASE TO cbs_owner WITH ADMIN OPTION;
GRANT IMP_FULL_DATABASE TO cbs_owner WITH ADMIN OPTION;
GRANT AUTHENTICATEDUSER TO cbs_owner WITH ADMIN OPTION;
GRANT DATAPUMP_EXP_FULL_DATABASE TO cbs_owner WITH ADMIN OPTION;
GRANT DATAPUMP_IMP_FULL_DATABASE TO cbs_owner WITH ADMIN OPTION;
-- GRANT ORA_ASPNET_MEM_BASICACCESS TO cbs_owner WITH ADMIN OPTION;
GRANT CONNECT TO cbs_owner WITH ADMIN OPTION;
GRANT DBA TO cbs_owner WITH ADMIN OPTION;
ALTER USER cbs_owner DEFAULT ROLE ALL;
-- 2 System Privileges for cbs_owner
GRANT IMPORT FULL DATABASE TO cbs_owner WITH ADMIN OPTION;

GRANT UNLIMITED TABLESPACE TO cbs_owner WITH ADMIN OPTION;