DROP SEQUENCE VNP_COMMON.ACCOUNT_SEQ;

CREATE SEQUENCE VNP_COMMON.ACCOUNT_SEQ
  START WITH 22
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

DROP TABLE VNP_COMMON.ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT
(
  ACCOUNT_ID   NUMBER(15)                       NOT NULL,
  CURRENCY_ID  NUMBER(3)                        NOT NULL
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--CREATE OR REPLACE TRIGGER VNP_COMMON.ACCOUNT_TRG
--BEFORE INSERT
--ON VNP_COMMON.ACCOUNT
--REFERENCING NEW AS New OLD AS Old
--FOR EACH ROW
--BEGIN
---- For Toad:  Highlight column ACCOUNT_ID
--  :new.ACCOUNT_ID := ACCOUNT_SEQ.nextval;
--END ACCOUNT_TRG;
--/
