/* Formatted on 17/12/2014 4:44:59 PM (QP5 v5.215.12089.38647) */
--TRUNCATE TABLE vnp_common.account_version;
--TRUNCATE TABLE vnp_common.account;
--TRUNCATE TABLE vnp_common.subscriber;
--TRUNCATE TABLE vnp_common.subs_offer_map;
--
--DELETE vnp_data.hot_rated_cdr WHERE 1 = 1;

SELECT COUNT (1) FROM VNP_COMMON.ACCOUNT_VERSION;

SELECT COUNT (1) FROM VNP_COMMON.SUBSCRIBER;

SELECT COUNT (1) FROM VNP_COMMON.ACCOUNT;

SELECT COUNT (1) FROM VNP_COMMON.SUBS_OFFER_MAP;

SELECT COUNT (1) FROM vnp_data.hot_rated_cdr;

SELECT * FROM vnp_common.subscriber;

SELECT * FROM VNP_COMMON.SUBS_OFFER_MAP;

-- 5 THUE BAO CHI SU DONG 1 PO VA 1 SO: ALO

INSERT INTO VNP_COMMON.ACCOUNT_VERSION
   SELECT AV.*
     FROM    VNP_COMMON.ACCOUNT_VERSION@PROD_VNP_VIEW AV
          INNER JOIN
             (  SELECT SUBSCRIBER_ID
                  FROM VNP_COMMON.SUBS_OFFER_MAP@PROD_VNP_VIEW SOM,
                       VNP_COMMON.PRODUCT_OFFER@PROD_VNP_VIEW PO
                 WHERE     SOM.PRODUCT_OFFER_ID = PO.OFFER_ID
                       AND (   (    UPPER (OFFER_NAME) LIKE '%ALO%'
                                AND PO.OFFER_TYPE = 'SO')
                            OR (PO.OFFER_TYPE = 'PO'))
              GROUP BY SUBSCRIBER_ID
                HAVING COUNT (1) = 2) T
          ON (AV.SUBSCRIBER_ID = T.SUBSCRIBER_ID)
    WHERE     SYSDATE - 100 > AV.FROM_DATE
          AND (AV.TO_DATE IS NULL OR SYSDATE + 100 < AV.TO_DATE)
          AND ROWNUM <= 5;

INSERT INTO VNP_COMMON.SUBSCRIBER
   SELECT S.*
     FROM    VNP_COMMON.SUBSCRIBER@PROD_VNP_VIEW S
          INNER JOIN
             VNP_COMMON.ACCOUNT_VERSION AV
          ON (S.SUBSCRIBER_ID = AV.SUBSCRIBER_ID);

INSERT INTO VNP_COMMON.ACCOUNT
   SELECT A.*
     FROM    VNP_COMMON.ACCOUNT@PROD_VNP_VIEW A
          INNER JOIN
             VNP_COMMON.ACCOUNT_VERSION AV
          ON (A.ACCOUNT_ID = AV.ACCOUNT_ID);

INSERT INTO VNP_COMMON.SUBS_OFFER_MAP
   SELECT SOM.*
     FROM    VNP_COMMON.SUBS_OFFER_MAP@PROD_VNP_VIEW SOM
          INNER JOIN
             VNP_COMMON.SUBSCRIBER S
          ON (SOM.SUBSCRIBER_ID = S.SUBSCRIBER_ID);

INSERT INTO VNP_DATA.HOT_RATED_CDR
   SELECT HRC.*
     FROM    VNP_COMMON.SUBSCRIBER S
          INNER JOIN
             VNP_DATA.HOT_RATED_CDR@PROD_VNP_VIEW HRC
          ON (S.SUBSCRIBER_NO = HRC.A_NUMBER);

COMMIT;