/* Formatted on 3/29/2014 11:54:33 AM (QP5 v5.227.12220.39754) */
SELECT t1.EXPRESSION_TEMPLATE_ID AS expressionTemplateId,
       t4.DISPLAY_VALUE AS expressionTemplateIdKey,
       t1.EXPRESSION_GROUP_ID AS expressionGroupId,
       t1.RESELLER_VERSION_ID AS resellerVersionId
  FROM cbs_owner.EXPRESSION_TEMPLATE t1
       INNER JOIN cbs_owner.EXPRESSION_TEMPLATE_ID_KEY t2
          ON t1.EXPRESSION_TEMPLATE_ID = t2.EXPRESSION_TEMPLATE_ID
       INNER JOIN
       cbs_owner.EXPRESSION_TEMPLATE_ID_REF t3
          ON     t2.EXPRESSION_TEMPLATE_ID = t3.EXPRESSION_TEMPLATE_ID
             AND t3.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
       INNER JOIN
       cbs_owner.EXPRESSION_TEMPLATE_ID_VALUES t4
          ON     t2.EXPRESSION_TEMPLATE_ID = t4.EXPRESSION_TEMPLATE_ID
             AND t4.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
             AND t4.LANGUAGE_CODE = 1
       INNER JOIN cbs_owner.EXPRESSION_GROUP_KEY t5
          ON t1.EXPRESSION_GROUP_ID = t5.EXPRESSION_GROUP_ID
 WHERE t1.RESELLER_VERSION_ID = 2;