/* Formatted on 29/11/2014 10:08:46 PM (QP5 v5.215.12089.38647) */
TRUNCATE TABLE ACTION_LOG;
TRUNCATE TABLE AGGREGATED_CDR;
TRUNCATE TABLE AGGREGATED_RC;
TRUNCATE TABLE FIRST_TEMP_RATED_CDR;
TRUNCATE TABLE RATED_CSV_FILE;
TRUNCATE TABLE RATED_RC;
TRUNCATE TABLE RC_LOG;
TRUNCATE TABLE SECOND_TEMP_RATED_CDR;
TRUNCATE TABLE TEMP_RC_RATING;
TRUNCATE TABLE THIRD_TEMP_RATED_CDR;
TRUNCATE TABLE ERROR_CODE;

TRUNCATE TABLE BALANCE_COUNTER;

TRUNCATE TABLE COMPENSATION_CDR;

TRUNCATE TABLE RATED_CDR;
TRUNCATE TABLE RATING_RC;
TRUNCATE TABLE RATED_CDR_DEV_OLD;

TRUNCATE TABLE RATED_CDR_DEV;
TRUNCATE TABLE HOT_RATED_CDR;

TRUNCATE TABLE HOT_AGGREGATED_CDR;
TRUNCATE TABLE CDR_LOG_PROCESS;
TRUNCATE TABLE TEMP_RATED_CDR;

TRUNCATE TABLE CDR_RECORD_HEADER;