/* Formatted on 29/04/2014 13:59:31 (QP5 v5.227.12220.39754) */
-- *** CBS_OWNER

GRANT EXECUTE ON ELC_USER.CBS_OWNER_FILTER TO cbs_owner;


-- *** ELC_USER

GRANT CREATE JOB TO elc_user;

-- GRANT MANAGE SCHEDULER TO elc_user;

GRANT CREATE DATABASE LINK TO elc_user;

--GRANT EXECUTE ON VNP_COMMON.ELC_USER_FILTER@EONERATE_VNP_COMMON TO ELC_USER;



-- *** VNP_COMMON

GRANT CREATE JOB TO vnp_common;

GRANT EXECUTE ON VNP_DATA.RR_UPDATE_COUNTER TO vnp_common;

BEGIN
   FOR R IN (SELECT OWNER, TABLE_NAME
               FROM ALL_TABLES
              WHERE OWNER = 'VNP_DATA')
   LOOP
      EXECUTE IMMEDIATE
            'GRANT SELECT, INSERT, DELETE, UPDATE ON '
         || R.OWNER
         || '.'
         || R.TABLE_NAME
         || ' TO VNP_COMMON';
   END LOOP;
END;