/* Formatted on 29/04/2014 13:55:26 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE TRIGGER PREFIX_ENRICH_TRG
   BEFORE INSERT
   ON VNP_COMMON.PREFIX_ENRICH
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBSCRIBER_VERSION_ID
   :new.PREFIX_ENRICH_ID := SUBSCRIBER_VERSION_SEQ.NEXTVAL;
END PREFIX_ENRICH_TRG;
/