/* Formatted on 6/6/2014 08:07:13 (QP5 v5.227.12220.39754) */
DROP TABLE VNP_DATA.COMPENSATION_CDR;

CREATE GLOBAL TEMPORARY TABLE VNP_DATA.COMPENSATION_CDR
(
   MAP_ID                      NUMBER (9),
   A_NUMBER                    VARCHAR2 (15 BYTE),
   AUT_FINAL_ID                NUMBER (6),
   SERVICE_FEE                 NUMBER (15, 3),
   CHARGE_FEE                  NUMBER (15, 3),
   OFFER_COST                  NUMBER (15, 3),
   OFFER_FREE_BLOCK            NUMBER (21),
   INTERNAL_COST               NUMBER (15, 3),
   INTERNAL_FREE_BLOCK         NUMBER (11),
   RATED_SERVICE_FEE           NUMBER (15, 3),
   RATED_CHARGE_FEE            NUMBER (15, 3),
   RATED_OFFER_COST            NUMBER (15, 3),
   RATED_OFFER_FREE_BLOCK      NUMBER (21),
   RATED_INTERNAL_COST         NUMBER (15, 3),
   RATED_INTERNAL_FREE_BLOCK   NUMBER (11)
)
ON COMMIT DELETE ROWS;