DROP SEQUENCE PCAT_FILTER.SUBS_OFFER_MAP_SEQ;

CREATE SEQUENCE PCAT_FILTER.SUBS_OFFER_MAP_SEQ
  START WITH 21
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;







ALTER TABLE PCAT_FILTER.SUBS_OFFER_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCAT_FILTER.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLE PCAT_FILTER.SUBS_OFFER_MAP
(
  SUBSCRIBER_ID      NUMBER(15)                 NOT NULL,
  FROM_DATE          DATE                       NOT NULL,
  TO_DATE            DATE,
  PRODUCT_OFFER_ID   NUMBER(10)                 NOT NULL,
  SUBS_OFFER_MAP_ID  NUMBER(23),
  MODIFIED_DATE      DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PCAT_FILTER.SUBS_OFFER_MAP_PK ON PCAT_FILTER.SUBS_OFFER_MAP
(SUBS_OFFER_MAP_ID)
LOGGING
TABLESPACE PCAT_FILTER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER PCAT_FILTER.SUBS_OFFER_MAP_TRG
BEFORE INSERT
ON PCAT_FILTER.SUBS_OFFER_MAP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SUBS_OFFER_MAP_ID
  :new.SUBS_OFFER_MAP_ID := SUBS_OFFER_MAP_SEQ.nextval;
END SUBS_OFFER_MAP_TRG;
/


ALTER TABLE PCAT_FILTER.SUBS_OFFER_MAP ADD (
  CONSTRAINT SUBS_OFFER_MAP_PK
  PRIMARY KEY
  (SUBS_OFFER_MAP_ID)
  USING INDEX PCAT_FILTER.SUBS_OFFER_MAP_PK
  ENABLE VALIDATE);
