/* Formatted on 26/03/2014 15:02:44 (QP5 v5.215.12089.38647) */
SELECT t44.RT_DISCOUNT_ID AS rtDiscountId,
       t45.RESELLER_VERSION_ID AS resellerVersionId,
       t6.DISPLAY_VALUE AS accumulatorKeyByAccumulatorId,
       t45.ACCUMULATOR_ID AS accumulatorId,
       t8.DISPLAY_VALUE AS discountType,
       t10.SERVICE_VERSION_ID AS serviceVersionId,
       t10.ISO_CODE AS currencyIsoCode,
       t10.IMPLIED_DECIMAL AS currencyImpliedDecimal,
       t11.DISPLAY_VALUE AS rateCurrencyKey,
       t45.CURRENCY_CODE AS currencyCode,
       t14.DISPLAY_VALUE AS accumulatorKeyByAddonAccId1,
       t45.ADDON_ACC_ID1 AS addonAccId1,
       t17.DISPLAY_VALUE AS accumulatorKeyByAddonAccId2,
       t45.ADDON_ACC_ID2 AS addonAccId2,
       t20.DISPLAY_VALUE AS accumulatorKeyByAddonAccId3,
       t45.ADDON_ACC_ID3 AS addonAccId3,
       t23.DISPLAY_VALUE AS accumulatorKeyByAddonAccId4,
       t45.ADDON_ACC_ID4 AS addonAccId4,
       t45.RESET_FLAG AS resetFlag,
       t45.IS_DEFAULT AS isDefault,
       t45.IS_INTERNAL AS isInternal,
       t46.LANGUAGE_CODE AS languageCode,
       t46.DISPLAY_VALUE AS displayValue,
       t46.DESCRIPTION AS description
  FROM cbs_owner.RT_DISCOUNT_KEY t44
       INNER JOIN cbs_owner.RT_DISCOUNT_REF t45
          ON t44.RT_DISCOUNT_ID = t45.RT_DISCOUNT_ID
       INNER JOIN cbs_owner.RT_DISCOUNT_VALUES t46
          ON     t45.RT_DISCOUNT_ID = t46.RT_DISCOUNT_ID
             AND t45.RESELLER_VERSION_ID = t46.RESELLER_VERSION_ID
       INNER JOIN cbs_owner.ACCUMULATOR_KEY t4
          ON t45.ACCUMULATOR_ID = t4.ACCUMULATOR_ID
       INNER JOIN cbs_owner.ACCUMULATOR_REF t5
          ON     t4.ACCUMULATOR_ID = t5.ACCUMULATOR_ID
             AND t5.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
       INNER JOIN cbs_owner.ACCUMULATOR_VALUES t6
          ON     t4.ACCUMULATOR_ID = t6.ACCUMULATOR_ID
             AND t6.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
             AND t6.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.GENERIC_ENUMERATION_REF t7
          ON     t7.enumeration_key = LOWER ('DISCOUNT_TYPE')
             AND t7.VALUE = t45.DISCOUNT_TYPE
       LEFT OUTER JOIN cbs_owner.GENERIC_ENUMERATION_VALUES t8
          ON     t8.enumeration_key = t7.enumeration_key
             AND t8.VALUE = t7.VALUE
             AND t8.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.RATE_CURRENCY_KEY t9
          ON t45.CURRENCY_CODE = t9.CURRENCY_CODE
       LEFT OUTER JOIN cbs_owner.RATE_CURRENCY_REF t10
          ON     t9.CURRENCY_CODE = t10.CURRENCY_CODE
             AND t10.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN cbs_owner.RATE_CURRENCY_VALUES t11
          ON     t9.CURRENCY_CODE = t11.CURRENCY_CODE
             AND t11.SERVICE_VERSION_ID = 1
             AND t11.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_KEY t12
          ON t45.ADDON_ACC_ID1 = t12.ACCUMULATOR_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_REF t13
          ON     t12.ACCUMULATOR_ID = t13.ACCUMULATOR_ID
             AND t13.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_VALUES t14
          ON     t12.ACCUMULATOR_ID = t14.ACCUMULATOR_ID
             AND t14.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
             AND t14.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_KEY t15
          ON t45.ADDON_ACC_ID2 = t15.ACCUMULATOR_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_REF t16
          ON     t15.ACCUMULATOR_ID = t16.ACCUMULATOR_ID
             AND t16.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_VALUES t17
          ON     t15.ACCUMULATOR_ID = t17.ACCUMULATOR_ID
             AND t17.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
             AND t17.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_KEY t18
          ON t45.ADDON_ACC_ID3 = t18.ACCUMULATOR_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_REF t19
          ON     t18.ACCUMULATOR_ID = t19.ACCUMULATOR_ID
             AND t19.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_VALUES t20
          ON     t18.ACCUMULATOR_ID = t20.ACCUMULATOR_ID
             AND t20.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
             AND t20.LANGUAGE_CODE = t46.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_KEY t21
          ON t45.ADDON_ACC_ID4 = t21.ACCUMULATOR_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_REF t22
          ON     t21.ACCUMULATOR_ID = t22.ACCUMULATOR_ID
             AND t22.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.ACCUMULATOR_VALUES t23
          ON     t21.ACCUMULATOR_ID = t23.ACCUMULATOR_ID
             AND t23.RESELLER_VERSION_ID = t45.RESELLER_VERSION_ID
             AND t23.LANGUAGE_CODE = t46.LANGUAGE_CODE
 WHERE t45.RESELLER_VERSION_ID = 2 AND t46.LANGUAGE_CODE = 1;