DROP TABLE VNP_COMMON.ACCUMULATOR CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCUMULATOR
(
  ACCUMULATOR_ID       NUMBER(10)               NOT NULL,
  ACCUMULATOR_NAME     VARCHAR2(720 BYTE)       NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  UNIT_TYPE_NAME       VARCHAR2(720 BYTE)       NOT NULL,
  UNIT_TYPE_ID         NUMBER(6)                NOT NULL,
  PERIOD_ID            VARCHAR2(213 BYTE),
  PERIOD_NAME          VARCHAR2(720 BYTE),
  RESET_POINT          NUMBER                   NOT NULL,
  TYPE_ID              VARCHAR2(195 BYTE),
  TYPE_NAME            VARCHAR2(720 BYTE),
  COUNT_TYPE_ID        VARCHAR2(195 BYTE),
  COUNT_TYPE_NAME      VARCHAR2(720 BYTE),
  DESCRIPTION          VARCHAR2(2160 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
