DROP TABLE VNP_COMMON.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CUSTOMER
(
  CUSTOMER_ID         NUMBER(15)                NOT NULL,
  CUSTOMER_PARENT_ID  NUMBER(15)
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
