DROP TABLE VNP_COMMON.DISCOUNT_MODEL CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.DISCOUNT_MODEL
(
  DISCOUNT_ITEM_ID     NUMBER                   NOT NULL,
  DISCOUNT_ITEM_NAME   VARCHAR2(720 BYTE)       NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  DISCOUNT_NAME        VARCHAR2(720 BYTE)       NOT NULL,
  DISCOUNT_ID          NUMBER(10)               NOT NULL,
  UA_NAME              VARCHAR2(720 BYTE),
  UA_ID                NUMBER(10),
  UA_GROUP_NAME        VARCHAR2(720 BYTE),
  UA_GROUP_ID          NUMBER(6),
  ITEM_DESC            VARCHAR2(2160 BYTE),
  ACCUMULATOR_NAME     VARCHAR2(720 BYTE)       NOT NULL,
  ACCUMULATOR_ID       NUMBER(10)               NOT NULL,
  DISCOUNT_TYPE_ID     VARCHAR2(195 BYTE),
  DISCOUNT_TYPE_NAME   VARCHAR2(720 BYTE),
  CURRENCY_NAME        VARCHAR2(720 BYTE),
  CURRENCY_CODE        NUMBER(6),
  DISCOUNT_DESC        VARCHAR2(2160 BYTE),
  AWARD_ID             NUMBER(10)               NOT NULL,
  AWARD_NAME           VARCHAR2(720 BYTE),
  THRESHOLD            NUMBER(22,8)             NOT NULL,
  AMOUNT               NUMBER(22,8)             NOT NULL,
  AWARD_DESC           VARCHAR2(2160 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
