DROP TABLE VNP_COMMON.OFFER_RC_AWARD_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.OFFER_RC_AWARD_MAP
(
  OFFER_RC_AWARD_MAP_ID     NUMBER(10)          NOT NULL,
  RESELLER_VERSION_ID       NUMBER(18)          NOT NULL,
  OFFER_NAME                VARCHAR2(720 BYTE)  NOT NULL,
  OFFER_ID                  NUMBER(10)          NOT NULL,
  RC_TERM_NAME              VARCHAR2(720 BYTE)  NOT NULL,
  RC_TERM_ID                NUMBER(10)          NOT NULL,
  TERM_DATE_ACTIVE          DATE                NOT NULL,
  TERM_DATE_INACTIVE        DATE,
  TERM_LEVEL_NAME           VARCHAR2(720 BYTE),
  TERM_LEVEL_ID             VARCHAR2(213 BYTE),
  BALANCE_NAME              VARCHAR2(720 BYTE)  NOT NULL,
  BALANCE_ID                NUMBER(10)          NOT NULL,
  PERIOD_FREQUENCE_ID       VARCHAR2(213 BYTE),
  PERIOD_FREQUENCE_NAME     VARCHAR2(720 BYTE),
  APPLY_DAY                 NUMBER(6),
  PRO_AWARD_INSF_RC_BAL     NUMBER(1)           NOT NULL,
  AMOUNT                    NUMBER(18),
  CURRENCY_NAME             VARCHAR2(720 BYTE),
  CURRENCY_CODE             NUMBER(6),
  UNIT_TYPE_NAME            VARCHAR2(720 BYTE)  NOT NULL,
  UNIT_TYPE_ID              NUMBER(6)           NOT NULL,
  GRANT_ORDER               VARCHAR2(720 BYTE),
  ACTION                    VARCHAR2(720 BYTE),
  AWARD_ACTIVATION_TYPE     VARCHAR2(720 BYTE),
  AWARD_ACTIVATION_OFFSET   NUMBER(6),
  AWARD_EXPIRY_TYPE         VARCHAR2(720 BYTE),
  AWARD_EXPIRY_OFFSET_TYPE  VARCHAR2(720 BYTE),
  AWARD_EXPIRY_OFFSET       NUMBER(6),
  AWARD_EXPIRY_DATE         DATE,
  IS_ROLLABLE               NUMBER(1)           NOT NULL,
  ROLLOVER_GROUPING         VARCHAR2(720 BYTE),
  MAXIMUM_GRANT_ROLLOVER    NUMBER(18),
  MAXIMUM_TOTAL_ROLLOVER    NUMBER(18),
  RC_MULTIPLICATIONS        NUMBER(6),
  CYCLES_ROLLOVER_EXPIRE    NUMBER(6),
  DEFAULT_SET_FUNCTION      NUMBER(1)           NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
