DROP TABLE VNP_COMMON.PREFIX_ENRICH CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PREFIX_ENRICH
(
  PREFIX            VARCHAR2(11 BYTE),
  CHANGE            VARCHAR2(11 BYTE),
  CONDITION         VARCHAR2(15 BYTE),
  PREFIX_ENRICH_ID  NUMBER(7)
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER VNP_COMMON.PREFIX_ENRICH_TRG
   BEFORE INSERT
   ON VNP_COMMON.PREFIX_ENRICH
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBSCRIBER_VERSION_ID
   :new.PREFIX_ENRICH_ID := SUBSCRIBER_VERSION_SEQ.NEXTVAL;
END PREFIX_ENRICH_TRG;
/
