ALTER TABLE VNP_COMMON.SERVICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE VNP_COMMON.SERVICE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SERVICE
(
  SERVICE_ID    NUMBER(3),
  SERVICE_NAME  VARCHAR2(255 BYTE),
  SERVICE_TYPE  VARCHAR2(63 BYTE),
  GROUP_ID      NUMBER(3),
  VAS           CHAR(1 CHAR)                    DEFAULT '0'                   NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VNP_COMMON.SERVICE.VAS IS 'Y - dich vu co ban, N - dich vu vas';



CREATE UNIQUE INDEX VNP_COMMON.SERVICE_PK ON VNP_COMMON.SERVICE
(SERVICE_ID)
LOGGING
TABLESPACE VNP_COMMON
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_COMMON.SERVICE_VAS ON VNP_COMMON.SERVICE
(VAS)
LOGGING
TABLESPACE VNP_COMMON
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE VNP_COMMON.SERVICE ADD (
  CONSTRAINT SERVICE_PK
  PRIMARY KEY
  (SERVICE_ID)
  USING INDEX VNP_COMMON.SERVICE_PK
  ENABLE VALIDATE);
