ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE VNP_COMMON.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_OFFER_MAP
(
  SUBSCRIBER_ID      NUMBER(15)                 NOT NULL,
  FROM_DATE          DATE                       NOT NULL,
  TO_DATE            DATE,
  PRODUCT_OFFER_ID   NUMBER(10)                 NOT NULL,
  SUBS_OFFER_MAP_ID  NUMBER(23),
  MODIFIED_DATE      DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_COMMON.SUBS_OFFER_MAP_PK ON VNP_COMMON.SUBS_OFFER_MAP
(SUBS_OFFER_MAP_ID)
LOGGING
TABLESPACE PCAT_FILTER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER VNP_COMMON.SUBS_OFFER_MAP_TRG
   BEFORE INSERT
   ON VNP_COMMON.SUBS_OFFER_MAP
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBS_OFFER_MAP_ID
   :new.SUBS_OFFER_MAP_ID := SUBS_OFFER_MAP_SEQ.NEXTVAL;
END SUBS_OFFER_MAP_TRG;
/


ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP ADD (
  CONSTRAINT SUBS_OFFER_MAP_PK
  PRIMARY KEY
  (SUBS_OFFER_MAP_ID)
  USING INDEX VNP_COMMON.SUBS_OFFER_MAP_PK
  ENABLE VALIDATE);
