-- DROP TABLE ELC_USER.ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.ACTION_LOG
(
  LOG_TITLE     VARCHAR2(255 BYTE),
  LOG_GROUP     VARCHAR2(127 BYTE),
  LOG_CONTENT   VARCHAR2(1023 BYTE),
  LOG_LEVEL     NUMBER(1),
  CREATED_TIME  DATE                            DEFAULT SYSDATE
);

COMMENT ON COLUMN ELC_USER.ACTION_LOG.LOG_LEVEL IS '1 = DEBUG Level
2 = INFO Level
3 = WARN Level
4 = ERROR Level
5 = FATAL Level';

GRANT SELECT ON ELC_USER.ACTION_LOG TO PCAT_FILTER;
