DROP TABLE ELC_USER.CHANGE_FLAG CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.CHANGE_FLAG
(
  IS_CHANGING  NUMBER(1)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
