DROP TABLE ELC_USER.CURRENCY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.CURRENCY_TYPE
(
  CURRENCY_CODE    NUMBER(6)                    NOT NULL,
  CURRENCY_NAME    VARCHAR2(240 BYTE)           NOT NULL,
  TYPE_NAME        VARCHAR2(240 BYTE)           NOT NULL,
  TYPE_ID          CHAR(1 BYTE)                 NOT NULL,
  ACTIVE_DATE      DATE                         NOT NULL,
  INACTIVE_DATE    DATE,
  ROUNDING_FACTOR  NUMBER(6)                    NOT NULL,
  ISO_CODE         VARCHAR2(4 BYTE),
  ISO_NUMBER       NUMBER(3),
  DESCRIPTION      VARCHAR2(720 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
