DROP TABLE ELC_USER.EXPRESSION_PLAN_OVERRIDE CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.EXPRESSION_PLAN_OVERRIDE
(
  EXPRESSIONPLANOVERRIDEID  NUMBER(10)          NOT NULL,
  RESELLERVERSIONID         NUMBER(18)          NOT NULL,
  EXPRESSIONTEMPLATEIDKEY   VARCHAR2(240 BYTE)  NOT NULL,
  DESCRIPTION               VARCHAR2(720 BYTE),
  EXPRESSIONTEMPLATEID      NUMBER(10)          NOT NULL,
  FINALPLANID               NUMBER              NOT NULL,
  INITIALPLANID             NUMBER              NOT NULL,
  PLANTYPE                  NUMBER              NOT NULL,
  INITIALPLANKEY            VARCHAR2(240 BYTE)  NOT NULL,
  OVERRIDETEMPLATEKEY       VARCHAR2(240 BYTE)  NOT NULL,
  OVERRIDETEMPLATEID        NUMBER(10)          NOT NULL,
  PRIORITY                  NUMBER(3)           NOT NULL
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
