DROP TABLE ELC_USER.OFFER_PRIORITY CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.OFFER_PRIORITY
(
  OFFER_ID                NUMBER(10)            NOT NULL,
  OFFER_NAME              VARCHAR2(240 BYTE)    NOT NULL,
  UPSELL_TEMPLATE_NAME    VARCHAR2(240 BYTE)    NOT NULL,
  UPSELL_TEMPLATE_ID      NUMBER(10),
  RESELLER_VERSION_ID     NUMBER(18)            NOT NULL,
  UPSELL_TMP_DESC         VARCHAR2(720 BYTE),
  UPSELL_TEMPLATE_MAP_ID  NUMBER(10)            NOT NULL,
  BUNDLE_NAME             VARCHAR2(240 BYTE),
  BUNDLE_ID               NUMBER(10),
  UPSELL_TMP_OFFER_NAME   VARCHAR2(240 BYTE),
  UPSELL_TMP_OFFER_ID     NUMBER(10),
  TARIFF_PRIORITY         NUMBER(6),
  RC_PRIORITY             NUMBER(6),
  DISCOUNT_PRIORITY       NUMBER(6),
  BALANCE_PRIORITY        NUMBER(6),
  DISPLAY_PRIORITY        NUMBER(6)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
