DROP TABLE ELC_USER.OFFER_BALANCE_MAP CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.OFFER_BALANCE_MAP
(
  BALANCE_NAME               VARCHAR2(240 BYTE) NOT NULL,
  BALANCE_ID                 NUMBER(10)         NOT NULL,
  OFFER_NAME                 VARCHAR2(240 BYTE) NOT NULL,
  OFFER_ID                   NUMBER(10)         NOT NULL,
  RESELLER_VERSION_ID        NUMBER(18)         NOT NULL,
  BALANCE_ORDER              NUMBER(6)          NOT NULL,
  IS_SHADOW                  NUMBER,
  IS_CORE                    NUMBER(1)          NOT NULL,
  EXPIRATION_DATE            DATE,
  MIN_BALANCE                NUMBER(22,8),
  MAX_BALANCE                NUMBER(22,8),
  EXPIRATION_OPTION          VARCHAR2(240 BYTE),
  DEFAULT_EXPIRATION_OFFSET  NUMBER(18)         NOT NULL,
  IS_SHARED                  NUMBER(1)          NOT NULL,
  DEFAULT_LIMIT_TYPE         VARCHAR2(240 BYTE),
  DEFAULT_LIMIT_VALUE        NUMBER(22,8),
  DEFAULT_LIMIT_PERIOD       VARCHAR2(240 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
