DROP TABLE ELC_USER.OFFER_ACCUMULATOR_MAP CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.OFFER_ACCUMULATOR_MAP
(
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  OFFER_NAME           VARCHAR2(240 BYTE)       NOT NULL,
  OFFER_ID             NUMBER(10)               NOT NULL,
  ACCUMULATOR_NAME     VARCHAR2(240 BYTE)       NOT NULL,
  ACCUMULATOR_ID       NUMBER(10)               NOT NULL
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
