DROP TABLE ELC_USER.PRODUCT_OFFER CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.PRODUCT_OFFER
(
  OFFER_ID               NUMBER(10)             NOT NULL,
  OFFER_NAME             VARCHAR2(240 BYTE)     NOT NULL,
  OFFER_TYPE             VARCHAR2(31 BYTE),
  RESELLER_VERSION_ID    NUMBER(18)             NOT NULL,
  SALES_EFFECTIVE_TIME   DATE                   NOT NULL,
  SALES_EXPIRATION_TIME  DATE,
  CURRENCY_NAME          VARCHAR2(240 BYTE),
  CURRENCY_CODE          NUMBER(6),
  UPSELL_TEMPLATE_ID     NUMBER(10)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
