DROP TABLE ELC_USER.TARIFF_PLAN CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.TARIFF_PLAN
(
  TARIFF_PLAN_MAPPING_ID  NUMBER(10)            NOT NULL,
  RESELLER_VERSION_ID     NUMBER(18)            NOT NULL,
  TARIFF_PLAN_NAME        VARCHAR2(240 BYTE)    NOT NULL,
  TARIFF_PLAN_ID          NUMBER(10)            NOT NULL,
  DEFAULT_CURRENCY_NAME   VARCHAR2(240 BYTE)    NOT NULL,
  DEFAULT_CURRENCY_CODE   NUMBER(6)             NOT NULL,
  CALENDAR_NAME           VARCHAR2(240 BYTE)    NOT NULL,
  CALENDAR_ID             NUMBER(10),
  UNIT_TYPE_NAME          VARCHAR2(240 BYTE)    NOT NULL,
  UNIT_TYPE_ID            NUMBER(6),
  TARIFF_SET_NAME         VARCHAR2(240 BYTE)    NOT NULL,
  TARIFF_SET_ID           NUMBER                NOT NULL,
  CHARGE_RATE_CODE        NUMBER(6)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
