DROP TABLE ELC_USER.TIME_MAP CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.TIME_MAP
(
  CALENDAR_ID          NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  CALENDAR_TYPE        VARCHAR2(240 BYTE),
  CALENDAR_NAME        VARCHAR2(240 BYTE)       NOT NULL,
  DESCRIPTION          VARCHAR2(720 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
