DROP TABLE ELC_USER.USAGE_PLAN CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.USAGE_PLAN
(
  USAGE_PLAN_NAME      VARCHAR2(240 BYTE)       NOT NULL,
  USAGE_PLAN_ID        NUMBER(10)               NOT NULL,
  OFFER_NAME           VARCHAR2(240 BYTE)       NOT NULL,
  OFFER_ID             NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  USAGE_ITEM_NAME      VARCHAR2(240 BYTE)       NOT NULL,
  USAGE_ITEM_ID        NUMBER(10)               NOT NULL,
  ASSUME_CONSUMPTION   NUMBER(3)                NOT NULL,
  INHIBIT_REFUND       CHAR(1 BYTE)             NOT NULL,
  UA_NAME              VARCHAR2(240 BYTE)       NOT NULL,
  UA_ID                NUMBER(10)               NOT NULL,
  TARIFF_PLAN_NAME     VARCHAR2(240 BYTE)       NOT NULL,
  TARIFF_PLAN_ID       NUMBER(10)               NOT NULL,
  DESCRIPTION          VARCHAR2(720 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
