/* Formatted on 04/03/2014 15:03:59 (QP5 v5.215.12089.38647) */
SELECT t1.TIME_TYPE_ID AS timeTypeId,
       t2.RESELLER_VERSION_ID AS resellerVersionId,
       t2.IS_INTERNAL AS isInternal,
       t2.IS_DEFAULT AS isDefault,
       t2.RATE_PERIOD AS ratePeriod,
       t3.LANGUAGE_CODE AS languageCode,
       t3.DISPLAY_VALUE AS displayValue,
       t3.DESCRIPTION AS description
  FROM TIME_TYPE_KEY t1
       INNER JOIN TIME_TYPE_REF t2
          ON t1.TIME_TYPE_ID = t2.TIME_TYPE_ID
       INNER JOIN TIME_TYPE_VALUES t3
          ON     t2.TIME_TYPE_ID = t3.TIME_TYPE_ID
             AND t2.RESELLER_VERSION_ID = t3.RESELLER_VERSION_ID
 WHERE t2.RESELLER_VERSION_ID = 2 AND t3.LANGUAGE_CODE = 1;


SELECT t1.RESELLER_VERSION_ID AS resellerVersionId,
       t1.SEQNUM AS seqnum,
       t1.OFFER_ID AS offerId,
       t1.RC_TERM_ID AS rcTermId,
       t1.USAGE_PLAN_ID AS usagePlanId,
       t1.CHG_WHO AS chgWho,
       t1.CHG_DT AS chgDt,
       t1.CREATE_DT AS createDt,
       t1.PRIORITY AS priority,
       t1.DISCOUNT_FACTOR AS discountFactor,
       t4.DISPLAY_VALUE AS timeTypeKey,
       t1.TIME_TYPE_ID AS timeTypeId,
       t1.ENDHHMM AS endhhmm,
       t1.STARTHHMM AS starthhmm,
       t1.DAYOFWEEK AS dayofweek,
       t1.DAYOFMONTH AS dayofmonth,
       t1.MONTH AS month,
       t1.YEAR AS year,
       t6.DISPLAY_VALUE AS classOfServiceCodeRef,
       t1.CLASS_OF_SERVICE_CODE AS classOfServiceCode,
       t8.DISPLAY_VALUE AS equipClassCodeRef,
       t1.EQUIP_CLASS_CODE AS equipClassCode,
       t10.DISPLAY_VALUE AS equipTypeCodeRef,
       t1.EQUIP_TYPE_CODE AS equipTypeCode,
       t1.RATE_CLASS AS rateClass,
       t13.DISPLAY_VALUE AS autFinalKey,
       t1.AUT_ID AS autId,
       t15.SERVICE_VERSION_ID AS serviceVersionId,
       t16.DISPLAY_VALUE AS providerClassKey,
       t1.PROVIDER_CLASS AS providerClass,
       t19.DISPLAY_VALUE AS billClassKey,
       t1.BILL_CLASS AS billClass,
       t22.DISPLAY_VALUE AS jurisdictionsKey,
       t1.JURISDICTION AS jurisdiction,
       t25.DISPLAY_VALUE AS pointClassKey,
       t1.POINT_CLASS_ORIGIN AS pointClassOrigin,
       t28.DISPLAY_VALUE AS pointClassKeyByPointClassTarge,
       t1.POINT_CLASS_TARGET AS pointClassTarget
  FROM TIME_TYPES t1
       INNER JOIN TIME_TYPE_KEY t2
          ON t1.TIME_TYPE_ID = t2.TIME_TYPE_ID
       INNER JOIN TIME_TYPE_REF t3
          ON     t2.TIME_TYPE_ID = t3.TIME_TYPE_ID
             AND t3.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
       INNER JOIN TIME_TYPE_VALUES t4
          ON     t2.TIME_TYPE_ID = t4.TIME_TYPE_ID
             AND t4.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
             AND t4.LANGUAGE_CODE = 1
       LEFT OUTER JOIN CLASS_OF_SERVICE_CODE_REF t5
          ON t1.CLASS_OF_SERVICE_CODE = t5.CLASS_OF_SERVICE_CODE
       LEFT OUTER JOIN CLASS_OF_SERVICE_CODE_VALUES t6
          ON     t5.CLASS_OF_SERVICE_CODE = t6.CLASS_OF_SERVICE_CODE
             AND t6.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN EQUIP_CLASS_CODE_REF t7
          ON t1.EQUIP_CLASS_CODE = t7.EQUIP_CLASS_CODE
       LEFT OUTER JOIN EQUIP_CLASS_CODE_VALUES t8
          ON     t7.EQUIP_CLASS_CODE = t8.EQUIP_CLASS_CODE
             AND t8.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN EQUIP_TYPE_CODE_REF t9
          ON t1.EQUIP_TYPE_CODE = t9.EQUIP_TYPE_CODE
       LEFT OUTER JOIN EQUIP_TYPE_CODE_VALUES t10
          ON     t9.EQUIP_TYPE_CODE = t10.EQUIP_TYPE_CODE
             AND t10.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN AUT_FINAL_KEY t11
          ON t1.AUT_ID = t11.AUT_ID
       LEFT OUTER JOIN AUT_FINAL_REF t12
          ON     t11.AUT_ID = t12.AUT_ID
             AND t12.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
       LEFT OUTER JOIN AUT_FINAL_VALUES t13
          ON     t11.AUT_ID = t13.AUT_ID
             AND t13.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
             AND t13.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN PROVIDER_CLASS_KEY t14
          ON t1.PROVIDER_CLASS = t14.PROVIDER_CLASS
       LEFT OUTER JOIN PROVIDER_CLASS_REF t15
          ON     t14.PROVIDER_CLASS = t15.PROVIDER_CLASS
             AND t15.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN PROVIDER_CLASS_VALUES t16
          ON     t14.PROVIDER_CLASS = t16.PROVIDER_CLASS
             AND t16.SERVICE_VERSION_ID = 1
             AND t16.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN BILL_CLASS_KEY t17
          ON t1.BILL_CLASS = t17.BILL_CLASS
       LEFT OUTER JOIN BILL_CLASS_REF t18
          ON t17.BILL_CLASS = t18.BILL_CLASS AND t18.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN BILL_CLASS_VALUES t19
          ON     t17.BILL_CLASS = t19.BILL_CLASS
             AND t19.SERVICE_VERSION_ID = 1
             AND t19.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN JURISDICTIONS_KEY t20
          ON t1.JURISDICTION = t20.JURISDICTION
       LEFT OUTER JOIN JURISDICTIONS_REF t21
          ON     t20.JURISDICTION = t21.JURISDICTION
             AND t21.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN JURISDICTIONS_VALUES t22
          ON     t20.JURISDICTION = t22.JURISDICTION
             AND t22.SERVICE_VERSION_ID = 1
             AND t22.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN POINT_CLASS_KEY t23
          ON t1.POINT_CLASS_ORIGIN = t23.POINT_CLASS
       LEFT OUTER JOIN POINT_CLASS_REF t24
          ON t23.POINT_CLASS = t24.POINT_CLASS AND t24.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN POINT_CLASS_VALUES t25
          ON     t23.POINT_CLASS = t25.POINT_CLASS
             AND t25.SERVICE_VERSION_ID = 1
             AND t25.LANGUAGE_CODE = t4.LANGUAGE_CODE
       LEFT OUTER JOIN POINT_CLASS_KEY t26
          ON t1.POINT_CLASS_TARGET = t26.POINT_CLASS
       LEFT OUTER JOIN POINT_CLASS_REF t27
          ON t26.POINT_CLASS = t27.POINT_CLASS AND t27.SERVICE_VERSION_ID = 1
       LEFT OUTER JOIN POINT_CLASS_VALUES t28
          ON     t26.POINT_CLASS = t28.POINT_CLASS
             AND t28.SERVICE_VERSION_ID = 1
             AND t28.LANGUAGE_CODE = t4.LANGUAGE_CODE
 WHERE t1.RESELLER_VERSION_ID = 2;