/* Formatted on 4/7/2014 1:28:40 PM (QP5 v5.227.12220.39754) */
CREATE TABLE ACCOUNT
AS
   SELECT * FROM VNP_COMMON.ACCOUNT;

CREATE TABLE ACCOUNT_VERSION
AS
   SELECT * FROM VNP_COMMON.ACCOUNT_VERSION;

CREATE TABLE BUSINESS_UNIT
AS
   SELECT * FROM VNP_COMMON.BUSINESS_UNIT;

CREATE TABLE CUSTOMER
AS
   SELECT * FROM VNP_COMMON.CUSTOMER;

CREATE TABLE ERA
AS
   SELECT * FROM VNP_COMMON.ERA;

CREATE TABLE PAYMENT_ITEM
AS
   SELECT * FROM VNP_COMMON.PAYMENT_ITEM;

CREATE TABLE PREFIX_ENRICH
AS
   SELECT * FROM VNP_COMMON.PREFIX_ENRICH;

CREATE TABLE RATED_RC
AS
   SELECT * FROM VNP_COMMON.RATED_RC;


SELECT * FROM VNP_COMMON.RATING_TYPE;

CREATE TABLE RATING_TYPE
AS
   SELECT * FROM VNP_COMMON.RATING_TYPE;

CREATE TABLE RC_TARIFF
AS
   SELECT * FROM VNP_COMMON.RC_TARIFF;

CREATE TABLE RC_TARIFF_TYPE
AS
   SELECT * FROM VNP_COMMON.RC_TARIFF_TYPE;

CREATE TABLE SUBSCRIBER
AS
   SELECT * FROM VNP_COMMON.SUBSCRIBER;

CREATE TABLE SUBSCRIBER_STATUS
AS
   SELECT * FROM VNP_COMMON.SUBSCRIBER_STATUS;

CREATE TABLE SUBSCRIBER_VERSION
AS
   SELECT * FROM VNP_COMMON.SUBSCRIBER_VERSION;

CREATE TABLE SUBS_BU_MAP
AS
   SELECT * FROM VNP_COMMON.SUBS_BU_MAP;

CREATE TABLE SUBS_OFFER_MAP
AS
   SELECT * FROM VNP_COMMON.SUBS_OFFER_MAP;


CREATE TABLE SUBS_STATUS_MAP
AS
   SELECT * FROM VNP_COMMON.SUBS_STATUS_MAP;