/* Formatted on 23/04/2014 18:13:07 (QP5 v5.227.12220.39754) */
SELECT ACCOUNT_VERSION_ID,
       ALIAS,
       ACCOUNT_ID,
       SUBSCRIBER_NO,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM PCAT_FILTER.ALIAS_SELECT;

SELECT ACCOUNT_VERSION_ID,
       SUBSCRIBER_NO AS ALIAS,
       ACCOUNT_ID,
       SUBSCRIBER_NO SUBSCRIBER_NO,
       ACCOUNT_VERSION.FROM_DATE,
       ACCOUNT_VERSION.TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE
  FROM SUBSCRIBER
       INNER JOIN ACCOUNT_VERSION
          ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID);


SELECT ACCOUNT_VERSION_ID,
       ACCOUNT_ID,
       MSN,
       EFFECTIVE_DATE,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM PCAT_FILTER.AUDIT_SEGMENT_SELECT;

SELECT ACCOUNT_VERSION_ID,
       ACCOUNT_ID,
       NULL MSN,
       ACCOUNT_VERSION.EFFECTIVE_DATE,
       ACCOUNT_VERSION.FROM_DATE,
       ACCOUNT_VERSION.TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE
  FROM ACCOUNT_VERSION;


SELECT ACCOUNT_VERSION_ID,
       ID,
       PRODUCT_OFFER_ID,
       SUBSCRIBER_NO,
       RESELLER_VERSION_ID,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM PCAT_FILTER.PRODUCT_SELECT;


  SELECT ACCOUNT_VERSION_ID,
         SUBS_OFFER_MAP_ID AS ID,               -- PROD_VIEW_ID_NEXTVAL AS ID,
         PRODUCT_OFFER_ID,
         SUBSCRIBER_NO,
         RESELLER_VERSION_ID,                                   -- SERVICE_ID,
         SUBS_OFFER_MAP.FROM_DATE,
         SUBS_OFFER_MAP.TO_DATE,
         SUBS_OFFER_MAP.MODIFIED_DATE,
         PRODUCT_OFFER.OFFER_TYPE
    FROM SUBSCRIBER
         INNER JOIN SUBS_OFFER_MAP
            ON (SUBSCRIBER.SUBSCRIBER_ID = SUBS_OFFER_MAP.SUBSCRIBER_ID)
         INNER JOIN ACCOUNT_VERSION
            ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID)
         INNER JOIN PRODUCT_OFFER
            ON (PRODUCT_OFFER.OFFER_ID = SUBS_OFFER_MAP.PRODUCT_OFFER_ID)
ORDER BY DECODE (PRODUCT_OFFER.OFFER_TYPE,  'PO', 1,  'SO', 2,  3)