#!/usr/bin/expect -f

set orfile [lindex $argv 0]
spawn bash
expect "#" { send "rm -f /staging/billing/data/usage/ready/999.$orfile.*\r" }
expect "#" { send "exit\r" }
expect eof

spawn sqlplus cbs_owner@orp
expect "password:" { send "comverse\r" }
expect "SQL>" { send "update file_status set file_status=10 where file_name='999.$orfile';\r" }
expect "SQL>" { send "update usage_file_status set file_status=6 where file_name='999.$orfile';\r" }
expect "SQL>" { send "commit;\r" }
expect "SQL>" { send "exit\r" }
expect eof
exit 0
