/* Formatted on 13/12/2014 6:20:46 PM (QP5 v5.215.12089.38647) */
DROP DATABASE LINK PCAT_ELC_USER;

CREATE DATABASE LINK PCAT_ELC_USER
 CONNECT TO ELC_USER
 IDENTIFIED BY elc_user
 USING 'ELC_202_8_PCAT';

DROP DATABASE LINK BAK_VNP_COMMON;

CREATE DATABASE LINK BAK_VNP_COMMON
 CONNECT TO vnp_common
 IDENTIFIED BY vnp_common
 USING 'EONERATE_BACKUP';

DROP DATABASE LINK BAK_VNP_DATA;

CREATE DATABASE LINK BAK_VNP_DATA
 CONNECT TO vnp_data
 IDENTIFIED BY vnp_data
 USING 'EONERATE_BACKUP';


DROP DATABASE LINK PROD_VNP_VIEW;

CREATE DATABASE LINK PROD_VNP_VIEW
 CONNECT TO vnp_view
 IDENTIFIED BY vnp_view
 USING 'EONERATE_PRODUCT';


DROP DATABASE LINK PROD_VNP_COMMON;

CREATE DATABASE LINK PROD_VNP_COMMON
 CONNECT TO vnp_common
 IDENTIFIED BY vnp_common
 USING 'EONERATE_PRODUCT';

DROP DATABASE LINK PROD_VNP_DATA;

CREATE DATABASE LINK PROD_VNP_DATA
 CONNECT TO vnp_data
 IDENTIFIED BY vnp_data
 USING 'EONERATE_PRODUCT';

--ELC_202_8_PCAT=
--  (DESCRIPTION=
--    (ADDRESS=
--      (PROTOCOL=TCP)
--      (HOST=192.9.202.8)
--      (PORT=1521)
--    )
--    (CONNECT_DATA=
--      (SERVER=dedicated)
--      (SERVICE_NAME=PCAT)
--    )
--  )

--EONERATE_BACKUP =
--  (DESCRIPTION =
--    (ADDRESS = (PROTOCOL = TCP)(HOST = backupdb)(PORT = 1521))
--    (CONNECT_DATA =
--      (SERVER = DEDICATED)
--      (SERVICE_NAME = eonerate)
--    )
--  )

--EONERATE_PRODUCT =
--  (DESCRIPTION=
--    (LOAD_BALANCE=on)
--    (ADDRESS_LIST=
--      (ADDRESS=
--        (PROTOCOL=TCP)
--        (HOST=10.149.3.111)
--        (PORT=1521)
--      )
--      (ADDRESS=
--        (PROTOCOL=TCP)
--        (HOST=10.149.3.112)
--        (PORT=1521)
--      )
--    )
--    (CONNECT_DATA=
--      (SERVICE_NAME=eonerate)
--    )
--  )