DROP TABLE VNP_COMMON.ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT
(
  ACCOUNT_ID   NUMBER(15)                       NOT NULL,
  CURRENCY_ID  NUMBER(3)                        NOT NULL
)
TABLESPACE VNP_COMMON_ACCOUNT;


CREATE INDEX VNP_COMMON.IDX_ACCOUNT_ID ON VNP_COMMON.ACCOUNT
(ACCOUNT_ID)
LOGGING
TABLESPACE VNP_COMMON_ACCOUNT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


-- CREATE OR REPLACE TRIGGER VNP_COMMON.ACCOUNT_TRG
-- BEFORE INSERT
-- ON VNP_COMMON.ACCOUNT
-- REFERENCING NEW AS NEW OLD AS OLD
-- FOR EACH ROW
-- DISABLE
-- BEGIN
-- -- For Toad:  Highlight column ACCOUNT_ID
  -- :new.ACCOUNT_ID := ACCOUNT_SEQ.nextval;
-- END ACCOUNT_TRG;
-- /
