DROP TABLE VNP_COMMON.ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACTION_LOG
(
  LOG_TITLE     VARCHAR2(255 BYTE),
  LOG_GROUP     VARCHAR2(127 BYTE),
  LOG_CONTENT   VARCHAR2(1023 BYTE),
  LOG_LEVEL     NUMBER(1),
  CREATED_TIME  DATE                            DEFAULT SYSDATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VNP_COMMON.ACTION_LOG.LOG_LEVEL IS '1 = DEBUG Level
2 = INFO Level
3 = WARN Level
4 = ERROR Level
5 = FATAL Level';
