DROP TABLE VNP_COMMON.ELCRATE_FLAG_DEV CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ELCRATE_FLAG_DEV
(
  CMD_CODE      NUMBER(2),
  RESULT        VARCHAR2(1023 BYTE),
  FLAG          NUMBER(1)                       NOT NULL,
  CREATED_TIME  DATE                            DEFAULT SYSDATE,
  HOST_IP       VARCHAR2(15 BYTE),
  HOST_PORT     NUMBER(7)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
