DROP TABLE VNP_COMMON.OFFER_RC_TERM_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.OFFER_RC_TERM_MAP
(
  OFFER_NAME           VARCHAR2(720 BYTE)       NOT NULL,
  OFFER_ID             NUMBER(10)               NOT NULL,
  RC_TERM_NAME         VARCHAR2(720 BYTE)       NOT NULL,
  RC_TERM_ID           NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  DATE_ACTIVE          DATE                     NOT NULL,
  DATE_INACTIVE        DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
