DROP TABLE VNP_COMMON.PAYMENT_ITEM CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PAYMENT_ITEM
(
  PAYMENT_ITEM_ID    NUMBER(3)                  NOT NULL,
  PAYMENT_ITEM_NAME  VARCHAR2(63 BYTE)          NOT NULL,
  USD                NUMBER(1),
  BONUS_TYPE         NUMBER(3)
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
