DROP TABLE VNP_COMMON.PRICE_MODEL CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PRICE_MODEL
(
  PRICE_MODEL  VARCHAR2(24 BYTE)                DEFAULT NULL,
  STEP         VARCHAR2(24 BYTE)                DEFAULT NULL,
  TIER_FROM    VARCHAR2(24 BYTE)                DEFAULT NULL,
  TIER_TO      VARCHAR2(24 BYTE)                DEFAULT NULL,
  BEAT         VARCHAR2(24 BYTE)                DEFAULT NULL,
  FACTOR       VARCHAR2(24 BYTE)                DEFAULT NULL,
  CHARGE_BASE  VARCHAR2(10 BYTE)                DEFAULT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
