DROP TABLE VNP_COMMON.RESELLER_VERSION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.RESELLER_VERSION
(
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  RESELLER_ID          NUMBER(10)               NOT NULL,
  MAJOR_VERSION_NUM    NUMBER(10)               NOT NULL,
  MINOR_VERSION_NUM    NUMBER(10)               NOT NULL,
  ACTIVE_DATE          DATE                     NOT NULL,
  INACTIVE_DATE        DATE,
  SERVICE_VERSION_ID   NUMBER(18)               NOT NULL,
  STATUS               NUMBER(3)                NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
