DROP TABLE VNP_COMMON.SUBSCRIBER CASCADE CONSTRAINTS;

CREATE TABLESPACE subs_p0
  DATAFILE '+DATA/eonerate/datafile/subs_p0.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p1
  DATAFILE '+DATA/eonerate/datafile/subs_p1.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p2
  DATAFILE '+DATA/eonerate/datafile/subs_p2.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p3
  DATAFILE '+DATA/eonerate/datafile/subs_p3.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p4
  DATAFILE '+DATA/eonerate/datafile/subs_p4.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p5
  DATAFILE '+DATA/eonerate/datafile/subs_p5.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p6
  DATAFILE '+DATA/eonerate/datafile/subs_p6.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p7
  DATAFILE '+DATA/eonerate/datafile/subs_p7.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p8
  DATAFILE '+DATA/eonerate/datafile/subs_p8.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLESPACE subs_p9
  DATAFILE '+DATA/eonerate/datafile/subs_p9.dbf'
    SIZE 200M
    REUSE
    AUTOEXTEND ON NEXT 100 M MAXSIZE 5 G;

CREATE TABLE VNP_COMMON.SUBSCRIBER
(
  SUBSCRIBER_ID   NUMBER(15)                    NOT NULL,
  SUBSCRIBER_NO   VARCHAR2(31 BYTE)             NOT NULL,
  RATING_TYPE_ID  NUMBER(3)                     NOT NULL,
  DATA_PART       NUMBER(2)                     NOT NULL
)
PARTITION BY RANGE (DATA_PART)
   (PARTITION P0 VALUES LESS THAN (1)
       TABLESPACE subs_p0,
    PARTITION P1 VALUES LESS THAN (2)
       TABLESPACE subs_p1,
    PARTITION P2 VALUES LESS THAN (3)
       TABLESPACE subs_p2,
    PARTITION P3 VALUES LESS THAN (4)
       TABLESPACE subs_p3,
    PARTITION P4 VALUES LESS THAN (5)
       TABLESPACE subs_p4,
    PARTITION P5 VALUES LESS THAN (6)
       TABLESPACE subs_p5,
    PARTITION P6 VALUES LESS THAN (7)
       TABLESPACE subs_p6,
    PARTITION P7 VALUES LESS THAN (8)
       TABLESPACE subs_p7,
    PARTITION P8 VALUES LESS THAN (9)
       TABLESPACE subs_p8,
    PARTITION P9 VALUES LESS THAN (10)
       TABLESPACE subs_p9);


-- CREATE OR REPLACE TRIGGER VNP_COMMON.SUBSCRIBER_TRG
-- BEFORE INSERT
-- ON VNP_COMMON.SUBSCRIBER
-- REFERENCING NEW AS NEW OLD AS OLD
-- FOR EACH ROW
-- DISABLE
-- BEGIN
   -- -- For Toad:  Highlight column SUBSCRIBER_ID
   -- :new.SUBSCRIBER_ID := SUBSCRIBER_SEQ.NEXTVAL;
-- END SUBSCRIBER_TRG;
-- /
