DROP TABLE VNP_COMMON.SUBS_BU_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_BU_MAP
(
  BU_ID          VARCHAR2(7 BYTE)               NOT NULL,
  SUBSCRIBER_ID  NUMBER(15)                     NOT NULL,
  FROM_DATE      DATE                           NOT NULL,
  TO_DATE        DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
