/* Formatted on 22/4/2014 10:26:03 (QP5 v5.227.12220.39754) */
DROP SEQUENCE VNP_COMMON.ACCOUNT_VERSION_SEQ;

CREATE SEQUENCE VNP_COMMON.ACCOUNT_VERSION_SEQ
   START WITH 113
   MAXVALUE 99999999999999999999999
   MINVALUE 1
   NOCYCLE
   CACHE 20
   NOORDER;


DROP SEQUENCE VNP_COMMON.SUBSCRIBER_SEQ;

CREATE SEQUENCE VNP_COMMON.SUBSCRIBER_SEQ
   START WITH 950286
   MAXVALUE 999999999999999
   MINVALUE 1
   NOCYCLE
   CACHE 20
   NOORDER;


DROP SEQUENCE VNP_COMMON.SUBSCRIBER_VERSION_SEQ;

CREATE SEQUENCE VNP_COMMON.SUBSCRIBER_VERSION_SEQ
   START WITH 876562
   MAXVALUE 99999999999999999999999
   MINVALUE 1
   NOCYCLE
   CACHE 20
   NOORDER;


DROP SEQUENCE VNP_COMMON.SUBS_OFFER_MAP_SEQ;

CREATE SEQUENCE VNP_COMMON.SUBS_OFFER_MAP_SEQ
   START WITH 23
   MAXVALUE 99999999999
   MINVALUE 1
   NOCYCLE
   CACHE 20
   NOORDER;



DROP TABLE VNP_COMMON.ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT
(
   ACCOUNT_ID    NUMBER (15) NOT NULL,
   CURRENCY_ID   NUMBER (3) NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.ACCOUNT_VERSION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_VERSION
(
   ACCOUNT_VERSION_ID   NUMBER (23) NOT NULL,
   FROM_DATE            DATE NOT NULL,
   TO_DATE              DATE,
   SUBSCRIBER_ID        NUMBER (15),
   ACCOUNT_ID           NUMBER (15),
   MODIFIED_DATE        DATE,
   EFFECTIVE_DATE       DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.BUSINESS_UNIT CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.BUSINESS_UNIT
(
   BU_ID     VARCHAR2 (7 BYTE) NOT NULL,
   BU_NAME   VARCHAR2 (127 BYTE) NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CUSTOMER
(
   CUSTOMER_ID          NUMBER (15) NOT NULL,
   CUSTOMER_PARENT_ID   NUMBER (15)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.ERA CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ERA
(
   ID                   NUMBER (11) NOT NULL,
   ACCOUNT_VERSION_ID   NUMBER (23),
   ERA_KEY              VARCHAR2 (255 BYTE),
   ERA_VALUE            VARCHAR2 (255 BYTE),
   ACCOUNT_ID           NUMBER (15),
   MODIFIED_DATE        DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.PAYMENT_ITEM CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PAYMENT_ITEM
(
   PAYMENT_ITEM_ID     NUMBER (3) NOT NULL,
   PAYMENT_ITEM_NAME   VARCHAR2 (63 BYTE) NOT NULL,
   USD                 NUMBER (1),
   BONUS_TYPE          NUMBER (3)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.PREFIX_ENRICH CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PREFIX_ENRICH
(
   PREFIX             VARCHAR2 (11 BYTE),
   CHANGE             VARCHAR2 (11 BYTE),
   CONDITION          VARCHAR2 (15 BYTE),
   PREFIX_ENRICH_ID   NUMBER (7)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.RATING_TYPE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.RATING_TYPE
(
   RATING_TYPE_ID   NUMBER (3) NOT NULL,
   TYPE_NAME        VARCHAR2 (63 BYTE) NOT NULL,
   UNBILL           CHAR (1 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.RC_TARIFF CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.RC_TARIFF
(
   NUMBER_OF_DAYS             NUMBER (2) NOT NULL,
   PRODUCT_OFFER_VERSION_ID   NUMBER (11) NOT NULL,
   RC_TARIFF_TYPE_ID          NUMBER (3) NOT NULL,
   STATUS_ID                  NUMBER (3),
   TARIFF_VALUE               NUMBER (15, 3),
   FULL_CYCLE                 CHAR (1 CHAR)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.RC_TARIFF_TYPE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.RC_TARIFF_TYPE
(
   RC_TARIFF_TYPE_ID   NUMBER (3) NOT NULL,
   TYPE_NAME           VARCHAR2 (63 BYTE) NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.SUBSCRIBER CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER
(
   SUBSCRIBER_ID    NUMBER (15) NOT NULL,
   SUBSCRIBER_NO    VARCHAR2 (31 BYTE) NOT NULL,
   RATING_TYPE_ID   NUMBER (3) NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.SUBSCRIBER_STATUS CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_STATUS
(
   STATUS_ID     NUMBER (3) NOT NULL,
   STATUS_NAME   VARCHAR2 (63 BYTE) NOT NULL,
   NRC           NUMBER (15, 3),
   CURRENCY_ID   NUMBER (3) NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.SUBSCRIBER_VERSION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_VERSION
(
   SUBSCRIBER_VERSION_ID   NUMBER (23) NOT NULL,
   FROM_DATE               DATE NOT NULL,
   TO_DATE                 DATE,
   SUBSCRIBER_ID           NUMBER (15),
   CUSTOMER_ID             NUMBER (15),
   MODIFIED_DATE           DATE,
   EFFECTIVE_DATE          DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.SUBS_BU_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_BU_MAP
(
   BU_ID           VARCHAR2 (7 BYTE) NOT NULL,
   SUBSCRIBER_ID   NUMBER (15) NOT NULL,
   FROM_DATE       DATE NOT NULL,
   TO_DATE         DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

DROP TABLE VNP_COMMON.NW_ZONE_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.NW_ZONE_MAP
(
  CODE      VARCHAR2(23 BYTE),
  ZONE      VARCHAR2(63 BYTE),
  NW_GROUP  VARCHAR2(7 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP DROP PRIMARY KEY CASCADE;

DROP TABLE VNP_COMMON.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_OFFER_MAP
(
   SUBSCRIBER_ID       NUMBER (15) NOT NULL,
   FROM_DATE           DATE NOT NULL,
   TO_DATE             DATE,
   PRODUCT_OFFER_ID    NUMBER (10) NOT NULL,
   SUBS_OFFER_MAP_ID   NUMBER (23),
   MODIFIED_DATE       DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE VNP_COMMON.SUBS_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_STATUS_MAP
(
   SUBSCRIBER_ID   NUMBER (15) NOT NULL,
   STATUS_ID       NUMBER (3) NOT NULL,
   START_DATE      DATE NOT NULL,
   END_DATE        DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_COMMON.SUBS_OFFER_MAP_PK
   ON VNP_COMMON.SUBS_OFFER_MAP (SUBS_OFFER_MAP_ID)
   LOGGING
   TABLESPACE VNP_COMMON
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;



CREATE OR REPLACE TRIGGER VNP_COMMON.ACCOUNT_VERSION_TRG
   BEFORE INSERT
   ON VNP_COMMON.ACCOUNT_VERSION
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column ACCOUNT_VERSION_ID
   :new.ACCOUNT_VERSION_ID := ACCOUNT_VERSION_SEQ.NEXTVAL;
END ACCOUNT_VERSION_TRG;
/


-- CREATE OR REPLACE TRIGGER VNP_COMMON.SUBSCRIBER_TRG
   -- BEFORE INSERT
   -- ON VNP_COMMON.SUBSCRIBER
   -- REFERENCING NEW AS New OLD AS Old
   -- FOR EACH ROW
-- BEGIN
   -- -- For Toad:  Highlight column SUBSCRIBER_ID
   -- :new.SUBSCRIBER_ID := SUBSCRIBER_SEQ.NEXTVAL;
-- END SUBSCRIBER_TRG;
-- /


CREATE OR REPLACE TRIGGER VNP_COMMON.SUBSCRIBER_VERSION_TRG
   BEFORE INSERT
   ON VNP_COMMON.SUBSCRIBER_VERSION
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBSCRIBER_VERSION_ID
   :new.SUBSCRIBER_VERSION_ID := SUBSCRIBER_VERSION_SEQ.NEXTVAL;
END SUBSCRIBER_VERSION_TRG;
/


CREATE OR REPLACE TRIGGER VNP_COMMON.SUBS_OFFER_MAP_TRG
   BEFORE INSERT
   ON VNP_COMMON.SUBS_OFFER_MAP
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBS_OFFER_MAP_ID
   :new.SUBS_OFFER_MAP_ID := SUBS_OFFER_MAP_SEQ.NEXTVAL;
END SUBS_OFFER_MAP_TRG;
/


ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP ADD (
  CONSTRAINT SUBS_OFFER_MAP_PK
  PRIMARY KEY
  (SUBS_OFFER_MAP_ID)
  USING INDEX VNP_COMMON.SUBS_OFFER_MAP_PK
  ENABLE VALIDATE);