DROP SEQUENCE PCAT_FILTER.SUBSCRIBER_VERSION_SEQ;

CREATE SEQUENCE PCAT_FILTER.SUBSCRIBER_VERSION_SEQ
  START WITH 876561
  MAXVALUE 99999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;








DROP TABLE PCAT_FILTER.SUBSCRIBER_VERSION CASCADE CONSTRAINTS;

CREATE TABLE PCAT_FILTER.SUBSCRIBER_VERSION
(
  SUBSCRIBER_VERSION_ID  NUMBER(23)             NOT NULL,
  FROM_DATE              DATE                   NOT NULL,
  TO_DATE                DATE,
  SUBSCRIBER_ID          NUMBER(15),
  CUSTOMER_ID            NUMBER(15),
  MODIFIED_DATE          DATE,
  EFFECTIVE_DATE         DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER PCAT_FILTER.SUBSCRIBER_VERSION_TRG
BEFORE INSERT
ON PCAT_FILTER.SUBSCRIBER_VERSION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column SUBSCRIBER_VERSION_ID
  :new.SUBSCRIBER_VERSION_ID := SUBSCRIBER_VERSION_SEQ.nextval;
END SUBSCRIBER_VERSION_TRG;
/
