/* Formatted on 05/03/2014 15:03:40 (QP5 v5.215.12089.38647) */
--DROP TABLE PRICE_MODEL CASCADE CONSTRAINTS;

--DESC PRICE_MODEL;

--DESC unit_type;
--
--DESC rate_currency;


-- *** DONE
-- ÐÁNG RA PH?I ÐI THEO HU?NG TARIFF -> TARIFF SET -> TARIFF PLAN Ð? T?O RA
-- PRICE MODEL NHUNG VÌ VINAPHONE KHÔNG C?U HÌNH GIÁ PH?C T?P, NHI?U NH?T
-- LÀ 2 TIER NÊN CH? C?N L?Y T? TARIFF


DROP TABLE price_model;

CREATE TABLE PRICE_MODEL
(
   PRICE_MODEL_ID   NUMBER (10),
   PRICE_MODEL      VARCHAR2 (63 BYTE),
   STEP             NUMBER (2),
   TIER_FROM        NUMBER (23, 8),
   TIER_TO          NUMBER (23, 8),
   BEAT             NUMBER (23, 8),
   FACTOR           NUMBER (23, 8),
   CHARGE_BASE      NUMBER (23, 8),
   unit_type_id     NUMBER (6),
   unit_type_name   VARCHAR2 (240),
   currency_code    NUMBER (6),
   currency_value   VARCHAR2 (240),
   description      VARCHAR2 (720)
)
TABLESPACE pcat_filter
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PRICE_MODEL_U01
   ON PRICE_MODEL (PRICE_MODEL, STEP)
   LOGGING
   TABLESPACE pcat_filter
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT
            FLASH_CACHE DEFAULT
            CELL_FLASH_CACHE DEFAULT)
   NOPARALLEL;


ALTER TABLE PRICE_MODEL ADD (
  CONSTRAINT PRICE_MODEL_U01
  UNIQUE (PRICE_MODEL, STEP)
  USING INDEX PRICE_MODEL_U01
  ENABLE VALIDATE);