DROP DATABASE LINK PCAT_ELC_USER;

CREATE DATABASE LINK PCAT_ELC_USER
 CONNECT TO ELC_USER
 IDENTIFIED BY elc_user
 USING 'ELC_202_8_PCAT';


ELC_202_8_PCAT=
  (DESCRIPTION=
    (ADDRESS=
      (PROTOCOL=TCP)
      (HOST=192.9.202.8)
      (PORT=1521)
    )
    (CONNECT_DATA=
      (SERVER=dedicated)
      (SERVICE_NAME=PCAT)
    )
  )