/* Formatted on 3/16/2014 2:33:01 PM (QP5 v5.215.12089.38647) */
SELECT t1.AUT_ID AS autId,
       t2.RESELLER_VERSION_ID AS resellerVersionId,
       t2.IS_PRERATED AS isPrerated,
       t2.OPEN_ITEM_ID AS openItemId,
       t2.IS_LATE_FEE_EXEMPT AS isLateFeeExempt,
       t7.SERVICE_VERSION_ID AS serviceVersionId,
       t8.DISPLAY_VALUE AS unitsTypeKey,
       t2.UNIT_TYPE AS unitType,
       t13.DISPLAY_VALUE AS subTypeIdKey,
       t2.SUB_TYPE_ID AS subTypeId,
       t16.DISPLAY_VALUE AS applicationIdKey,
       t2.APPLICATION_ID AS applicationId,
       t19.DISPLAY_VALUE AS autInitialKey,
       t2.GENERATED_FROM AS generatedFrom,
       t2.ACTIVITY_CHAR_IDS AS activityCharIds,
       t22.DISPLAY_VALUE AS taxClassKey,
       t2.TAX_CLASS AS taxClass,
       t33.DISPLAY_VALUE AS productLineKey,
       t2.PRODUCT_LINE_ID AS productLineId,
       t36.DISPLAY_VALUE AS ratableUnitClassKey,
       t2.RATABLE_UNIT_CLASS AS ratableUnitClass,
       t3.LANGUAGE_CODE AS languageCode,
       t3.DISPLAY_VALUE AS displayValue,
       t3.DESCRIPTION AS description
  FROM cbs_owner.AUT_FINAL_KEY t1
       INNER JOIN cbs_owner.AUT_FINAL_REF t2
          ON t1.AUT_ID = t2.AUT_ID
       INNER JOIN cbs_owner.AUT_FINAL_VALUES t3
          ON     t2.AUT_ID = t3.AUT_ID
             AND t2.RESELLER_VERSION_ID = t3.RESELLER_VERSION_ID
       INNER JOIN cbs_owner.UNITS_TYPE_KEY t6
          ON t2.UNIT_TYPE = t6.UNIT_TYPE
       INNER JOIN cbs_owner.UNITS_TYPE_REF t7
          ON t6.UNIT_TYPE = t7.UNIT_TYPE AND t7.SERVICE_VERSION_ID = 1
       INNER JOIN cbs_owner.UNITS_TYPE_VALUES t8
          ON     t6.UNIT_TYPE = t8.UNIT_TYPE
             AND t8.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
             AND t8.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.SUB_TYPE_ID_KEY t11
          ON t2.SUB_TYPE_ID = t11.SUB_TYPE_ID
       LEFT OUTER JOIN cbs_owner.SUB_TYPE_ID_REF t12
          ON     t11.SUB_TYPE_ID = t12.SUB_TYPE_ID
             AND t12.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
       LEFT OUTER JOIN cbs_owner.SUB_TYPE_ID_VALUES t13
          ON     t11.SUB_TYPE_ID = t13.SUB_TYPE_ID
             AND t13.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
             AND t13.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.APPLICATION_ID_KEY t14
          ON t2.APPLICATION_ID = t14.APPLICATION_ID
       LEFT OUTER JOIN cbs_owner.APPLICATION_ID_REF t15
          ON     t14.APPLICATION_ID = t15.APPLICATION_ID
             AND t15.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
       LEFT OUTER JOIN cbs_owner.APPLICATION_ID_VALUES t16
          ON     t14.APPLICATION_ID = t16.APPLICATION_ID
             AND t16.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
             AND t16.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.AUT_INITIAL_KEY t17
          ON t2.GENERATED_FROM = t17.INITIAL_AUT_ID
       LEFT OUTER JOIN cbs_owner.AUT_INITIAL_REF t18
          ON     t17.INITIAL_AUT_ID = t18.INITIAL_AUT_ID
             AND t18.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
       LEFT OUTER JOIN cbs_owner.AUT_INITIAL_VALUES t19
          ON     t17.INITIAL_AUT_ID = t19.INITIAL_AUT_ID
             AND t19.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
             AND t19.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.TAX_CLASS_KEY t20
          ON t2.TAX_CLASS = t20.TAX_CLASS
       LEFT OUTER JOIN cbs_owner.TAX_CLASS_REF t21
          ON     t20.TAX_CLASS = t21.TAX_CLASS
             AND t21.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.TAX_CLASS_VALUES t22
          ON     t20.TAX_CLASS = t22.TAX_CLASS
             AND t22.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t22.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.PRODUCT_LINE_KEY t31
          ON t2.PRODUCT_LINE_ID = t31.PRODUCT_LINE_ID
       LEFT OUTER JOIN cbs_owner.PRODUCT_LINE_REF t32
          ON     t31.PRODUCT_LINE_ID = t32.PRODUCT_LINE_ID
             AND t32.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN cbs_owner.PRODUCT_LINE_VALUES t33
          ON     t31.PRODUCT_LINE_ID = t33.PRODUCT_LINE_ID
             AND t33.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t33.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN cbs_owner.RATABLE_UNIT_CLASS_KEY t34
          ON t2.RATABLE_UNIT_CLASS = t34.RATABLE_UNIT_CLASS
       LEFT OUTER JOIN cbs_owner.RATABLE_UNIT_CLASS_REF t35
          ON     t34.RATABLE_UNIT_CLASS = t35.RATABLE_UNIT_CLASS
             AND t35.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
       LEFT OUTER JOIN cbs_owner.RATABLE_UNIT_CLASS_VALUES t36
          ON     t34.RATABLE_UNIT_CLASS = t36.RATABLE_UNIT_CLASS
             AND t36.SERVICE_VERSION_ID = t7.SERVICE_VERSION_ID
             AND t36.LANGUAGE_CODE = t3.LANGUAGE_CODE
 WHERE t2.RESELLER_VERSION_ID = 2 AND t3.LANGUAGE_CODE = 1;