/* Formatted on 3/15/2014 5:04:01 PM (QP5 v5.215.12089.38647) */
SELECT t1.RT_PROMO_PI_MAP_ID AS rtPromoPiMapId,
       t1.RESELLER_VERSION_ID AS resellerVersionId,
       t1.RT_PROMOTION_PLAN_ID AS rtPromotionPlanId,
       t1.DISCOUNT_ITEM_ID AS discountItemId,
       t2.DISPLAY_VALUE AS name,
       t2.DESCRIPTION AS description
  FROM    cbs_owner.RT_PROMOTION_PLAN_ITEM_MAP t1
       LEFT OUTER JOIN
          cbs_owner.RT_DISCOUNT_ITEM_VALUES t2
       ON     t1.DISCOUNT_ITEM_ID = t2.DISCOUNT_ITEM_ID
          AND t2.LANGUAGE_CODE = 1
          AND t2.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
 WHERE t1.RESELLER_VERSION_ID = 2 AND t1.DISCOUNT_ITEM_ID IS NOT NULL;