/* Formatted on 05/12/2014 4:58:38 PM (QP5 v5.215.12089.38647) */
EXEC DBMS_REDEFINITION.CAN_REDEF_TABLE('VNP_DATA','HOT_RATED_CDR');

EXEC DBMS_REDEFINITION.START_REDEF_TABLE('VNP_DATA','HOT_RATED_CDR','HOT_RATED_CDR_NEW');


--  VARIABLE v_num NUMBER;
--  EXEC DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS('VNP_DATA','HOT_RATED_CDR','HOT_RATED_CDR_NEW', 0,TRUE,TRUE,TRUE,FALSE,:v_num,FALSE);


EXEC DBMS_REDEFINITION.SYNC_INTERIM_TABLE('VNP_DATA','HOT_RATED_CDR','HOT_RATED_CDR_NEW');

SELECT * FROM vnp_data.hot_rated_cdr_new;

EXEC DBMS_REDEFINITION.FINISH_REDEF_TABLE('VNP_DATA','HOT_RATED_CDR','HOT_RATED_CDR_NEW');

EXEC DBMS_REDEFINITION.ABORT_REDEF_TABLE('VNP_DATA','HOT_RATED_CDR','HOT_RATED_CDR_NEW');