/* Formatted on 21/11/2014 1:49:42 PM (QP5 v5.215.12089.38647) */
SELECT ACCOUNT_VERSION_ID,
       ALIAS,
       ACCOUNT_ID,
       SUBSCRIBER_NO,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM VNP_COMMON.ALIAS_SELECT;

SELECT * FROM subscriber;
select * from account_version;

SELECT ACCOUNT_VERSION_ID,
       SUBSCRIBER_NO AS ALIAS,
       ACCOUNT_ID,
       SUBSCRIBER_NO SUBSCRIBER_NO,
       ACCOUNT_VERSION.FROM_DATE AS FROM_DATE_TEST,
         (ACCOUNT_VERSION.FROM_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS FROM_DATE,
       ACCOUNT_VERSION.TO_DATE AS TO_DATE_TEST,
         (ACCOUNT_VERSION.TO_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE AS MODIFIED_DATE_TEST,
         (  ACCOUNT_VERSION.MODIFIED_DATE
          - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS MODIFIED_DATE
  FROM    SUBSCRIBER
       INNER JOIN
          ACCOUNT_VERSION
       ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID);

SELECT ACCOUNT_VERSION_ID,
       SUBSCRIBER_NO AS ALIAS,
       ACCOUNT_ID,
       SUBSCRIBER_NO SUBSCRIBER_NO,
       ACCOUNT_VERSION.FROM_DATE,
       ACCOUNT_VERSION.TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE
  FROM    SUBSCRIBER
       INNER JOIN
          ACCOUNT_VERSION
       ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID);


SELECT ACCOUNT_VERSION_ID,
       ACCOUNT_ID,
       MSN,
       EFFECTIVE_DATE,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM VNP_COMMON.AUDIT_SEGMENT_SELECT;

SELECT ACCOUNT_VERSION_ID,
       ACCOUNT_ID,
       NULL MSN,
       ACCOUNT_VERSION.EFFECTIVE_DATE AS EFFECTIVE_DATE_TEST,
         (  ACCOUNT_VERSION.EFFECTIVE_DATE
          - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS EFFECTIVE_DATE,
       ACCOUNT_VERSION.FROM_DATE AS FROM_DATE_TEST,
         (ACCOUNT_VERSION.FROM_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS FROM_DATE,
       ACCOUNT_VERSION.TO_DATE AS TO_DATE_TEST,
         (ACCOUNT_VERSION.TO_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE AS MODIFIED_DATE_TEST,
         (  ACCOUNT_VERSION.MODIFIED_DATE
          - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
       * 24
       * 60
       * 60
          AS MODIFIED_DATE
  FROM ACCOUNT_VERSION;



SELECT ACCOUNT_VERSION_ID,
       ACCOUNT_ID,
       NULL MSN,
       ACCOUNT_VERSION.EFFECTIVE_DATE,
       ACCOUNT_VERSION.FROM_DATE,
       ACCOUNT_VERSION.TO_DATE,
       ACCOUNT_VERSION.MODIFIED_DATE
  FROM ACCOUNT_VERSION;


SELECT ACCOUNT_VERSION_ID,
       ID,
       PRODUCT_OFFER_ID,
       SUBSCRIBER_NO,
       RESELLER_VERSION_ID,
       FROM_DATE,
       TO_DATE,
       MODIFIED_DATE
  FROM VNP_COMMON.PRODUCT_SELECT;

  SELECT ACCOUNT_VERSION_ID,
         SUBS_OFFER_MAP_ID AS ID,               -- PROD_VIEW_ID_NEXTVAL AS ID,
         PRODUCT_OFFER.OFFER_ID,
         PRODUCT_OFFER.OFFER_NAME,
         SUBSCRIBER_NO,
         RESELLER_VERSION_ID,                                   -- SERVICE_ID,
         SUBS_OFFER_MAP.FROM_DATE AS FROM_DATE_TEST,
           (SUBS_OFFER_MAP.FROM_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
         * 24
         * 60
         * 60
            AS FROM_DATE,
         SUBS_OFFER_MAP.TO_DATE AS TO_DATE_TEST,
           (SUBS_OFFER_MAP.TO_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
         * 24
         * 60
         * 60
            AS TO_DATE,
         SUBS_OFFER_MAP.MODIFIED_DATE AS MODIFIED_DATE_TEST,
           (SUBS_OFFER_MAP.MODIFIED_DATE - TO_DATE ('1970-01-01', 'yyyy-mm-dd'))
         * 24
         * 60
         * 60
            AS MODIFIED_DATE,
         PRODUCT_OFFER.OFFER_TYPE
    FROM SUBSCRIBER
         INNER JOIN SUBS_OFFER_MAP
            ON (SUBSCRIBER.SUBSCRIBER_ID = SUBS_OFFER_MAP.SUBSCRIBER_ID)
         INNER JOIN ACCOUNT_VERSION
            ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID)
         INNER JOIN PRODUCT_OFFER
            ON (PRODUCT_OFFER.OFFER_ID = SUBS_OFFER_MAP.PRODUCT_OFFER_ID)
ORDER BY DECODE (PRODUCT_OFFER.OFFER_TYPE,  'PO', 1,  'SO', 2,  3);


  SELECT ACCOUNT_VERSION_ID,
         SUBS_OFFER_MAP_ID AS ID,               -- PROD_VIEW_ID_NEXTVAL AS ID,
         PRODUCT_OFFER_ID,
         SUBSCRIBER_NO,
         RESELLER_VERSION_ID,                                   -- SERVICE_ID,
         SUBS_OFFER_MAP.FROM_DATE,
         SUBS_OFFER_MAP.TO_DATE,
         SUBS_OFFER_MAP.MODIFIED_DATE,
         PRODUCT_OFFER.OFFER_TYPE
    FROM SUBSCRIBER
         INNER JOIN SUBS_OFFER_MAP
            ON (SUBSCRIBER.SUBSCRIBER_ID = SUBS_OFFER_MAP.SUBSCRIBER_ID)
         INNER JOIN ACCOUNT_VERSION
            ON (SUBSCRIBER.SUBSCRIBER_ID = ACCOUNT_VERSION.SUBSCRIBER_ID)
         INNER JOIN PRODUCT_OFFER
            ON (PRODUCT_OFFER.OFFER_ID = SUBS_OFFER_MAP.PRODUCT_OFFER_ID)
ORDER BY DECODE (PRODUCT_OFFER.OFFER_TYPE,  'PO', 1,  'SO', 2,  3);


SELECT RESELLER_VERSION_ID, TARIFF_PLAN_ID, CALENDAR_ID
  FROM VNP_COMMON.TARIFF_PLAN
 WHERE tariff_plan_id = 0;

SELECT 'UsagePlan_' || V.UNIT_TYPE_NAME,
       'R',
       V.OFFER_ID,
       V.RESELLER_VERSION_ID,
       UA_ID,
       TARIFF_PLAN_ID || ':' || V.OFFER_TYPE,
       PO.OFFER_NAME
  FROM VNP_COMMON.USAGE_PLAN_VIEW V, PRODUCT_OFFER PO
 WHERE     V.offer_type = 'SO'
       AND UNIT_TYPE_NAME = 'SMS'
       AND V.OFFER_ID = PO.OFFER_ID;

-- WHERE offer_id = 51004508;

-- WHERE UA_ID = 30162;                      -- 30162

SELECT *
  FROM usage_activity
 WHERE unit_type_name = 'SMS';

-- WHERE ua_id = 30423;