/* Formatted on 23/3/2014 10:30:29 (QP5 v5.215.12089.38647) */
SELECT t25.USAGE_ITEM_ID AS usageItemId,
       t26.RESELLER_VERSION_ID AS resellerVersionId,
       t46.DISPLAY_VALUE AS autFinalKey,
       t26.AUT_ID AS autId,
       t49.DISPLAY_VALUE AS tariffPlanKey,
       t26.TARIFF_PLAN_ID AS tariffPlanId,
       t26.IS_DEFAULT_ACTIVITY AS isDefaultActivity,
       t26.CHARGE_CODE AS chargeCode,
       t27.LANGUAGE_CODE AS languageCode,
       t27.DISPLAY_VALUE AS displayValue,
       t27.DESCRIPTION AS description
  FROM USAGE_ITEM_KEY t25
       INNER JOIN USAGE_ITEM_REF t26
          ON t25.USAGE_ITEM_ID = t26.USAGE_ITEM_ID
       INNER JOIN USAGE_ITEM_VALUES t27
          ON     t26.USAGE_ITEM_ID = t27.USAGE_ITEM_ID
             AND t26.RESELLER_VERSION_ID = t27.RESELLER_VERSION_ID
       INNER JOIN AUT_FINAL_KEY t44
          ON t26.AUT_ID = t44.AUT_ID
       INNER JOIN AUT_FINAL_REF t45
          ON     t44.AUT_ID = t45.AUT_ID
             AND t45.RESELLER_VERSION_ID = t26.RESELLER_VERSION_ID
       INNER JOIN AUT_FINAL_VALUES t46
          ON     t44.AUT_ID = t46.AUT_ID
             AND t46.RESELLER_VERSION_ID = t26.RESELLER_VERSION_ID
             AND t46.LANGUAGE_CODE = t27.LANGUAGE_CODE
       INNER JOIN TARIFF_PLAN_KEY t47
          ON t26.TARIFF_PLAN_ID = t47.TARIFF_PLAN_ID
       INNER JOIN TARIFF_PLAN_REF t48
          ON     t47.TARIFF_PLAN_ID = t48.TARIFF_PLAN_ID
             AND t48.RESELLER_VERSION_ID = t26.RESELLER_VERSION_ID
       INNER JOIN TARIFF_PLAN_VALUES t49
          ON     t47.TARIFF_PLAN_ID = t49.TARIFF_PLAN_ID
             AND t49.RESELLER_VERSION_ID = t26.RESELLER_VERSION_ID
             AND t49.LANGUAGE_CODE = t27.LANGUAGE_CODE
 WHERE t26.RESELLER_VERSION_ID = 2 AND t27.LANGUAGE_CODE = 1;