DROP TABLE VNP_DATA.ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.ACTION_LOG
(
  LOG_USER_NAME    VARCHAR2(255 BYTE)           NOT NULL,
  LOG_ACTION       VARCHAR2(511 BYTE),
  LOG_DESCRIPTION  VARCHAR2(3071 BYTE),
  LOG_TIME         DATE,
  LOG_LEVEL        NUMBER(1),
  LOG_ID           NUMBER
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.ACTION_LOG TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.ACTION_LOG TO VNP_COMMON;
