DROP TABLE VNP_DATA.CDR_RECORD_HEADER CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.CDR_RECORD_HEADER
(
  CDR_RECORD_HEADER_ID       NUMBER(10),
  RECORD_ID                  VARCHAR2(3 BYTE),
  XOR_CHECKSUM               NUMBER(3),
  HOST_NAME                  VARCHAR2(33 BYTE),
  START_RCD_SEQ              VARCHAR2(11 BYTE),
  END_RCD_SEQ                VARCHAR2(11 BYTE),
  FILE_CREATION_TIMESTAMP    VARCHAR2(32 BYTE),
  FILE_LASTUPDATE_TIMESTAMP  VARCHAR2(32 BYTE),
  NUMBER_OF_RECORD           NUMBER(11),
  CHECKSUM_VALID             NUMBER(3),
  CDR_FILENAME               VARCHAR2(60 BYTE),
  CONVERT_TIME               DATE               DEFAULT SYSDATE
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_DATA.CDR_RECORD_HEADER_HEADER_ID ON VNP_DATA.CDR_RECORD_HEADER
(CDR_RECORD_HEADER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.CDR_RECORD_HEADER TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.CDR_RECORD_HEADER TO VNP_COMMON;
