DROP TABLE VNP_DATA.HOT_AGGREGATED_CDR CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.HOT_AGGREGATED_CDR
(
  A_NUMBER             VARCHAR2(31 BYTE),
  CDR_TYPE             NUMBER(2),
  TOTAL_CDR            NUMBER(21),
  BILL_MONTH           DATE,
  TOTAL_USAGE          NUMBER(38,3),
  SERVICE_FEE          NUMBER(25,3),
  CHARGE_FEE           NUMBER(25,3),
  OFFER_COST           NUMBER(25,3),
  OFFER_FREE_BLOCK     NUMBER(21),
  INTERNAL_COST        NUMBER(25,3),
  INTERNAL_FREE_BLOCK  NUMBER(21),
  AUT_FINAL_ID         NUMBER(6)
)
TABLESPACE AGGREGATE_CDR_TBS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_DATA.HOT_AGGREGATED_CDR_A_NUMBER ON VNP_DATA.HOT_AGGREGATED_CDR
(A_NUMBER)
LOGGING
TABLESPACE AGGREGATE_CDR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_DATA.HOT_AGGREGATED_CDR_BILL_MONTH ON VNP_DATA.HOT_AGGREGATED_CDR
(BILL_MONTH)
LOGGING
TABLESPACE AGGREGATE_CDR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_DATA.HOT_AGGREGATED_CDR_CDR_TYPE ON VNP_DATA.HOT_AGGREGATED_CDR
(CDR_TYPE)
LOGGING
TABLESPACE AGGREGATE_CDR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_DATA.HOT_AGGR_PAYMENT_ITEM_ID ON VNP_DATA.HOT_AGGREGATED_CDR
(AUT_FINAL_ID)
LOGGING
TABLESPACE AGGREGATE_CDR_IDX_TBS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.HOT_AGGREGATED_CDR TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.HOT_AGGREGATED_CDR TO VNP_COMMON;
