/* Formatted on 3/23/2014 9:13:11 PM (QP5 v5.215.12089.38647) */
SELECT t1.BONUS_ITEM_ID AS bonusItemId,
       t2.RESELLER_VERSION_ID AS resellerVersionId,
       t6.DISPLAY_VALUE AS accumulatorKey,
       t2.ACCUMULATOR_ID AS accumulatorId,
       t8.SERVICE_VERSION_ID AS serviceVersionId,
       t8.ISO_CODE AS currencyIsoCode,
       t8.IMPLIED_DECIMAL AS currencyImpliedDecimal,
       t9.DISPLAY_VALUE AS rateCurrencyKey,
       t2.CURRENCY_CODE AS currencyCode,
       t12.DISPLAY_VALUE AS accumulatorKeyByAddonAccId1,
       t2.ADDON_ACC_ID1 AS addonAccId1,
       t15.DISPLAY_VALUE AS accumulatorKeyByAddonAccId2,
       t2.ADDON_ACC_ID2 AS addonAccId2,
       t18.DISPLAY_VALUE AS accumulatorKeyByAddonAccId3,
       t2.ADDON_ACC_ID3 AS addonAccId3,
       t21.DISPLAY_VALUE AS accumulatorKeyByAddonAccId4,
       t2.ADDON_ACC_ID4 AS addonAccId4,
       t2.RESET_FLAG AS resetFlag,
       t2.IS_INTERNAL AS isInternal,
       t2.IS_DEFAULT AS isDefault,
       t2.AWARD_TRIGGER AS awardTrigger,
       t2.CALC_DATE_BASED_ON AS calcDateBasedOn,
       t2.USE_ACTIVE_DAYS AS useActiveDays,
       t2.USE_BONUS_CYCLES AS useBonusCycles,
       t3.LANGUAGE_CODE AS languageCode,
       t3.DISPLAY_VALUE AS displayValue,
       t3.DESCRIPTION AS description
  FROM RT_BONUS_ITEM_KEY t1
       INNER JOIN RT_BONUS_ITEM_REF t2
          ON t1.BONUS_ITEM_ID = t2.BONUS_ITEM_ID
       INNER JOIN RT_BONUS_ITEM_VALUES t3
          ON     t2.BONUS_ITEM_ID = t3.BONUS_ITEM_ID
             AND t2.RESELLER_VERSION_ID = t3.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_KEY t4
          ON t2.ACCUMULATOR_ID = t4.ACCUMULATOR_ID
       LEFT OUTER JOIN ACCUMULATOR_REF t5
          ON     t4.ACCUMULATOR_ID = t5.ACCUMULATOR_ID
             AND t5.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_VALUES t6
          ON     t4.ACCUMULATOR_ID = t6.ACCUMULATOR_ID
             AND t6.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t6.LANGUAGE_CODE = t3.LANGUAGE_CODE
       INNER JOIN RATE_CURRENCY_KEY t7
          ON t2.CURRENCY_CODE = t7.CURRENCY_CODE
       INNER JOIN RATE_CURRENCY_REF t8
          ON     t7.CURRENCY_CODE = t8.CURRENCY_CODE
             AND t8.SERVICE_VERSION_ID = 1
       INNER JOIN RATE_CURRENCY_VALUES t9
          ON     t7.CURRENCY_CODE = t9.CURRENCY_CODE
             AND t9.SERVICE_VERSION_ID = t8.SERVICE_VERSION_ID
             AND t9.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN ACCUMULATOR_KEY t10
          ON t2.ADDON_ACC_ID1 = t10.ACCUMULATOR_ID
       LEFT OUTER JOIN ACCUMULATOR_REF t11
          ON     t10.ACCUMULATOR_ID = t11.ACCUMULATOR_ID
             AND t11.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_VALUES t12
          ON     t10.ACCUMULATOR_ID = t12.ACCUMULATOR_ID
             AND t12.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t12.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN ACCUMULATOR_KEY t13
          ON t2.ADDON_ACC_ID2 = t13.ACCUMULATOR_ID
       LEFT OUTER JOIN ACCUMULATOR_REF t14
          ON     t13.ACCUMULATOR_ID = t14.ACCUMULATOR_ID
             AND t14.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_VALUES t15
          ON     t13.ACCUMULATOR_ID = t15.ACCUMULATOR_ID
             AND t15.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t15.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN ACCUMULATOR_KEY t16
          ON t2.ADDON_ACC_ID3 = t16.ACCUMULATOR_ID
       LEFT OUTER JOIN ACCUMULATOR_REF t17
          ON     t16.ACCUMULATOR_ID = t17.ACCUMULATOR_ID
             AND t17.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_VALUES t18
          ON     t16.ACCUMULATOR_ID = t18.ACCUMULATOR_ID
             AND t18.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t18.LANGUAGE_CODE = t3.LANGUAGE_CODE
       LEFT OUTER JOIN ACCUMULATOR_KEY t19
          ON t2.ADDON_ACC_ID4 = t19.ACCUMULATOR_ID
       LEFT OUTER JOIN ACCUMULATOR_REF t20
          ON     t19.ACCUMULATOR_ID = t20.ACCUMULATOR_ID
             AND t20.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
       LEFT OUTER JOIN ACCUMULATOR_VALUES t21
          ON     t19.ACCUMULATOR_ID = t21.ACCUMULATOR_ID
             AND t21.RESELLER_VERSION_ID = t2.RESELLER_VERSION_ID
             AND t21.LANGUAGE_CODE = t3.LANGUAGE_CODE
 WHERE t2.RESELLER_VERSION_ID = 2 AND t3.LANGUAGE_CODE = 1;