/* Formatted on 29/04/2014 10:35:57 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE TRIGGER RESELLER_VERSION_ARU_STATUS
   BEFORE UPDATE
   ON RESELLER_VERSION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
   WHEN (NEW.STATUS = 3 AND NEW.RESELLER_ID = 9)
DECLARE
   jno   BINARY_INTEGER;
BEGIN
   DBMS_JOB.submit (
      JOB         => jno,
      WHAT        =>    'BEGIN ELC_USER.CBS_OWNER_FILTER.START_JOB_FILTER_NEW_PCAT_DATA ('
                     || :NEW.RESELLER_VERSION_ID
                     || '); END;',
      NEXT_DATE   => SYSDATE);

   DBMS_OUTPUT.PUT_LINE ('Job Number:' || jno);
END;
/