DROP TABLE VNP_DATA.AGGREGATED_RC CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.AGGREGATED_RC
(
  SUBSCRIBER_ID  NUMBER(15),
  SUBSCRIBER_NO  VARCHAR2(31 BYTE),
  CURRENCY_CODE  NUMBER(6),
  RC             NUMBER(16,4),
  VAT            NUMBER(16,4),
  BILL_MONTH     DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE 4 INSTANCES 1 )
MONITORING;


CREATE INDEX VNP_DATA.AGGREGATED_RC_BILL_MONTH ON VNP_DATA.AGGREGATED_RC
(BILL_MONTH)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_DATA.AGGREGATED_RC_SUBSCRIBER_ID ON VNP_DATA.AGGREGATED_RC
(SUBSCRIBER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_DATA.AGGREGATED_RC_SUBSCRIBER_NO1 ON VNP_DATA.AGGREGATED_RC
(SUBSCRIBER_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.AGGREGATED_RC TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.AGGREGATED_RC TO VNP_COMMON;
