DROP TABLE VNP_DATA.BALANCE_COUNTER_DEV CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.BALANCE_COUNTER_DEV
(
  BAL_GROUP_ID  NUMBER(15),
  COUNTER_ID    NUMBER(11),
  RECORD_ID     NUMBER(11),
  VALID_FROM    NUMBER(11),
  VALID_TO      NUMBER(11),
  CURRENT_BAL   NUMBER(15,3)
)
TABLESPACE VNP_DATA_BALANCE_COUNTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.BALANCE_COUNTER_DEV TO VNP_COMMON;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.BALANCE_COUNTER_DEV TO VNP_COMMON_2;
