DROP TABLE VNP_DATA.CDR_LOG_PROCESS CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.CDR_LOG_PROCESS
(
  CDR_LOG_PROCESS_ID    NUMBER(10)              NOT NULL,
  SOURCE_FILE_URL       VARCHAR2(255 BYTE),
  OUTPUT_FILE_URL       VARCHAR2(255 BYTE),
  START_TIME            DATE,
  END_TIME              DATE,
  STATUS                VARCHAR2(10 BYTE),
  METHOD                CHAR(1 BYTE),
  SOURCE_FILE_BEHAVIOR  CHAR(1 BYTE),
  BACKUP_FILE_URL       VARCHAR2(255 BYTE),
  IS_HANDLED            VARCHAR2(20 BYTE),
  TOTAL_CDR             NUMBER(10),
  TOTAL_CDR_PROCESSED   NUMBER
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.CDR_LOG_PROCESS TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.CDR_LOG_PROCESS TO VNP_COMMON;
