DROP TABLE VNP_COMMON.SUBSCRIBER_VERSION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_VERSION
(
  SUBSCRIBER_VERSION_ID  NUMBER(23)             NOT NULL,
  FROM_DATE              DATE                   NOT NULL,
  TO_DATE                DATE,
  SUBSCRIBER_ID          NUMBER(15),
  CUSTOMER_ID            NUMBER(15),
  MODIFIED_DATE          DATE,
  EFFECTIVE_DATE         DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER VNP_COMMON.SUBSCRIBER_VERSION_TRG
   BEFORE INSERT
   ON VNP_COMMON.SUBSCRIBER_VERSION
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column SUBSCRIBER_VERSION_ID
   :new.SUBSCRIBER_VERSION_ID := SUBSCRIBER_VERSION_SEQ.NEXTVAL;
END SUBSCRIBER_VERSION_TRG;
/
