DROP PACKAGE VNP_DATA.REFORMAT_ENRICH;

CREATE OR REPLACE PACKAGE VNP_DATA.reformat_enrich AS

  /* TODO enter package declarations (types, exceptions, methods etc) here */
   PROCEDURE ENRICH_BU_1(NUMBER_RECORD OUT NUMBER,TIME_PROCESS OUT NUMBER);
   PROCEDURE ENRICH_BU_2(NUMBER_RECORD OUT NUMBER,TIME_PROCESS OUT NUMBER);
   PROCEDURE ENRICH_BU_TEST(NUMBER_RECORD OUT NUMBER,TIME_PROCESS OUT NUMBER);
   PROCEDURE PROCESS_RC_TMP;
   PROCEDURE MOVE_TMP_2_HOT_RC;
END REFORMAT_ENRICH;
/
