/* Formatted on 4/6/2014 10:58:23 AM (QP5 v5.227.12220.39754) */
CREATE TABLE ACTION_LOG
(
   LOG_TITLE      VARCHAR2 (255 BYTE),
   LOG_GROUP      VARCHAR2 (127 BYTE),
   LOG_CONTENT    VARCHAR2 (1023 BYTE),
   LOG_LEVEL      NUMBER (1),
   CREATED_TIME   DATE DEFAULT SYSDATE
)
TABLESPACE USERS;

COMMENT ON COLUMN ACTION_LOG.LOG_LEVEL IS '1: DEBUG Level
2: INFO Level
3: WARN Level
4: ERROR Level
5: FATAL Level';

CREATE TABLE CHANGE_FLAG (IS_CHANGING NUMBER (1))
TABLESPACE USERS;