/* Formatted on 18/4/2014 09:30:28 (QP5 v5.227.12220.39754) */
SELECT t4.DISPLAY_VALUE AS offerKey,
       t1.OFFER_ID AS offerId,
       t7.DISPLAY_VALUE AS usagePlanKey,
       t1.USAGE_PLAN_ID AS usagePlanId,
       t1.RESELLER_VERSION_ID AS resellerVersionId
  FROM OFFER_USAGE_PLAN_MAP t1
       INNER JOIN OFFER_KEY t2 ON t1.OFFER_ID = t2.OFFER_ID
       INNER JOIN
       OFFER_REF t3
          ON     t2.OFFER_ID = t3.OFFER_ID
             AND t3.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
       INNER JOIN
       OFFER_VALUES t4
          ON     t2.OFFER_ID = t4.OFFER_ID
             AND t4.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
             AND t4.LANGUAGE_CODE = 1
       INNER JOIN USAGE_PLAN_KEY t5 ON t1.USAGE_PLAN_ID = t5.USAGE_PLAN_ID
       INNER JOIN
       USAGE_PLAN_REF t6
          ON     t5.USAGE_PLAN_ID = t6.USAGE_PLAN_ID
             AND t6.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
       INNER JOIN
       USAGE_PLAN_VALUES t7
          ON     t5.USAGE_PLAN_ID = t7.USAGE_PLAN_ID
             AND t7.RESELLER_VERSION_ID = t1.RESELLER_VERSION_ID
             AND t7.LANGUAGE_CODE = t4.LANGUAGE_CODE
 WHERE t1.RESELLER_VERSION_ID = 2;