/* Formatted on 23/3/2014 10:14:42 (QP5 v5.215.12089.38647) */
SELECT t7.DISPLAY_VALUE AS usagePlanKey,
       t21.USAGE_PLAN_ID AS usagePlanId,
       t27.DISPLAY_VALUE AS usageItemKey,
       t21.USAGE_ITEM_ID AS usageItemId,
       t21.RESELLER_VERSION_ID AS resellerVersionId,
       t21.IS_USAGE_SPLIT AS isUsageSplit,
       t21.RESERVATION_AMT AS reservationAmt,
       t21.RESERVATION_LIFETIME AS reservationLifetime,
       t21.RESERVATION_MAX_NUM AS reservationMaxNum,
       t21.RESERVATION_MIN_AMT AS reservationMinAmt,
       t21.RESERVATION_MAX_AMT AS reservationMaxAmt,
       t21.ASSUME_CONSUMPTION AS assumeConsumption,
       t21.INHIBIT_REFUND AS inhibitRefund
  FROM USAGE_PLAN_ITEM_MAP t21
       INNER JOIN USAGE_PLAN_KEY t5
          ON t21.USAGE_PLAN_ID = t5.USAGE_PLAN_ID
       INNER JOIN USAGE_PLAN_REF t6
          ON     t5.USAGE_PLAN_ID = t6.USAGE_PLAN_ID
             AND t6.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
       INNER JOIN USAGE_PLAN_VALUES t7
          ON     t5.USAGE_PLAN_ID = t7.USAGE_PLAN_ID
             AND t7.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
             AND t7.LANGUAGE_CODE = 1
       INNER JOIN USAGE_ITEM_KEY t25
          ON t21.USAGE_ITEM_ID = t25.USAGE_ITEM_ID
       INNER JOIN USAGE_ITEM_REF t26
          ON     t25.USAGE_ITEM_ID = t26.USAGE_ITEM_ID
             AND t26.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
       INNER JOIN USAGE_ITEM_VALUES t27
          ON     t25.USAGE_ITEM_ID = t27.USAGE_ITEM_ID
             AND t27.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
             AND t27.LANGUAGE_CODE = t7.LANGUAGE_CODE
 WHERE t21.RESELLER_VERSION_ID = 2;