/* Formatted on 17/03/2014 17:27:20 (QP5 v5.215.12089.38647) */
SELECT t21.RT_PROMO_PI_MAP_ID AS rtPromoPiMapId,
       t21.RESELLER_VERSION_ID AS resellerVersionId,
       t24.DISPLAY_VALUE AS rtPromotionPlanKey,
       t21.RT_PROMOTION_PLAN_ID AS rtPromotionPlanId,
       t27.DISPLAY_VALUE AS rtBonusItemKey,
       t21.BONUS_ITEM_ID AS bonusItemId,
       t30.DISPLAY_VALUE AS rtDiscountItemKey,
       t21.DISCOUNT_ITEM_ID AS discountItemId
  FROM RT_PROMOTION_PLAN_ITEM_MAP t21
       INNER JOIN RT_PROMOTION_PLAN_KEY t22
          ON t21.RT_PROMOTION_PLAN_ID = t22.RT_PROMOTION_PLAN_ID
       INNER JOIN RT_PROMOTION_PLAN_REF t23
          ON     t22.RT_PROMOTION_PLAN_ID = t23.RT_PROMOTION_PLAN_ID
             AND t23.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
       INNER JOIN RT_PROMOTION_PLAN_VALUES t24
          ON     t22.RT_PROMOTION_PLAN_ID = t24.RT_PROMOTION_PLAN_ID
             AND t24.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
             AND t24.LANGUAGE_CODE = 1
       LEFT OUTER JOIN RT_BONUS_ITEM_KEY t25
          ON t21.BONUS_ITEM_ID = t25.BONUS_ITEM_ID
       LEFT OUTER JOIN RT_BONUS_ITEM_REF t26
          ON     t25.BONUS_ITEM_ID = t26.BONUS_ITEM_ID
             AND t26.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
       LEFT OUTER JOIN RT_BONUS_ITEM_VALUES t27
          ON     t25.BONUS_ITEM_ID = t27.BONUS_ITEM_ID
             AND t27.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
             AND t27.LANGUAGE_CODE = t24.LANGUAGE_CODE
       LEFT OUTER JOIN RT_DISCOUNT_ITEM_KEY t28
          ON t21.DISCOUNT_ITEM_ID = t28.DISCOUNT_ITEM_ID
       LEFT OUTER JOIN RT_DISCOUNT_ITEM_REF t29
          ON     t28.DISCOUNT_ITEM_ID = t29.DISCOUNT_ITEM_ID
             AND t29.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
       LEFT OUTER JOIN RT_DISCOUNT_ITEM_VALUES t30
          ON     t28.DISCOUNT_ITEM_ID = t30.DISCOUNT_ITEM_ID
             AND t30.RESELLER_VERSION_ID = t21.RESELLER_VERSION_ID
             AND t30.LANGUAGE_CODE = t24.LANGUAGE_CODE      
 WHERE t21.RESELLER_VERSION_ID = 2;