DROP TABLE VNP_DATA.DISCOUNT_COUNTER CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.DISCOUNT_COUNTER
(
  DIS_GROUP_ID  NUMBER(11),
  COUNTER_ID    NUMBER(11),
  RECORD_ID     NUMBER(11),
  VALID_FROM    NUMBER(11),
  VALID_TO      NUMBER(11),
  AMOUNT        NUMBER(15,3)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
