/* Formatted on 30/11/2014 2:20:10 PM (QP5 v5.215.12089.38647) */
CREATE USER dba1
    IDENTIFIED BY dba1
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK;

GRANT CREATE SESSION TO dba1;

-- 8 Roles for dba1
GRANT EXP_FULL_DATABASE TO dba1 WITH ADMIN OPTION;
GRANT IMP_FULL_DATABASE TO dba1 WITH ADMIN OPTION;
GRANT AUTHENTICATEDUSER TO dba1 WITH ADMIN OPTION;
GRANT DATAPUMP_EXP_FULL_DATABASE TO dba1 WITH ADMIN OPTION;
GRANT DATAPUMP_IMP_FULL_DATABASE TO dba1 WITH ADMIN OPTION;
-- GRANT ORA_ASPNET_MEM_BASICACCESS TO dba1 WITH ADMIN OPTION;
GRANT CONNECT TO dba1 WITH ADMIN OPTION;
GRANT DBA TO dba1 WITH ADMIN OPTION;
ALTER USER dba1 DEFAULT ROLE ALL;
-- 2 System Privileges for dba1
GRANT IMPORT FULL DATABASE TO dba1 WITH ADMIN OPTION;

GRANT UNLIMITED TABLESPACE TO dba1 WITH ADMIN OPTION;