CREATE USER vnp_view IDENTIFIED BY vnp_view
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
ALTER USER vnp_view QUOTA UNLIMITED ON USERS;
GRANT SELECT ANY DICTIONARY TO vnp_view;
GRANT CREATE SESSION TO vnp_view;
GRANT UNLIMITED TABLESPACE to vnp_view;
GRANT ALTER SESSION to vnp_view;
GRANT CREATE SYNONYM TO vnp_view;
GRANT CREATE ROLE TO vnp_view;
GRANT CREATE TRIGGER TO vnp_view;
GRANT CREATE TABLE TO vnp_view;
GRANT CREATE VIEW TO vnp_view;
GRANT CREATE PROCEDURE TO vnp_view;
GRANT DROP PUBLIC SYNONYM TO vnp_view;
GRANT CREATE PUBLIC SYNONYM TO vnp_view;
GRANT CREATE SEQUENCE TO vnp_view;

GRANT CREATE ANY TRIGGER TO vnp_view;