/* Formatted on 4/6/2014 10:55:24 AM (QP5 v5.227.12220.39754) */
DROP TABLE ACCUMULATOR CASCADE CONSTRAINTS;

CREATE TABLE ACCUMULATOR
(
   ACCUMULATOR_ID        NUMBER (10) NOT NULL,
   ACCUMULATOR_NAME      VARCHAR2 (240 BYTE) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   UNIT_TYPE_NAME        VARCHAR2 (240 BYTE) NOT NULL,
   UNIT_TYPE_ID          NUMBER (6) NOT NULL,
   PERIOD                VARCHAR2 (240 BYTE),
   RESET_POINT           NUMBER NOT NULL,
   ACCUMULATOR_TYPE      VARCHAR2 (240 BYTE),
   COUNT_TYPE            VARCHAR2 (240 BYTE),
   DESCRIPTION           VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE ACTION_LOG
(
   LOG_TITLE      VARCHAR2 (255 BYTE),
   LOG_GROUP      VARCHAR2 (127 BYTE),
   LOG_CONTENT    VARCHAR2 (1023 BYTE),
   LOG_LEVEL      NUMBER (1),
   CREATED_TIME   DATE DEFAULT SYSDATE
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN ACTION_LOG.LOG_LEVEL IS '1: DEBUG Level
2: INFO Level
3: WARN Level
4: ERROR Level
5: FATAL Level';



DROP TABLE BALANCE CASCADE CONSTRAINTS;

CREATE TABLE BALANCE
(
   BALANCE_ID            NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   UNIT_TYPE_NAME        VARCHAR2 (240 BYTE) NOT NULL,
   UNIT_TYPE_ID          NUMBER (6) NOT NULL,
   BALANCE_NAME          VARCHAR2 (240 BYTE) NOT NULL,
   DESCRIPTION           VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE CHANGE_FLAG CASCADE CONSTRAINTS;

CREATE TABLE CHANGE_FLAG (IS_CHANGING NUMBER (1))
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE CURRENCY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE CURRENCY_TYPE
(
   CURRENCY_CODE     NUMBER (6) NOT NULL,
   CURRENCY_NAME     VARCHAR2 (240 BYTE) NOT NULL,
   TYPE_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   TYPE_ID           CHAR (1 BYTE) NOT NULL,
   ACTIVE_DATE       DATE NOT NULL,
   INACTIVE_DATE     DATE,
   ROUNDING_FACTOR   NUMBER (6) NOT NULL,
   ISO_CODE          VARCHAR2 (4 BYTE),
   ISO_NUMBER        NUMBER (3),
   DESCRIPTION       VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE DISCOUNT_MODEL CASCADE CONSTRAINTS;

CREATE TABLE DISCOUNT_MODEL
(
   DISCOUNT_ITEM_ID      NUMBER NOT NULL,
   DISCOUNT_ITEM_NAME    VARCHAR2 (240 BYTE) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   DISCOUNT_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   DISCOUNT_ID           NUMBER (10) NOT NULL,
   UA_NAME               VARCHAR2 (240 BYTE),
   UA_ID                 NUMBER (10),
   UA_GROUP_NAME         VARCHAR2 (240 BYTE),
   UA_GROUP_ID           NUMBER (6),
   ITEM_DESC             VARCHAR2 (720 BYTE),
   ACCUMULATOR_NAME      VARCHAR2 (240 BYTE) NOT NULL,
   ACCUMULATOR_ID        NUMBER (10) NOT NULL,
   DISCOUNT_TYPE         VARCHAR2 (240 BYTE),
   CURRENCY_NAME         VARCHAR2 (240 BYTE),
   CURRENCY_CODE         NUMBER (6),
   DISCOUNT_DESC         VARCHAR2 (720 BYTE),
   AWARD_ID              NUMBER (10) NOT NULL,
   AWARD_NAME            VARCHAR2 (240 BYTE),
   THRESHOLD             NUMBER (22, 8) NOT NULL,
   AMOUNT                NUMBER (22, 8) NOT NULL,
   AWARD_DESC            VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE OFFER_BALANCE_MAP CASCADE CONSTRAINTS;

CREATE TABLE OFFER_BALANCE_MAP
(
   BALANCE_NAME                VARCHAR2 (240 BYTE) NOT NULL,
   BALANCE_ID                  NUMBER (10) NOT NULL,
   OFFER_NAME                  VARCHAR2 (240 BYTE) NOT NULL,
   OFFER_ID                    NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID         NUMBER (18) NOT NULL,
   BALANCE_ORDER               NUMBER (6) NOT NULL,
   IS_SHADOW                   NUMBER,
   IS_CORE                     NUMBER (1) NOT NULL,
   EXPIRATION_DATE             DATE,
   MIN_BALANCE                 NUMBER (22, 8),
   MAX_BALANCE                 NUMBER (22, 8),
   EXPIRATION_OPTION           VARCHAR2 (240 BYTE),
   DEFAULT_EXPIRATION_OFFSET   NUMBER (18) NOT NULL,
   IS_SHARED                   NUMBER (1) NOT NULL,
   DEFAULT_LIMIT_TYPE          VARCHAR2 (240 BYTE),
   DEFAULT_LIMIT_VALUE         NUMBER (22, 8),
   DEFAULT_LIMIT_PERIOD        VARCHAR2 (240 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PRODUCT_OFFER CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT_OFFER
(
   OFFER_ID              NUMBER (10) NOT NULL,
   OFFER_NAME            VARCHAR2 (240 BYTE) NOT NULL,
   OFFER_ABBREVIATION    VARCHAR2 (31 BYTE),
   UNBILL                CHAR (1 BYTE),
   B_NUMBER_ENRICH       VARCHAR2 (31 BYTE),
   PRODUCT_GROUP_TYPE    VARCHAR2 (31 BYTE),
   PARENT_ID             NUMBER (10),
   OFFER_TYPE            VARCHAR2 (31 BYTE),
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE PROMO_MAP CASCADE CONSTRAINTS;

CREATE TABLE PROMO_MAP
(
   OFFER_ID              NUMBER (10) NOT NULL,
   OFFER_NAME            VARCHAR2 (240 BYTE) NOT NULL,
   PROMO_PLAN_NAME       VARCHAR2 (240 BYTE) NOT NULL,
   PROMO_PLAN_ID         NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   BONUS_ITEM_NAME       VARCHAR2 (240 BYTE),
   BONUS_ITEM_ID         NUMBER,
   DISCOUNT_ITEM_NAME    VARCHAR2 (240 BYTE),
   DISCOUNT_ITEM_ID      NUMBER
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RESELLER_VERSION CASCADE CONSTRAINTS;

CREATE TABLE RESELLER_VERSION
(
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   RESELLER_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   RESELLER_ID           NUMBER (10) NOT NULL,
   ACTIVE_DATE           DATE NOT NULL,
   INACTIVE_DATE         DATE,
   STATUS                NUMBER (3) NOT NULL
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE RUM_MAP CASCADE CONSTRAINTS;

CREATE TABLE RUM_MAP
(
   TARIFF_SET_MEMBER_ID   NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID    NUMBER (18) NOT NULL,
   TARIFF_SET_NAME        VARCHAR2 (240 BYTE) NOT NULL,
   TARIFF_SET_ID          NUMBER NOT NULL,
   UNIT_TYPE_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   UNIT_TYPE_ID           NUMBER (6) NOT NULL,
   TIME_TYPE_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   TIME_TYPE_ID           NUMBER (10) NOT NULL,
   TARIFF_MODEL_NAME      VARCHAR2 (240 BYTE),
   TARIFF_MODEL_ID        NUMBER (10),
   IS_PRIMARY             NUMBER (1),
   RUM_TYPE               VARCHAR2 (7 BYTE),
   CONSUME_FLAG           NUMBER,
   STEP                   NUMBER
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TARIFF_MODEL CASCADE CONSTRAINTS;

CREATE TABLE TARIFF_MODEL
(
   TARIFF_MODEL_ID       NUMBER (10),
   TARIFF_MODEL_NAME     VARCHAR2 (240 BYTE),
   RESELLER_VERSION_ID   NUMBER (18),
   STEP                  NUMBER,
   TIER_FROM             NUMBER,
   TIER_TO               NUMBER,
   BEAT                  NUMBER (22, 8),
   FACTOR                NUMBER (22, 8),
   CHARGE_BASE           NUMBER (22, 8),
   DESCRIPTION           VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TARIFF_PLAN CASCADE CONSTRAINTS;

CREATE TABLE TARIFF_PLAN
(
   TARIFF_PLAN_MAPPING_ID   NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID      NUMBER (18) NOT NULL,
   TARIFF_PLAN_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   TARIFF_PLAN_ID           NUMBER (10) NOT NULL,
   DEFAULT_CURRENCY_NAME    VARCHAR2 (240 BYTE),
   DEFAULT_CURRENCY_CODE    NUMBER (6),
   TARIFF_SET_NAME          VARCHAR2 (240 BYTE) NOT NULL,
   TARIFF_SET_ID            NUMBER NOT NULL,
   CHARGE_RATE_CODE         NUMBER (6)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TIME_MAP CASCADE CONSTRAINTS;

CREATE TABLE TIME_MAP
(
   CALENDAR_ID           NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   CALENDAR_TYPE         VARCHAR2 (240 BYTE),
   CALENDAR_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   DESCRIPTION           VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE TIME_MODEL CASCADE CONSTRAINTS;

CREATE TABLE TIME_MODEL
(
   CALENDAR_ID           NUMBER (10),
   CALENDAR_NAME         VARCHAR2 (240 BYTE),
   MODEL_TYPE            VARCHAR2 (240 BYTE),
   DAY_IN                NUMBER,
   DAY_TYPE_NAME         VARCHAR2 (240 BYTE),
   DAY_TYPE_ID           NUMBER (10),
   DESCRIPTION           VARCHAR2 (720 BYTE),
   TIME_SLOT_ID          NUMBER (10),
   TIME_SLOT_NAME        VARCHAR2 (240 BYTE),
   FROM_IN               VARCHAR2 (5 BYTE),
   TO_IN                 VARCHAR2 (5 BYTE),
   TIME_TYPE_ID          NUMBER (10),
   TIME_TYPE_NAME        VARCHAR2 (240 BYTE),
   RESELLER_VERSION_ID   NUMBER (18)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE UNIT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE UNIT_TYPE
(
   TYPE_ID       NUMBER (6) NOT NULL,
   TYPE_NAME     VARCHAR2 (240 BYTE) NOT NULL,
   DESCRIPTION   VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE USAGE_ACTIVITY CASCADE CONSTRAINTS;

CREATE TABLE USAGE_ACTIVITY
(
   TRANS_ID              NUMBER (10) NOT NULL,
   UA_NAME               VARCHAR2 (240 BYTE) NOT NULL,
   UA_ID                 NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   PRIORITY              NUMBER (6),
   ZONE_GROUP_NAME       VARCHAR2 (240 BYTE),
   ZONE_GROUP_ID         NUMBER (10),
   UNIT_TYPE_NAME        VARCHAR2 (240 BYTE) NOT NULL,
   UNIT_TYPE_ID          NUMBER (6) NOT NULL,
   INITIAL_AUT_NAME      VARCHAR2 (240 BYTE) NOT NULL,
   INITIAL_AUT_ID        NUMBER (10) NOT NULL
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE USAGE_ACTIVITY_GROUP CASCADE CONSTRAINTS;

CREATE TABLE USAGE_ACTIVITY_GROUP
(
   UA_MAP_ID             NUMBER (10) NOT NULL,
   UA_GROUP_NAME         VARCHAR2 (240 BYTE) NOT NULL,
   UA_GROUP_ID           NUMBER (6) NOT NULL,
   UA_KEY                VARCHAR2 (240 BYTE),
   UA_ID                 NUMBER (10),
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE USAGE_PLAN CASCADE CONSTRAINTS;

CREATE TABLE USAGE_PLAN
(
   USAGE_PLAN_NAME       VARCHAR2 (240 BYTE) NOT NULL,
   USAGE_PLAN_ID         NUMBER (10) NOT NULL,
   OFFER_NAME            VARCHAR2 (240 BYTE) NOT NULL,
   OFFER_ID              NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   USAGE_ITEM_NAME       VARCHAR2 (240 BYTE) NOT NULL,
   USAGE_ITEM_ID         NUMBER (10) NOT NULL,
   ASSUME_CONSUMPTION    NUMBER (3) NOT NULL,
   INHIBIT_REFUND        CHAR (1 BYTE) NOT NULL,
   UA_NAME               VARCHAR2 (240 BYTE) NOT NULL,
   UA_ID                 NUMBER (10) NOT NULL,
   TARIFF_PLAN_NAME      VARCHAR2 (240 BYTE) NOT NULL,
   TARIFF_PLAN_ID        NUMBER (10) NOT NULL,
   DESCRIPTION           VARCHAR2 (720 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ZONE CASCADE CONSTRAINTS;

CREATE TABLE ZONE
(
   ZONE_ID          NUMBER (10) NOT NULL,
   ZONE_NAME        VARCHAR2 (25 BYTE) NOT NULL,
   PART_OF          VARCHAR2 (25 BYTE),
   TIME_ZONE_NAME   VARCHAR2 (240 BYTE),
   TIME_ZONE_ID     NUMBER (3),
   HIERARCHY_NAME   VARCHAR2 (240 BYTE),
   HIERARCHY_ID     NUMBER,
   TRANSLATION_ID   NUMBER (10) NOT NULL,
   GLT_NUMBER       VARCHAR2 (30 BYTE) NOT NULL
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE ZONE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE ZONE_GROUP
(
   GROUP_ID              NUMBER (10) NOT NULL,
   GROUP_NAME            VARCHAR2 (240 BYTE) NOT NULL,
   ZONE_A                VARCHAR2 (25 BYTE) NOT NULL,
   ZONE_B                VARCHAR2 (25 BYTE) NOT NULL,
   EXPRESSION_GROUP_ID   NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   PRIORITY              NUMBER (6) NOT NULL,
   HOME_OPPS_ID          NUMBER,
   HOME_OPPS_NAME        VARCHAR2 (240 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 80 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER RESELLER_VERSION_STATUS_AR
   AFTER UPDATE OF STATUS
   ON RESELLER_VERSION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   IF :NEW.STATUS = 2
   THEN
      --      :new.create_dt := SYSDATE;

      ELC_USER.CBS_OWNER_FILTER.LETS_GO (:NEW.RESELLER_VERSION_ID);
   END IF;
END;
/