DROP TABLE ELC_USER.PROMO_PLAN CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.PROMO_PLAN
(
  OFFER_ID             NUMBER(10)               NOT NULL,
  OFFER_NAME           VARCHAR2(240 BYTE)       NOT NULL,
  PROMO_PLAN_NAME      VARCHAR2(240 BYTE)       NOT NULL,
  PROMO_PLAN_ID        NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  BONUS_ITEM_NAME      VARCHAR2(240 BYTE),
  BONUS_ITEM_ID        NUMBER,
  DISCOUNT_ITEM_NAME   VARCHAR2(240 BYTE),
  DISCOUNT_ITEM_ID     NUMBER
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
