DROP TABLE ELC_USER.RUM_MAP CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.RUM_MAP
(
  TARIFF_PLAN_MAPPING_ID  NUMBER(10)            NOT NULL,
  RESELLER_VERSION_ID     NUMBER(18)            NOT NULL,
  TARIFF_PLAN_NAME        VARCHAR2(240 BYTE)    NOT NULL,
  TARIFF_PLAN_ID          NUMBER(10)            NOT NULL,
  TARIFF_SET_MEMBER_ID    NUMBER(10)            NOT NULL,
  TARIFF_SET_NAME         VARCHAR2(240 BYTE)    NOT NULL,
  TARIFF_SET_ID           NUMBER                NOT NULL,
  UNIT_TYPE_NAME          VARCHAR2(240 BYTE)    NOT NULL,
  UNIT_TYPE_ID            NUMBER(6)             NOT NULL,
  RUM_ID                  VARCHAR2(7 BYTE),
  CURRENCY_NAME           VARCHAR2(240 BYTE)    NOT NULL,
  CURRENCY_ID             NUMBER(6)             NOT NULL,
  TIME_TYPE_NAME          VARCHAR2(240 BYTE)    NOT NULL,
  TIME_TYPE_ID            NUMBER(10)            NOT NULL,
  TARIFF_MODEL_NAME       VARCHAR2(240 BYTE),
  TARIFF_MODEL_ID         NUMBER(10),
  IS_PRIMARY              NUMBER(1),
  RUM_TYPE                VARCHAR2(7 BYTE),
  CONSUME_FLAG            NUMBER,
  STEP                    NUMBER
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
