DROP TABLE ELC_USER.TIME_MODEL CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.TIME_MODEL
(
  CALENDAR_ID          NUMBER(10),
  CALENDAR_NAME        VARCHAR2(240 BYTE),
  MODEL_TYPE           VARCHAR2(240 BYTE),
  DAY_IN               NUMBER,
  DAY_TYPE_NAME        VARCHAR2(240 BYTE),
  DAY_TYPE_ID          NUMBER(10),
  DESCRIPTION          VARCHAR2(720 BYTE),
  TIME_SLOT_ID         NUMBER(10),
  TIME_SLOT_NAME       VARCHAR2(240 BYTE),
  FROM_IN              VARCHAR2(5 BYTE),
  TO_IN                VARCHAR2(5 BYTE),
  TIME_TYPE_ID         NUMBER(10),
  TIME_TYPE_NAME       VARCHAR2(240 BYTE),
  RESELLER_VERSION_ID  NUMBER(18)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
