DROP TABLE ELC_USER.USAGE_ACTIVITY CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.USAGE_ACTIVITY
(
  UA_ID                NUMBER(10)               NOT NULL,
  UA_NAME              VARCHAR2(240 BYTE)       NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  UNIT_TYPE_NAME       VARCHAR2(240 BYTE)       NOT NULL,
  UNIT_TYPE_ID         NUMBER(6)                NOT NULL,
  SUB_TYPE_NAME        VARCHAR2(240 BYTE),
  SUB_TYPE_ID          NUMBER(10),
  APP_NAME             VARCHAR2(240 BYTE),
  APP_ID               NUMBER(10),
  UA_INITIAL_NAME      VARCHAR2(240 BYTE),
  UA_INITIAL_ID        NUMBER(10),
  TAX_CLASS_NAME       VARCHAR2(240 BYTE),
  TAX_CLASS_ID         NUMBER(10),
  DESCRIPTION          VARCHAR2(720 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
