DROP TABLE ELC_USER.ZONE CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.ZONE
(
  ZONE_ID         NUMBER(10)                    NOT NULL,
  LI              VARCHAR2(16 BYTE)             NOT NULL,
  ZONE_NAME       VARCHAR2(25 BYTE)             NOT NULL,
  PART_OF         VARCHAR2(25 BYTE),
  TIME_ZONE_NAME  VARCHAR2(240 BYTE),
  TIME_ZONE_ID    NUMBER(3),
  HIERARCHY_NAME  VARCHAR2(240 BYTE),
  HIERARCHY_ID    NUMBER,
  TRANSLATION_ID  NUMBER(10)                    NOT NULL,
  GLT_NUMBER      VARCHAR2(30 BYTE)             NOT NULL
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
