DROP TABLE ELC_USER.ZONE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE ELC_USER.ZONE_GROUP
(
  GROUP_ID             NUMBER(10)               NOT NULL,
  GROUP_NAME           VARCHAR2(240 BYTE)       NOT NULL,
  ZONE_A               VARCHAR2(25 BYTE)        NOT NULL,
  ZONE_B               VARCHAR2(25 BYTE)        NOT NULL,
  EXPRESSION_GROUP_ID  NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  PRIORITY             NUMBER(6)                NOT NULL,
  HOME_OPPS_ID         NUMBER,
  HOME_OPPS_NAME       VARCHAR2(240 BYTE)
)
TABLESPACE ELC_USER
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
