DROP TABLE VNP_COMMON.ACCOUNT_VERSION_DEV CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_VERSION_DEV
(
  ACCOUNT_VERSION_ID  NUMBER(23)                NOT NULL,
  FROM_DATE           DATE                      NOT NULL,
  TO_DATE             DATE,
  SUBSCRIBER_ID       NUMBER(15),
  ACCOUNT_ID          NUMBER(15),
  MODIFIED_DATE       DATE,
  EFFECTIVE_DATE      DATE
)
TABLESPACE VNP_COMMON_ACC_VER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.IDX_AVD_ACCOUNT_ID ON VNP_COMMON.ACCOUNT_VERSION_DEV
(ACCOUNT_ID)
LOGGING
TABLESPACE VNP_COMMON_ACC_VER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_COMMON.IDX_AVD_SUBSCRIBER_ID ON VNP_COMMON.ACCOUNT_VERSION_DEV
(SUBSCRIBER_ID)
LOGGING
TABLESPACE VNP_COMMON_ACC_VER
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ACCOUNT_VERSION_DEV TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ACCOUNT_VERSION_DEV TO VNP_VIEW;
