DROP TABLE VNP_COMMON.ACCOUNT_DEV CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_DEV
(
  ACCOUNT_ID   NUMBER(15)                       NOT NULL,
  CURRENCY_ID  NUMBER(3)                        NOT NULL
)
TABLESPACE VNP_COMMON_ACCOUNT
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.IDX_AD_ACCOUNT_ID ON VNP_COMMON.ACCOUNT_DEV
(ACCOUNT_ID)
LOGGING
TABLESPACE VNP_COMMON_ACCOUNT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ACCOUNT_DEV TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ACCOUNT_DEV TO VNP_VIEW;
