DROP TABLE VNP_COMMON.ACCOUNT_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_OFFER_MAP
(
  ACCOUNT_ID            NUMBER                  NOT NULL,
  OFFER_ID              NUMBER                  NOT NULL,
  ACTIVE_DATE           DATE                    NOT NULL,
  IN_ACTIVE_DATE        DATE,
  OFFER_TYPE            NUMBER,
  C1_OFFER_INSTANCE_ID  NUMBER,
  MODIFIED_DATE         DATE                    DEFAULT current_date
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ACCOUNT_OFFER_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ACCOUNT_OFFER_MAP TO VNP_VIEW;
