DROP TABLE VNP_COMMON.ACCOUNT_SUBSCRIBERS_TMP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_SUBSCRIBERS_TMP
(
  STT               INTEGER,
  MA_TINH           NVARCHAR2(300),
  MA_KH_CHA         NVARCHAR2(300),
  MA_KH             NVARCHAR2(300),
  TEN_TT            NVARCHAR2(300),
  DIA_CHI_TT        NVARCHAR2(300),
  SO_DT_DD          VARCHAR2(300 BYTE),
  QUOC_TICH         NVARCHAR2(300),
  CO_QUAN           NVARCHAR2(300),
  LOAI_KH           NVARCHAR2(300),
  MA_CQ             NVARCHAR2(300),
  ACCT_OFFER_ID     VARCHAR2(300 BYTE),
  EMAIL             VARCHAR2(300 BYTE),
  MSISDN            VARCHAR2(300 BYTE),
  PRIMARY_OFFER_ID  INTEGER,
  TEN_TB            NVARCHAR2(300),
  DIA_CHI           NVARCHAR2(300),
  NGAY_LD           NVARCHAR2(300),
  SIM               VARCHAR2(20 BYTE),
  NGAY_SINH         VARCHAR2(20 BYTE),
  EMAIL_TB          VARCHAR2(300 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ACCOUNT_SUBSCRIBERS_TMP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ACCOUNT_SUBSCRIBERS_TMP TO VNP_VIEW;
