DROP TABLE VNP_COMMON.ACCOUNT_VERSION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ACCOUNT_VERSION
(
  ACCOUNT_VERSION_ID  NUMBER(23)                NOT NULL,
  FROM_DATE           DATE                      NOT NULL,
  TO_DATE             DATE,
  SUBSCRIBER_ID       NUMBER(15),
  ACCOUNT_ID          NUMBER(15),
  MODIFIED_DATE       DATE,
  EFFECTIVE_DATE      DATE
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER VNP_COMMON.ACCOUNT_VERSION_TRG
   BEFORE INSERT
   ON VNP_COMMON.ACCOUNT_VERSION
   REFERENCING NEW AS New OLD AS Old
   FOR EACH ROW
BEGIN
   -- For Toad:  Highlight column ACCOUNT_VERSION_ID
   :new.ACCOUNT_VERSION_ID := ACCOUNT_VERSION_SEQ.NEXTVAL;
END ACCOUNT_VERSION_TRG;
/
