DROP TABLE VNP_COMMON.ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLESPACE vnp_common_account
  DATAFILE '/cdr/u01/app/oracle/oradata/eonerate/vnp_common/vnp_common_account01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10 M MAXSIZE UNLIMITED;

CREATE TABLE VNP_COMMON.ACCOUNT
(
  ACCOUNT_ID     NUMBER(15)                     NOT NULL,
  CURRENCY_ID    NUMBER(3)                      NOT NULL,
  MODIFIED_DATE  DATE                           DEFAULT current_date
)
TABLESPACE VNP_COMMON_ACCOUNT
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.IDX_ACCOUNT_ID ON VNP_COMMON.ACCOUNT
(ACCOUNT_ID)
LOGGING
TABLESPACE VNP_COMMON_ACCOUNT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ACCOUNT TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ACCOUNT TO VNP_VIEW;
