/* Formatted on 17/11/2014 11:27:12 AM (QP5 v5.215.12089.38647) */
DROP TABLE VNP_COMMON.BALANCE_EI CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.BALANCE_EI
(
   BALANCE_EI_ID         NUMBER (10) NOT NULL,
   RESELLER_VERSION_ID   NUMBER (18) NOT NULL,
   OFFER_NAME            VARCHAR2 (240 BYTE) NOT NULL,
   OFFER_ID              NUMBER (10) NOT NULL,
   BALANCE_NAME          VARCHAR2 (240 BYTE) NOT NULL,
   BALANCE_ID            NUMBER (10) NOT NULL,
   UA_NAME               VARCHAR2 (240 BYTE),
   UA_ID                 NUMBER (10),
   UA_GROUP_NAME         VARCHAR2 (240 BYTE),
   UA_GROUP_ID           NUMBER (6),
   RC_TERM_NAME          VARCHAR2 (240 BYTE),
   RC_TERM_ID            NUMBER (10),
   NRC_TERM_NAME         VARCHAR2 (240 BYTE),
   NRC_TERM_ID           NUMBER (10),
   EI_FLAG               CHAR (4 BYTE),
   TIME_TYPE_NAME        VARCHAR2 (240 BYTE),
   TIME_TYPE_ID          NUMBER (10)
)
TABLESPACE vnp_common;