ALTER TABLE VNP_COMMON.CALLING_CIRCLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE VNP_COMMON.CALLING_CIRCLE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CALLING_CIRCLE
(
  CALLING_CIRCLE_ID    NUMBER(15)               NOT NULL,
  CALLING_CIRCLE_NAME  VARCHAR2(100 BYTE),
  STATUS_ID            NUMBER(3),
  MAX_SIZE             NUMBER(5),
  CREATED_DATE         DATE                     DEFAULT CURRENT_DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_COMMON.CALLING_CIRCLE_PK ON VNP_COMMON.CALLING_CIRCLE
(CALLING_CIRCLE_ID)
LOGGING
TABLESPACE VNP_COMMON
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE VNP_COMMON.CALLING_CIRCLE ADD (
  CONSTRAINT CALLING_CIRCLE_PK
  PRIMARY KEY
  (CALLING_CIRCLE_ID)
  USING INDEX VNP_COMMON.CALLING_CIRCLE_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.CALLING_CIRCLE TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.CALLING_CIRCLE TO VNP_VIEW;
