DROP TABLE VNP_COMMON.CALLING_CIRCLE_MEMBER_TMP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CALLING_CIRCLE_MEMBER_TMP
(
  CALLING_CIRCLE_ID       NUMBER(15)            NOT NULL,
  MSISDN                  NUMBER(20)            NOT NULL,
  MEMBER_TYPE             NUMBER(3),
  STATUS_ID               NUMBER(3)             NOT NULL,
  MODIFIED_DATE           DATE                  NOT NULL,
  CREATED_DATE            DATE                  DEFAULT CURRENT_DATE,
  C1_SUBSCRIBER_NO        NUMBER(20)            NOT NULL,
  C1_SUBSCRIBER_NO_RESET  NUMBER(20)            NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.CALLING_CIRCLE_MEMBER_TMP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.CALLING_CIRCLE_MEMBER_TMP TO VNP_VIEW;
