/* Formatted on 16/11/2014 10:36:27 AM (QP5 v5.215.12089.38647) */
--------------------------------------------------------
--  File created - Friday-November-14-2014
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CDR_MAPPING_ERROR_CODE
--------------------------------------------------------

CREATE TABLE "VNP_COMMON"."CDR_MAPPING_ERROR_CODE"
(
   "ERROR_CODE"    VARCHAR2 (7 BYTE),
   "DESCRIPTION"   VARCHAR2 (511 BYTE)
)
TABLESPACE "VNP_COMMON";

ALTER TABLE "VNP_COMMON"."CDR_MAPPING_ERROR_CODE" MODIFY ("ERROR_CODE" NOT NULL ENABLE);

COMMENT ON COLUMN "VNP_COMMON"."CDR_MAPPING_ERROR_CODE"."ERROR_CODE" IS
   'Error code for mapping CDR';

COMMENT ON COLUMN "VNP_COMMON"."CDR_MAPPING_ERROR_CODE"."DESCRIPTION" IS
   'Descriptiption eror code';
REM INSERTING into VNP_COMMON.CDR_MAPPING_ERROR_CODE
SET DEFINE OFF;

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100001', 'DURATION NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100002', 'TOTAL_USAGE NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100003', 'B_NUMBER NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100004', 'LOCATION_NO NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100005', 'CHARGE_FEE NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100006', 'CHARGE_FEE_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100007', 'MSC_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100008', 'LAC NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100009', 'CELL_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100010', 'CDR_SEQUENCE_NUMBER NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100011', 'DIAL_DIGIT NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100012', 'UNIT_TYPE_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100013', 'AUT_FINAL_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100014', 'USAGE_OFFER_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100015', 'USAGE_PLAN_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100016', 'PRIMARY_OFFER_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100017', 'DISCOUNT_ITEM NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100018', 'TARIFF_PLAN_ID NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100019', 'BALANCE_CHANGE NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100020', 'DURATION_OCS NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110000', 'A_NUMBER OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110001', 'DURATION OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110002', 'TOTAL_USAGE OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110003', 'B_NUMBER OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110004', 'LOCATION_NO OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110005', 'CHARGE_FEE OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110006', 'CHARGE_FEE_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110007', 'MSC_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110008', 'LAC OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110009', 'CELL_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110010', 'CDR_SEQUENCE_NUMBER OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110011', 'DIAL_DIGIT OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110012', 'UNIT_TYPE_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110013', 'AUT_FINAL_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110014', 'USAGE_OFFER_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110015', 'USAGE_PLAN_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110016', 'PRIMARY_OFFER_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110017', 'DISCOUNT_ITEM OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110018', 'TARIFF_PLAN_ID OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110019', 'BALANCE_CHANGE OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110020', 'B_ZONE_OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('110021', 'NW_GROUP OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120000', 'CDR_START_TIME WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120001', 'DURATION WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120002', 'TOTAL_DOUBLE WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120003', 'TIME1_FIRST_TARIFF_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120004', 'TIME1_SECOND_TARIFF_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120005', 'TIME1_THIRD_TARIFF_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120006', 'TIME1_FOURTH_TARIFF_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120007', 'TIME1_FIFTH_TARIFF_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120008', 'TIME1_FIRST_TARIFF_CHARGE WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120009', 'CDR_SEQUENCE_NUMBER WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120010', 'USAGE_UNIT_TYPE WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120011', 'AUT_FINAL WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120012', 'USAGE_OFFER_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120013', 'USAGE_PLAN_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120014', 'PRIMARY_OFFER_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120015', 'DISCOUNT_ITEM_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('120016', 'TARIFF_PLAN_ID WRONG FORMAT');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('210020', 'ENRICH_B_ZONE OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('210021', 'ENRICH_NW_GROUP OVERLOAD');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('100000', 'A_NUMBER NULL');

INSERT INTO VNP_COMMON.CDR_MAPPING_ERROR_CODE (ERROR_CODE, DESCRIPTION)
     VALUES ('0', 'SUCCESS');

--------------------------------------------------------
--  Constraints for Table CDR_MAPPING_ERROR_CODE
--------------------------------------------------------