DROP TABLE VNP_COMMON.CHANGE_FLAG CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CHANGE_FLAG
(
  IS_CHANGING  NUMBER(1)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.CHANGE_FLAG TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.CHANGE_FLAG TO VNP_VIEW;
