DROP TABLE VNP_COMMON.CURRENCY_TYPE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CURRENCY_TYPE
(
  CURRENCY_CODE    NUMBER(6)                    NOT NULL,
  CURRENCY_NAME    VARCHAR2(720 BYTE)           NOT NULL,
  TYPE_NAME        VARCHAR2(720 BYTE)           NOT NULL,
  TYPE_ID          CHAR(3 BYTE)                 NOT NULL,
  ACTIVE_DATE      DATE                         NOT NULL,
  INACTIVE_DATE    DATE,
  ROUNDING_FACTOR  NUMBER(6)                    NOT NULL,
  ISO_CODE         VARCHAR2(12 BYTE),
  ISO_NUMBER       NUMBER(3),
  DESCRIPTION      VARCHAR2(2160 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
