DROP TABLE VNP_COMMON.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.CUSTOMER
(
  CUSTOMER_ID         NUMBER(15)                NOT NULL,
  CUSTOMER_PARENT_ID  NUMBER(15)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.CUSTOMER TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.CUSTOMER TO VNP_VIEW;
