DROP TABLE VNP_COMMON.NW_ZONE_MAP_TEST CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.NW_ZONE_MAP_TEST
(
  CODE        VARCHAR2(31 BYTE),
  ZONE        VARCHAR2(63 BYTE),
  NW_GROUP    VARCHAR2(7 BYTE),
  PAYMENT_ID  NUMBER(6),
  SHORT_CODE  VARCHAR2(63 BYTE),
  ZONE_GROUP  VARCHAR2(7 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
