DROP TABLE VNP_COMMON.NW_ZONE_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.NW_ZONE_MAP
(
  CODE        VARCHAR2(31 BYTE),
  ZONE        VARCHAR2(63 BYTE),
  NW_GROUP    VARCHAR2(7 BYTE),
  PAYMENT_ID  NUMBER(6),
  SHORT_CODE  VARCHAR2(63 BYTE),
  ZONE_GROUP  VARCHAR2(7 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON VNP_COMMON.NW_ZONE_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.NW_ZONE_MAP TO VNP_VIEW;
