DROP TABLE VNP_COMMON.OFFER_BALANCE_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.OFFER_BALANCE_MAP
(
  BALANCE_NAME               VARCHAR2(720 BYTE) NOT NULL,
  BALANCE_ID                 NUMBER(10)         NOT NULL,
  OFFER_NAME                 VARCHAR2(720 BYTE) NOT NULL,
  OFFER_ID                   NUMBER(10)         NOT NULL,
  RESELLER_VERSION_ID        NUMBER(18)         NOT NULL,
  BALANCE_ORDER              NUMBER(6)          NOT NULL,
  IS_SHADOW                  NUMBER,
  IS_CORE                    NUMBER(1)          NOT NULL,
  EXPIRATION_DATE            DATE,
  MIN_BALANCE                NUMBER(22,8),
  MAX_BALANCE                NUMBER(22,8),
  EXPIRATION_OPTION          VARCHAR2(720 BYTE),
  DEFAULT_EXPIRATION_OFFSET  NUMBER(18)         NOT NULL,
  IS_SHARED                  NUMBER(1)          NOT NULL,
  DEFAULT_LIMIT_TYPE         VARCHAR2(720 BYTE),
  DEFAULT_LIMIT_VALUE        NUMBER(22,8),
  DEFAULT_LIMIT_PERIOD       VARCHAR2(720 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
