DROP TABLE VNP_COMMON.ORP_TRANSFORMATION_LOG CASCADE CONSTRAINTS;

CREATE TABLESPACE vnp_common_ORP_TRANSFORMATION
  DATAFILE '/cdr/u01/app/oracle/oradata/eonerate/vnp_common/ORP_TRANSFORMATION01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10 M MAXSIZE UNLIMITED;

CREATE TABLE VNP_COMMON.ORP_TRANSFORMATION_LOG
(
  INPUT_FILE_NAME           VARCHAR2(255 BYTE),
  OUTPUT_FILE_NAME          VARCHAR2(255 BYTE),
  NUMBER_OF_VALID_RECORD    NUMBER(12),
  NUMBER_OF_INVALID_RECORD  NUMBER(12),
  RESERVE_1                 VARCHAR2(255 BYTE),
  RESERVE_2                 NUMBER(12),
  START_TIME_PROCESSED      DATE,
  END_TIME_PROCESSED        DATE,
  ERROR_CODE                VARCHAR2(10 BYTE),
  ERROR_DESCRIPTION         VARCHAR2(4000 BYTE)
)
TABLESPACE vnp_common_ORP_TRANSFORMATION
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ORP_TRANSFORMATION_LOG TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ORP_TRANSFORMATION_LOG TO VNP_VIEW;
