DROP TABLE VNP_COMMON.ORP_SFTP_FILE_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ORP_SFTP_FILE_HISTORY
(
  SFTP_FILE      VARCHAR2(255 BYTE),
  SLU            VARCHAR2(63 BYTE),
  SEQ            NUMBER(11),
  FILE_SIZE      NUMBER(11),
  STATUS         NUMBER(1),
  RETRY          NUMBER(1),
  NOTE           VARCHAR2(1023 BYTE),
  CREATED_TIME   DATE,
  MODIFIED_TIME  DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ORP_SFTP_FILE_HISTORY TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ORP_SFTP_FILE_HISTORY TO VNP_VIEW;
