DROP TABLE VNP_COMMON.ORP_OCG_TRANSFORMATION CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ORP_OCG_TRANSFORMATION
(
  CODE          NUMBER(15),
  RESERVE_1     VARCHAR2(50 BYTE),
  DIALED_DIGIT  VARCHAR2(30 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ORP_OCG_TRANSFORMATION TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ORP_OCG_TRANSFORMATION TO VNP_VIEW;
