DROP TABLE VNP_COMMON.ORP_NORMALISATION_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ORP_NORMALISATION_MAP
(
  MAP_GROUP      VARCHAR2(15 BYTE)              DEFAULT NULL,
  NUMBER_MATCH   VARCHAR2(32 BYTE)              DEFAULT NULL,
  REMOVE_PREFIX  VARCHAR2(32 BYTE)              DEFAULT NULL,
  NEW_PREFIX     VARCHAR2(32 BYTE)              DEFAULT NULL,
  RANK           NUMBER(5)                      DEFAULT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.ORP_NORMALISATION_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.ORP_NORMALISATION_MAP TO VNP_VIEW;
