DROP TABLE VNP_COMMON.PRICE_RUM_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PRICE_RUM_MAP
(
  PRICE_GROUP   VARCHAR2(24 BYTE)               DEFAULT NULL,
  PRICE_MODEL   VARCHAR2(24 BYTE)               DEFAULT NULL,
  RUM           VARCHAR2(24 BYTE)               DEFAULT NULL,
  "RESOURCE"    VARCHAR2(24 BYTE)               DEFAULT NULL,
  RESOURCE_ID   NUMBER(11)                      DEFAULT NULL,
  RUM_TYPE      VARCHAR2(24 BYTE)               DEFAULT NULL,
  CONSUME_FLAG  NUMBER(11)                      DEFAULT NULL,
  STEP          NUMBER(11)                      DEFAULT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.PRICE_RUM_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.PRICE_RUM_MAP TO VNP_VIEW;
