DROP TABLE VNP_COMMON.PRODUCT_SETTING CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PRODUCT_SETTING
(
  IS_INTERNAL  NUMBER(1),
  RC           NUMBER(15,3),
  NRC          NUMBER(15,3),
  VAT_RATE     NUMBER(15,3),
  UNBILL       CHAR(1 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.PRODUCT_SETTING TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.PRODUCT_SETTING TO VNP_VIEW;
