DROP TABLE VNP_COMMON.PROMO_PLAN CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.PROMO_PLAN
(
  OFFER_ID             NUMBER(10)               NOT NULL,
  OFFER_NAME           VARCHAR2(720 BYTE)       NOT NULL,
  PROMO_PLAN_NAME      VARCHAR2(720 BYTE)       NOT NULL,
  PROMO_PLAN_ID        NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  BONUS_ITEM_NAME      VARCHAR2(720 BYTE),
  BONUS_ITEM_ID        NUMBER,
  DISCOUNT_ITEM_NAME   VARCHAR2(720 BYTE),
  DISCOUNT_ITEM_ID     NUMBER
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
