DROP TABLE VNP_COMMON.RC_RATE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.RC_RATE
(
  RC_RATE_ID           NUMBER(10),
  RESELLER_VERSION_ID  NUMBER(18),
  SERVICE_VERSION_ID   NUMBER(18),
  RC_TERM_NAME         VARCHAR2(240 BYTE),
  RC_TERM_ID           NUMBER(10),
  OFFER_ID             NUMBER(10),
  PERIOD_FREQUENCE     VARCHAR2(240 BYTE),
  CURRENCY_NAME        VARCHAR2(240 BYTE),
  CURRENCY_CODE        NUMBER(6),
  RATE                 NUMBER(18)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.RC_RATE TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.RC_RATE TO VNP_VIEW;
