DROP TABLE VNP_COMMON.SUBS_BU_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_BU_HISTORY
(
  SUBSCRIBER_NO     VARCHAR2(15 BYTE),
  CHANGE_DATE_TIME  DATE,
  CHANGE_CODE       VARCHAR2(7 BYTE),
  CHANGE_BU         VARCHAR2(7 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.SUBSCRIBER_NO_IDX ON VNP_COMMON.SUBS_BU_HISTORY
(SUBSCRIBER_NO)
LOGGING
TABLESPACE VNP_COMMON
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_COMMON.SUB_BU_CHANGE_IDX ON VNP_COMMON.SUBS_BU_HISTORY
(CHANGE_DATE_TIME)
NOLOGGING
TABLESPACE VNP_COMMON
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBS_BU_HISTORY TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBS_BU_HISTORY TO VNP_VIEW;
