-- ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP
 -- DROP PRIMARY KEY CASCADE;

DROP TABLE VNP_COMMON.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

DROP TABLE VNP_COMMON.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_OFFER_MAP
(
  SUBSCRIBER_ID      NUMBER(15)                 NOT NULL,
  FROM_DATE          DATE                       NOT NULL,
  TO_DATE            DATE,
  PRODUCT_OFFER_ID   NUMBER(10)                 NOT NULL,
  SUBS_OFFER_MAP_ID  NUMBER(23)                 NOT NULL,
  MODIFIED_DATE      DATE
)
TABLESPACE VNP_COMMON_SOM;


CREATE INDEX VNP_COMMON.IDX_SOM_PRODUCT_OFFER_ID ON VNP_COMMON.SUBS_OFFER_MAP
(PRODUCT_OFFER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX VNP_COMMON.IDX_SOM_SUBSCRIBER_ID ON VNP_COMMON.SUBS_OFFER_MAP
(SUBSCRIBER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


-- CREATE OR REPLACE TRIGGER VNP_COMMON.SUBS_OFFER_MAP_TRG
   -- BEFORE INSERT
   -- ON VNP_COMMON.SUBS_OFFER_MAP
   -- REFERENCING NEW AS New OLD AS Old
   -- FOR EACH ROW
-- BEGIN
   -- -- For Toad:  Highlight column SUBS_OFFER_MAP_ID
   -- :new.SUBS_OFFER_MAP_ID := SUBS_OFFER_MAP_SEQ.NEXTVAL;
-- END SUBS_OFFER_MAP_TRG;
/


-- ALTER TABLE VNP_COMMON.SUBS_OFFER_MAP ADD (
  -- CONSTRAINT SUBS_OFFER_MAP_PK
  -- PRIMARY KEY
  -- (SUBS_OFFER_MAP_ID)
  -- USING INDEX VNP_COMMON.SUBS_OFFER_MAP_PK
  -- ENABLE VALIDATE);
