DROP TABLE VNP_COMMON.SUBSCRIBER CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER
(
  SUBSCRIBER_ID   NUMBER(15)                    NOT NULL,
  SUBSCRIBER_NO   VARCHAR2(31 BYTE)             NOT NULL,
  RATING_TYPE_ID  NUMBER(3)                     NOT NULL
)
TABLESPACE PCAT_FILTER
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


-- CREATE OR REPLACE TRIGGER VNP_COMMON.SUBSCRIBER_TRG
-- BEFORE INSERT
-- ON VNP_COMMON.SUBSCRIBER
-- REFERENCING NEW AS NEW OLD AS OLD
-- FOR EACH ROW
-- DISABLE
-- BEGIN
   -- -- For Toad:  Highlight column SUBSCRIBER_ID
   -- :new.SUBSCRIBER_ID := SUBSCRIBER_SEQ.NEXTVAL;
-- END SUBSCRIBER_TRG;
-- /
