DROP TABLE VNP_COMMON.SUBS_OFFER_MAP CASCADE CONSTRAINTS;

CREATE TABLESPACE vnp_common_som
  DATAFILE '/cdr/u01/app/oracle/oradata/eonerate/vnp_common/subs_offer_map01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10 M MAXSIZE UNLIMITED;

CREATE TABLE VNP_COMMON.SUBS_OFFER_MAP
(
  SUBSCRIBER_ID         NUMBER(15)              NOT NULL,
  FROM_DATE             DATE                    NOT NULL,
  TO_DATE               DATE,
  PRODUCT_OFFER_ID      NUMBER(10)              NOT NULL,
  SUBS_OFFER_MAP_ID     NUMBER(23)              NOT NULL,
  MODIFIED_DATE         DATE,
  C1_OFFER_INSTANCE_ID  NUMBER
)
TABLESPACE VNP_COMMON_SOM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.IDX_SOM_PRODUCT_OFFER_ID ON VNP_COMMON.SUBS_OFFER_MAP
(PRODUCT_OFFER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_COMMON.IDX_SOM_SUBSCRIBER_ID ON VNP_COMMON.SUBS_OFFER_MAP
(SUBSCRIBER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBS_OFFER_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBS_OFFER_MAP TO VNP_VIEW;
