DROP TABLE VNP_COMMON.SUBS_OFFER_MAP_DEV CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_OFFER_MAP_DEV
(
  SUBSCRIBER_ID      NUMBER(15)                 NOT NULL,
  FROM_DATE          DATE                       NOT NULL,
  TO_DATE            DATE,
  PRODUCT_OFFER_ID   NUMBER(10)                 NOT NULL,
  SUBS_OFFER_MAP_ID  NUMBER(23),
  MODIFIED_DATE      DATE
)
TABLESPACE VNP_COMMON_SOM
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_COMMON.IDX_SOMD_PRODUCT_OFFER_ID ON VNP_COMMON.SUBS_OFFER_MAP_DEV
(PRODUCT_OFFER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_COMMON.IDX_SOMD_SUBSCRIBER_ID ON VNP_COMMON.SUBS_OFFER_MAP_DEV
(SUBSCRIBER_ID)
LOGGING
TABLESPACE VNP_COMMON_SOM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBS_OFFER_MAP_DEV TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBS_OFFER_MAP_DEV TO VNP_VIEW;
