DROP TABLE VNP_COMMON.SUBSCRIBER_STATUS CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_STATUS
(
  STATUS_ID    NUMBER(3)                        NOT NULL,
  STATUS_NAME  VARCHAR2(63 BYTE)                NOT NULL,
  NRC          NUMBER(15,3),
  CURRENCY_ID  NUMBER(3)                        NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBSCRIBER_STATUS TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBSCRIBER_STATUS TO VNP_VIEW;
