DROP TABLE VNP_COMMON.SUBS_BU_HISTORY_OLD CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_BU_HISTORY_OLD
(
  SUBSCRIBER_NO     VARCHAR2(15 BYTE),
  CHANGE_DATE_TIME  DATE,
  CHANGE_CODE       VARCHAR2(7 BYTE),
  CHANGE_BU         VARCHAR2(7 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
