DROP TABLE VNP_COMMON.SUBSCRIBER_OFFERS_C1_TMP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_OFFERS_C1_TMP
(
  MSISDN                NVARCHAR2(20),
  SUBS_ID               NVARCHAR2(20),
  OFFER_ID              VARCHAR2(20 BYTE),
  ACCOUNT               VARCHAR2(20 BYTE),
  ACTIVE_DATE           DATE,
  INACTIVE_DATE         DATE,
  OFFER_TYPE            VARCHAR2(10 BYTE),
  C1_OFFER_INSTANCE_ID  VARCHAR2(20 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBSCRIBER_OFFERS_C1_TMP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBSCRIBER_OFFERS_C1_TMP TO VNP_VIEW;
