DROP TABLE VNP_COMMON.SUBSCRIBER_TMP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBSCRIBER_TMP
(
  SUBSCRIBER_ID           NUMBER(15)            NOT NULL,
  SUBSCRIBER_NO           VARCHAR2(31 BYTE)     NOT NULL,
  RATING_TYPE_ID          NUMBER(3)             NOT NULL,
  DATA_PART               NUMBER(2)             NOT NULL,
  C1_SUBSCRIBER_NO        NUMBER(15),
  C1_SUBSCRIBER_NO_RESET  NUMBER
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBSCRIBER_TMP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBSCRIBER_TMP TO VNP_VIEW;
