DROP TABLE VNP_COMMON.SUBS_STATUS_MAP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.SUBS_STATUS_MAP
(
  SUBSCRIBER_ID  NUMBER(15)                     NOT NULL,
  STATUS_ID      NUMBER(3)                      NOT NULL,
  START_DATE     DATE                           NOT NULL,
  END_DATE       DATE,
  MODIFIED_DATE  DATE                           DEFAULT CURRENT_DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_COMMON.SUBS_STATUS_MAP TO VNP_DATA;

GRANT SELECT ON VNP_COMMON.SUBS_STATUS_MAP TO VNP_VIEW;
