DROP TABLE VNP_COMMON.TIME_MODEL CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.TIME_MODEL
(
  CALENDAR_ID          NUMBER(10),
  CALENDAR_NAME        VARCHAR2(720 BYTE),
  MODEL_TYPE           VARCHAR2(720 BYTE),
  DAY_IN               NUMBER,
  DAY_TYPE_NAME        VARCHAR2(720 BYTE),
  DAY_TYPE_ID          NUMBER(10),
  DESCRIPTION          VARCHAR2(2160 BYTE),
  TIME_SLOT_ID         NUMBER(10),
  TIME_SLOT_NAME       VARCHAR2(720 BYTE),
  FROM_IN              VARCHAR2(15 BYTE),
  TO_IN                VARCHAR2(15 BYTE),
  TIME_TYPE_ID         NUMBER(10),
  TIME_TYPE_NAME       VARCHAR2(720 BYTE),
  RESELLER_VERSION_ID  NUMBER(18)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
