DROP TABLE VNP_COMMON.UNIT_PRICE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.UNIT_PRICE
(
  BALANCE_ID  NUMBER(7)                         NOT NULL,
  TIER1       NUMBER(7),
  PRICE1      NUMBER(15,2),
  TIER2       NUMBER(7),
  PRICE2      NUMBER(15,2)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON VNP_COMMON.UNIT_PRICE TO VNP_DATA;
