DROP TABLE VNP_COMMON.USAGE_ACTIVITY_TRANS CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.USAGE_ACTIVITY_TRANS
(
  AUT_TRANS_ID                NUMBER(10)        NOT NULL,
  UA_NAME                     VARCHAR2(720 BYTE) NOT NULL,
  UA_ID                       NUMBER(10)        NOT NULL,
  RESELLER_VERSION_ID         NUMBER(18)        NOT NULL,
  UNIT_TYPE_NAME              VARCHAR2(720 BYTE) NOT NULL,
  UNIT_TYPE_ID                NUMBER(6)         NOT NULL,
  UA_INITIAL_NAME             VARCHAR2(720 BYTE) NOT NULL,
  UA_INITIAL_ID               NUMBER(10)        NOT NULL,
  PRIORITY                    NUMBER(6),
  ACCOUNT_GROUP_NAME          VARCHAR2(720 BYTE),
  ACCOUNT_GROUP_ID            NUMBER(10),
  SUBS_GROUP_NAME             VARCHAR2(720 BYTE),
  SUBS_GROUP_ID               NUMBER(10),
  MARKET_GROUP_NAME           VARCHAR2(720 BYTE),
  MARKET_GROUP_ID             NUMBER(10),
  ZONE_GROUP_NAME             VARCHAR2(720 BYTE),
  ZONE_GROUP_ID               NUMBER(10),
  ACCESS_METHOD_GROUP_NAME    VARCHAR2(720 BYTE),
  ACCESS_METHOD_GROUP_ID      NUMBER(10),
  SPECIAL_FEATURE_GROUP_NAME  VARCHAR2(720 BYTE),
  SPECIAL_FEATURE_GROUP_ID    NUMBER(10),
  OFFLINE_GROUP_NAME          VARCHAR2(720 BYTE),
  OFFLINE_GROUP_ID            NUMBER(10)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
