DROP TABLE VNP_COMMON.USER_ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.USER_ACCOUNT
(
  USERNAME      VARCHAR2(20 BYTE)               NOT NULL,
  PASSWORD      VARCHAR2(255 BYTE)              NOT NULL,
  ROLE          NUMBER(1),
  CREATED_BY    VARCHAR2(20 BYTE),
  UPDATED_TIME  DATE
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
