DROP TABLE VNP_COMMON.ZONE_GROUP CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ZONE_GROUP
(
  GROUP_ID             NUMBER(10)               NOT NULL,
  GROUP_NAME           VARCHAR2(720 BYTE)       NOT NULL,
  ZONE_A               VARCHAR2(75 BYTE)        NOT NULL,
  ZONE_B               VARCHAR2(75 BYTE)        NOT NULL,
  EXPRESSION_GROUP_ID  NUMBER(10)               NOT NULL,
  RESELLER_VERSION_ID  NUMBER(18)               NOT NULL,
  PRIORITY             NUMBER(6)                NOT NULL,
  HOME_OPPS_ID         NUMBER,
  HOME_OPPS_NAME       VARCHAR2(720 BYTE)
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
