DROP TABLE VNP_COMMON.ZONE CASCADE CONSTRAINTS;

CREATE TABLE VNP_COMMON.ZONE
(
  ZONE_ID         NUMBER(10)                    NOT NULL,
  LI              VARCHAR2(48 BYTE)             NOT NULL,
  ZONE_NAME       VARCHAR2(75 BYTE)             NOT NULL,
  PART_OF         VARCHAR2(75 BYTE),
  TIME_ZONE_NAME  VARCHAR2(720 BYTE),
  TIME_ZONE_ID    NUMBER(3),
  HIERARCHY_NAME  VARCHAR2(720 BYTE),
  HIERARCHY_ID    NUMBER,
  TRANSLATION_ID  NUMBER(10)                    NOT NULL,
  GLT_NUMBER      VARCHAR2(90 BYTE)             NOT NULL
)
TABLESPACE VNP_COMMON
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
