DROP TABLE VNP_DATA.AGGREGATED_CDR CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.AGGREGATED_CDR
(
  A_NUMBER             VARCHAR2(31 BYTE),
  CDR_TYPE             NUMBER(1),
  TOTAL_CDR            NUMBER(11),
  BILL_MONTH           DATE,
  TOTAL_USAGE          NUMBER(11)               DEFAULT 0,
  SERVICE_FEE          NUMBER(15,3)             DEFAULT 0,
  CHARGE_FEE           NUMBER(15,3)             DEFAULT 0,
  OFFER_COST           NUMBER(15,3)             DEFAULT 0,
  OFFER_FREE_BLOCK     NUMBER(21)               DEFAULT 0,
  INTERNAL_COST        NUMBER(15,3)             DEFAULT 0,
  INTERNAL_FREE_BLOCK  NUMBER(11)               DEFAULT 0,
  PAYMENT_ID           NUMBER(4)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_DATA.AGGREGATED_CDR_BILL_MONTH ON VNP_DATA.AGGREGATED_CDR
(BILL_MONTH)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_DATA.AGGREGATED_USAGE_A_NUMBER ON VNP_DATA.AGGREGATED_CDR
(A_NUMBER)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_DATA.AGGREGATED_USAGE_CDR_TYPE ON VNP_DATA.AGGREGATED_CDR
(CDR_TYPE)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX VNP_DATA.AGGR_USG_PAYMENT_ITEM_ID ON VNP_DATA.AGGREGATED_CDR
(PAYMENT_ID)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.AGGREGATED_CDR TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.AGGREGATED_CDR TO VNP_VIEW;
