DROP TABLE VNP_DATA.BALANCE_COUNTER CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.BALANCE_COUNTER
(
  BAL_GROUP_ID  NUMBER(15),
  COUNTER_ID    NUMBER(11),
  RECORD_ID     NUMBER(11),
  VALID_FROM    NUMBER(11),
  VALID_TO      NUMBER(11),
  CURRENT_BAL   NUMBER(15,3)
)
TABLESPACE VNP_DATA_BALANCE_COUNTER;


CREATE INDEX VNP_DATA.IDX_BC_GROUP1 ON VNP_DATA.BALANCE_COUNTER
(BAL_GROUP_ID, COUNTER_ID, VALID_FROM)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.BALANCE_COUNTER TO VNP_COMMON;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.BALANCE_COUNTER TO VNP_COMMON_2;
