DROP TABLE VNP_DATA.C1RT_ORP_MONITOR CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.C1RT_ORP_MONITOR
(
  FILE_NAME        VARCHAR2(200 BYTE)           NOT NULL,
  FILE_CLASS       NUMBER,
  TOTAL            NUMBER                       DEFAULT 0                     NOT NULL,
  INVALID          NUMBER                       DEFAULT 0,
  RATE_ERROR       NUMBER                       DEFAULT 0,
  PROCESSING_DATE  DATE,
  CREATED_DATE     DATE                         DEFAULT CURRENT_DATE          NOT NULL
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_DATA.C1RT_ORP_MONITOR_UK1 ON VNP_DATA.C1RT_ORP_MONITOR
(FILE_NAME)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE VNP_DATA.C1RT_ORP_MONITOR ADD (
  CONSTRAINT C1RT_ORP_MONITOR_UK1
  UNIQUE (FILE_NAME)
  USING INDEX VNP_DATA.C1RT_ORP_MONITOR_UK1
  ENABLE VALIDATE);
