DROP TABLE VNP_DATA.C1RT_ORP_DAILY_DETAIL_REPORT CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.C1RT_ORP_DAILY_DETAIL_REPORT
(
  FILE_ID          VARCHAR2(50 BYTE)            NOT NULL,
  FILE_NAME        VARCHAR2(200 BYTE)           NOT NULL,
  TOTAL_RECORDS    NUMBER,
  INVALID_RECORDS  NUMBER,
  ERROR_RECORDS    NUMBER,
  PROCESSING_DATE  DATE                         NOT NULL,
  CREATED_DATE     DATE                         DEFAULT CURRENT_DATE          NOT NULL
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_DATA.C1RT_ORP_DAILY_DETAIL_REP_UK1 ON VNP_DATA.C1RT_ORP_DAILY_DETAIL_REPORT
(FILE_ID, FILE_NAME)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE VNP_DATA.C1RT_ORP_DAILY_DETAIL_REPORT ADD (
  CONSTRAINT C1RT_ORP_DAILY_DETAIL_REP_UK1
  UNIQUE (FILE_ID, FILE_NAME)
  USING INDEX VNP_DATA.C1RT_ORP_DAILY_DETAIL_REP_UK1
  ENABLE VALIDATE);
