DROP TABLE VNP_DATA.C1RT_ORP_DAILY_SUMMARY_REPORT CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.C1RT_ORP_DAILY_SUMMARY_REPORT
(
  TOTAL_RECEIVED_FILES       NUMBER             NOT NULL,
  TOTAL_RATED_FILES          NUMBER             NOT NULL,
  FILES_WITH_NO_CDR          NUMBER,
  TOTAL_RECORDS              NUMBER,
  TOTAL_RATED_RECORDS        NUMBER,
  TOTAL_INVALID_RECORDS      NUMBER,
  TOTAL_ERROR_RATED_RECORDS  NUMBER,
  REPORT_DATE                DATE               NOT NULL,
  CREATED_DATE               DATE               DEFAULT CURRENT_DATE          NOT NULL
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VNP_DATA.C1RT_ORP_DAILY_SUMMARY_RE_UK1 ON VNP_DATA.C1RT_ORP_DAILY_SUMMARY_REPORT
(REPORT_DATE)
LOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE VNP_DATA.C1RT_ORP_DAILY_SUMMARY_REPORT ADD (
  CONSTRAINT C1RT_ORP_DAILY_SUMMARY_RE_UK1
  UNIQUE (REPORT_DATE)
  USING INDEX VNP_DATA.C1RT_ORP_DAILY_SUMMARY_RE_UK1
  ENABLE VALIDATE);
