DROP TABLE VNP_DATA.CDR_LOG_PROCESS_HIS CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.CDR_LOG_PROCESS_HIS
(
  CDR_LOG_PROCESS_ID    NUMBER(10)              NOT NULL,
  SOURCE_FILE_URL       VARCHAR2(255 BYTE),
  OUTPUT_FILE_URL       VARCHAR2(255 BYTE),
  START_TIME            DATE,
  END_TIME              DATE,
  STATUS                VARCHAR2(10 BYTE),
  METHOD                CHAR(1 BYTE),
  SOURCE_FILE_BEHAVIOR  CHAR(1 BYTE),
  BACKUP_FILE_URL       VARCHAR2(255 BYTE),
  IS_HANDLED            VARCHAR2(20 BYTE),
  TOTAL_CDR             NUMBER(10),
  TOTAL_CDR_PROCESSED   NUMBER,
  INSTANCE              NUMBER(2)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON VNP_DATA.CDR_LOG_PROCESS_HIS TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.CDR_LOG_PROCESS_HIS TO VNP_VIEW;
