DROP TABLE VNP_DATA.CDR_RECORD_HEADER_TEST CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.CDR_RECORD_HEADER_TEST
(
  CDR_RECORD_HEADER_ID       NUMBER(10),
  RECORD_ID                  VARCHAR2(7 BYTE),
  XOR_CHECKSUM               NUMBER(3),
  HOST_NAME                  VARCHAR2(33 BYTE),
  START_RCD_SEQ              VARCHAR2(11 BYTE),
  END_RCD_SEQ                VARCHAR2(11 BYTE),
  FILE_CREATION_TIMESTAMP    VARCHAR2(32 BYTE),
  FILE_LASTUPDATE_TIMESTAMP  VARCHAR2(32 BYTE),
  NUMBER_OF_RECORD           NUMBER(11),
  CHECKSUM_VALID             NUMBER(3),
  CDR_FILENAME               VARCHAR2(60 BYTE),
  CONVERT_TIME               DATE               DEFAULT SYSDATE
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON VNP_DATA.CDR_RECORD_HEADER_TEST TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.CDR_RECORD_HEADER_TEST TO VNP_VIEW;
