DROP TABLE VNP_DATA.CDR_LOG_PROCESS CASCADE CONSTRAINTS;

CREATE TABLESPACE vnp_data_CDR_LOG_PROC
  DATAFILE '+DATA/orcl/datafile/vnp_data/CDR_LOG_PROC01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10 M MAXSIZE UNLIMITED;

CREATE TABLE VNP_DATA.CDR_LOG_PROCESS
(
  CDR_LOG_PROCESS_ID    NUMBER(10)              NOT NULL,
  SOURCE_FILE_URL       VARCHAR2(255 BYTE),
  OUTPUT_FILE_URL       VARCHAR2(255 BYTE),
  START_TIME            DATE,
  END_TIME              DATE,
  STATUS                VARCHAR2(10 BYTE),
  METHOD                CHAR(1 BYTE),
  SOURCE_FILE_BEHAVIOR  CHAR(1 BYTE),
  BACKUP_FILE_URL       VARCHAR2(255 BYTE),
  IS_HANDLED            VARCHAR2(20 BYTE),
  TOTAL_CDR             NUMBER(10),
  TOTAL_CDR_PROCESSED   NUMBER,
  INSTANCE              NUMBER(2)
)
TABLESPACE vnp_data_CDR_LOG_PROC;


CREATE INDEX VNP_DATA.CDR_LOG_PROCESS_IDX_01 ON VNP_DATA.CDR_LOG_PROCESS
(CDR_LOG_PROCESS_ID)
TABLESPACE vnp_data_CDR_LOG_PROC;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.CDR_LOG_PROCESS TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.CDR_LOG_PROCESS TO VNP_VIEW;
