DROP TABLE VNP_DATA.ERROR_CODE CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.ERROR_CODE
(
  ERROR_CODE   VARCHAR2(6 BYTE)                 NOT NULL,
  DESCRIPTION  VARCHAR2(500 BYTE)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VNP_DATA.ERROR_CODE.ERROR_CODE IS 'CDR Error code';

COMMENT ON COLUMN VNP_DATA.ERROR_CODE.DESCRIPTION IS 'Error Description';


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.ERROR_CODE TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.ERROR_CODE TO VNP_VIEW;
