DROP TABLE VNP_DATA.HOT_RC_C1RT_LOG_PROCESS CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.HOT_RC_C1RT_LOG_PROCESS
(
  GZIP_FILE          VARCHAR2(100 BYTE)         NOT NULL,
  DATA_FILE          VARCHAR2(100 BYTE),
  LOG_FILE           VARCHAR2(100 BYTE),
  BAD_FILE           VARCHAR2(100 BYTE),
  TOTAL_RECORDS      NUMBER,
  SUCCESS_RECORDS    NUMBER,
  INVALID_RECORDS    NUMBER,
  GZIP_SIZE          NUMBER,
  DATA_SIZE          NUMBER,
  GZIP_PROCESS       NUMBER                     DEFAULT 0,
  INSERT_DB_PROCESS  NUMBER                     DEFAULT 0,
  MODIFIED_TIME      DATE                       DEFAULT CURRENT_DATE,
  CREATED_TIME       DATE,
  ENRICH_PROCESS     NUMBER                     DEFAULT 0
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
