DROP TABLE VNP_DATA.RATED_RC CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.RATED_RC
(
  STATUS_ID       NUMBER(3),
  SUBSCRIBER_NO   VARCHAR2(31 BYTE),
  CURRENCY_CODE   NUMBER(6),
  RC              NUMBER(16,4),
  VAT             NUMBER(16,4),
  OFFER_ID        NUMBER(10),
  BILL_MONTH      DATE,
  SUBSCRIBER_ID   NUMBER(15),
  RATE_TIME       DATE                          DEFAULT sysdate               NOT NULL,
  FULL_CYCLE      CHAR(1 BYTE)                  DEFAULT '0'                   NOT NULL,
  NUMBER_OF_DAYS  NUMBER(2)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE 4 INSTANCES 1 )
MONITORING;


CREATE INDEX VNP_DATA.RATED_RC_GROUP ON VNP_DATA.RATED_RC
(SUBSCRIBER_ID, SUBSCRIBER_NO, CURRENCY_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.RATED_RC TO PCAT_FILTER;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.RATED_RC TO VNP_COMMON;
