DROP TABLE VNP_DATA.RATING_RC CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE VNP_DATA.RATING_RC
(
  SUBSCRIBER_ID  NUMBER(15),
  SUBSCRIBER_NO  VARCHAR2(31 BYTE),
  OFFER_ID       NUMBER(10),
  STATUS_ID      NUMBER(3),
  DURATION       NUMBER,
  RC             NUMBER(15,3),
  VAT_RATE       NUMBER(15,3),
  CURRENCY_CODE  NUMBER(6)
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.RATING_RC TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.RATING_RC TO VNP_VIEW;
