DROP TABLE VNP_DATA.RC_LOG CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.RC_LOG
(
  RATE_TIME    DATE                             NOT NULL,
  INSERT_TYPE  CHAR(1 BYTE)                     DEFAULT '0'                   NOT NULL
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.RC_LOG TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.RC_LOG TO VNP_VIEW;
