DROP TABLE VNP_DATA.SUBS_RERATE_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.SUBS_RERATE_HISTORY
(
  RATE_HIS_ID       NUMBER,
  SUBSCRIBER_NO     VARCHAR2(31 BYTE),
  STATUS            VARCHAR2(5 BYTE),
  LAST_RATE_DATE    DATE,
  LAST_CHANGE_DATE  DATE
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX VNP_DATA.SUBS_RERATE_HISTORY_IDX ON VNP_DATA.SUBS_RERATE_HISTORY
(SUBSCRIBER_NO)
NOLOGGING
TABLESPACE VNP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.SUBS_RERATE_HISTORY TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.SUBS_RERATE_HISTORY TO VNP_VIEW;
