DROP TABLE VNP_DATA.SUBS_RERATE_CTL CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.SUBS_RERATE_CTL
(
  MONTH             VARCHAR2(100 BYTE),
  MSISDN            VARCHAR2(30 BYTE),
  AGENT_CODE        VARCHAR2(10 BYTE),
  PRIMARY_OFFER_ID  NUMBER(10),
  N1                NUMBER(10),
  C2                VARCHAR2(30 BYTE),
  TIME_START        DATE,
  TIME_END          DATE,
  IS_ROLLBACK       NUMBER,
  IS_GETBACK        NUMBER,
  LOG_DATE          DATE,
  RERATED_DAY       NUMBER(2)                   DEFAULT 0,
  STATUS            NUMBER(2)                   DEFAULT 0
)
TABLESPACE VNP_DATA;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.SUBS_RERATE_CTL TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.SUBS_RERATE_CTL TO VNP_VIEW;
