DROP TABLE VNP_DATA.TEMP_RC_RATING CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.TEMP_RC_RATING
(
  SUBSCRIBER_ID  NUMBER(15)                     NOT NULL,
  SUBSCRIBER_NO  VARCHAR2(31 BYTE)              NOT NULL,
  OFFER_ID       NUMBER(10)                     NOT NULL,
  STATUS_ID      NUMBER(3)                      NOT NULL,
  DURATION       NUMBER,
  RC             NUMBER(15,3),
  VAT_RATE       NUMBER(15,3),
  CURRENCY_CODE  NUMBER(6)                      NOT NULL
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.TEMP_RC_RATING TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.TEMP_RC_RATING TO VNP_VIEW;
