DROP TABLE VNP_DATA.TEMP_RATED_CDR_1 CASCADE CONSTRAINTS;

CREATE TABLESPACE vnp_DATA_TRC_1
  DATAFILE '+DATA/orcl/datafile/vnp_data/temp_rated_cdr_101.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10 M MAXSIZE UNLIMITED;

CREATE TABLE VNP_DATA.TEMP_RATED_CDR_1
(
  A_NUMBER              VARCHAR2(15 BYTE),
  CDR_TYPE              NUMBER(2),
  CREATED_TIME          DATE                    DEFAULT SYSDATE,
  CDR_START_TIME        DATE,
  DURATION              NUMBER(11),
  TOTAL_USAGE           NUMBER(11),
  B_NUMBER              VARCHAR2(31 BYTE),
  B_ZONE                VARCHAR2(127 BYTE),
  NW_GROUP              VARCHAR2(15 BYTE),
  SERVICE_FEE           NUMBER(15,3),
  SERVICE_FEE_ID        NUMBER(3),
  CHARGE_FEE            NUMBER(31,3),
  CHARGE_FEE_ID         NUMBER(5),
  LAC                   VARCHAR2(23 BYTE),
  CELL_ID               VARCHAR2(23 BYTE),
  SUBSCRIBER_UNBILL     CHAR(2 BYTE),
  BU_ID                 VARCHAR2(3 BYTE),
  OLD_BU_ID             VARCHAR2(3 BYTE),
  OFFER_COST            NUMBER(15,3),
  OFFER_FREE_BLOCK      NUMBER(21),
  INTERNAL_COST         NUMBER(15,3),
  INTERNAL_FREE_BLOCK   NUMBER(11),
  DIAL_DIGIT            VARCHAR2(31 BYTE),
  CDR_RECORD_HEADER_ID  NUMBER(11),
  CDR_SEQUENCE_NUMBER   NUMBER(11),
  LOCATION_NO           VARCHAR2(31 BYTE),
  MSC_ID                VARCHAR2(31 BYTE),
  UNIT_TYPE_ID          NUMBER(2)               NOT NULL,
  PRIMARY_OFFER_ID      NUMBER(10),
  DISCOUNT_ITEM_ID      NUMBER(6),
  BALANCE_CHANGE        VARCHAR2(500 BYTE),
  RERATE_FLAG           NUMBER(1),
  AUT_FINAL_ID          NUMBER(6),
  TARIFF_PLAN_ID        NUMBER(6),
  ERROR_CODE            VARCHAR2(6 BYTE)        DEFAULT 0,
  PAYMENT_ID            NUMBER(6),
  SUBSCRIBER_NO         NUMBER(31)              DEFAULT 0,
  SUBSCRIBER_NO_RESETS  NUMBER(7)               DEFAULT 0,
  ACCOUNT_NO            NUMBER(31)              DEFAULT 0,
  PARENT_ACCOUNT_NO     NUMBER(31)              DEFAULT 0,
  INTL_VND              NUMBER(31,3)            DEFAULT 0,
  INTL_ID               NUMBER(7)               DEFAULT 0,
  CDR_CALL_TYPE         VARCHAR2(7 BYTE),
  QOS                   VARCHAR2(7 BYTE)
)
TABLESPACE vnp_DATA_TRC_1;


GRANT DELETE, INSERT, SELECT, UPDATE ON  VNP_DATA.TEMP_RATED_CDR_1 TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.TEMP_RATED_CDR_1 TO VNP_VIEW;
