DROP TABLE VNP_DATA.THIRD_TEMP_RATED_CDR CASCADE CONSTRAINTS;

CREATE TABLE VNP_DATA.THIRD_TEMP_RATED_CDR
(
  A_NUMBER              VARCHAR2(31 BYTE),
  CDR_TYPE              NUMBER(2),
  CREATED_TIME          DATE,
  CDR_START_TIME        DATE,
  DURATION              NUMBER(11),
  TOTAL_USAGE           NUMBER(11),
  B_NUMBER              VARCHAR2(31 BYTE),
  B_ZONE                VARCHAR2(127 BYTE),
  NW_GROUP              VARCHAR2(7 BYTE),
  SERVICE_FEE           NUMBER(15,3),
  SERVICE_FEE_ID        NUMBER(1),
  CHARGE_FEE            NUMBER(15,3),
  CHARGE_FEE_ID         NUMBER(1),
  LAC                   VARCHAR2(23 BYTE),
  CELL_ID               VARCHAR2(23 BYTE),
  SUBSCRIBER_UNBILL     CHAR(1 BYTE),
  BU_ID                 NUMBER(3),
  OLD_BU_ID             NUMBER(3),
  OFFER_COST            NUMBER(15,3),
  OFFER_FREE_BLOCK      NUMBER(11),
  INTERNAL_COST         NUMBER(15,3),
  INTERNAL_FREE_BLOCK   NUMBER(11),
  DIAL_DIGIT            VARCHAR2(31 BYTE),
  CDR_RECORD_HEADER_ID  NUMBER(11),
  CDR_SEQUENCE_NUMBER   NUMBER(11),
  LOCATION_NO           VARCHAR2(31 BYTE),
  RERATE_FLAG           NUMBER(1),
  CALL_TYPE_ID          NUMBER(1),
  PAYMENT_ITEM_ID       NUMBER(3),
  MSC_ID                VARCHAR2(31 BYTE),
  ERROR_MESSAGE         VARCHAR2(512 BYTE)
)
TABLESPACE VNP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON VNP_DATA.THIRD_TEMP_RATED_CDR TO VNP_COMMON;

GRANT SELECT ON VNP_DATA.THIRD_TEMP_RATED_CDR TO VNP_VIEW;
