DROP TABLESPACE VNP_COMMON_ACCOUNT INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_ACCOUNT DATAFILE 
  '+DATA/eonerate/datafile/vnp_common/account01.dbf' SIZE 2048M AUTOEXTEND ON NEXT 500M MAXSIZE 30720M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
