DROP TABLESPACE VNP_DATA_2 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_DATA_2 DATAFILE 
  '+DATA/eonerate/datafile/vnp_data_201.dbf' SIZE 2048M AUTOEXTEND ON NEXT 500M MAXSIZE 10240M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
