DROP TABLESPACE VNP_COMMON_2 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_2 DATAFILE 
  '+DATA/eonerate/datafile/vnp_common_201.dbf' SIZE 450M AUTOEXTEND ON NEXT 50M MAXSIZE 2048M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
