DROP TABLESPACE VNP_DATA_BALANCE_COUNTER INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_DATA_BALANCE_COUNTER DATAFILE 
  '+DATA/eonerate/datafile/vnp_data/balance_counter01.dbf' SIZE 2048M AUTOEXTEND ON NEXT 500M MAXSIZE 30720M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
