DROP TABLESPACE VNP_COMMON_SOM INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_SOM DATAFILE 
  '+DATA/eonerate/datafile/vnp_common/subs_offer_map01.dbf' SIZE 2048M AUTOEXTEND ON NEXT 500M MAXSIZE 30720M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
