DROP TABLESPACE VNP_COMMON_PROP INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_PROP DATAFILE 
  '+DATA/eonerate/datafile/vnp_common_prop01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 1024M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
