/* Formatted on 13/1/2015 12:09:17 (QP5 v5.215.12089.38647) */
DROP TABLE SYNC_FLAG CASCADE CONSTRAINTS;

CREATE TABLE SYNC_FLAG
(
   RESELLER_VERSION_ID   NUMBER (18),
   STATUS                NUMBER (1),
   CREATED_TIME          DATE DEFAULT SYSDATE,
   NOTE                  VARCHAR2 (255 BYTE)
)
TABLESPACE CBS_OWNER
RESULT_CACHE (MODE DEFAULT)
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER SYNC_FLAG_ARI
   AFTER INSERT
   ON SYNC_FLAG
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
   WHEN (NEW.STATUS = 1)
DECLARE
   jno   BINARY_INTEGER;
BEGIN
   DBMS_JOB.submit (
      JOB         => jno,
      WHAT        =>    'BEGIN VNP_COMMON.ELC_USER_FILTER_2.START_JOB_FILTER_NEW_PCAT_DATA ('
                     || :NEW.RESELLER_VERSION_ID
                     || '); END;',
      NEXT_DATE   => SYSDATE);
END SYNC_FLAG_ARI;
/


GRANT DELETE,
      INSERT,
      SELECT,
      UPDATE
   ON SYNC_FLAG
   TO VNP_COMMON;