/* Formatted on 14/4/2014 00:47:56 (QP5 v5.227.12220.39754) */
SELECT t4.UPSELL_TEMPLATE_ID AS upsellTemplateId,
       t2.RESELLER_VERSION_ID AS resellerVersionId,
       t3.LANGUAGE_CODE AS languageCode,
       t3.DISPLAY_VALUE AS name,
       t3.DESCRIPTION AS description
  FROM cbs_owner.UPSELL_TEMPLATE_KEY t4
       INNER JOIN cbs_owner.UPSELL_TEMPLATE_REF t2
          ON t4.UPSELL_TEMPLATE_ID = t2.UPSELL_TEMPLATE_ID
       INNER JOIN
       cbs_owner.UPSELL_TEMPLATE_VALUES t3
          ON     t2.UPSELL_TEMPLATE_ID = t3.UPSELL_TEMPLATE_ID
             AND t2.RESELLER_VERSION_ID = t3.RESELLER_VERSION_ID
       INNER JOIN
       cbs_owner.OFFER_REF t1
          ON     t4.UPSELL_TEMPLATE_ID = t1.UPSELL_TEMPLATE_ID
             AND t1.RESELLER_VERSION_ID = t3.RESELLER_VERSION_ID
 WHERE t2.RESELLER_VERSION_ID = 2 AND t3.LANGUAGE_CODE = 1