#!/usr/bin/expect -f

set orfile [lindex $argv 0]
set namelist {}

set fd [open orp.map r]
while { [gets $fd line] >= 0 } {
  lappend namelist $line
}
close $fd

set fd [open "$orfile" r]
while { [gets $fd line] >= 0 } {
  if { [string compare -length 3 "$line" "ORH"] == 0 } { continue }
  set vlist [split "$line" "|"]
  set idx 0
  while { $idx < [llength $vlist] } {
    set name [lindex $namelist $idx]
    set val [lindex $vlist $idx]
    if { [string length "$val"] > 0 } {
      send_user "$name=$val\n"
    }
    incr idx
  }
}
close $fd
exit 0
