#!/bin/bash

if [ ! -f cdr.dat ]; then
  echo "No record found"
  exit 1
fi

HOST=`head -1 cdr.dat | cut -f8 -d'|'`
RCNT=`wc -l cdr.dat | cut -f1 -d' '`
SEQ=`head -1 cdr.dat | cut -f2 -d'|'`
FROM=$SEQ
SEQ=`tail -1 cdr.dat | cut -f2 -d'|'`

echo $HOST $RCNT $FROM $SEQ

TT=`date +%s`
orfile="IPor.$TT.$HOST.$FROM.bill"
echo $orfile

printf "ORH:%-33s0%s0%s%011d%011d%011d\n" $HOST $FROM $SEQ $(($TT - 10)) $TT $RCNT > $orfile
cat cdr.dat >> $orfile
rm -f cdr.dat

cp $orfile /staging/billing/data/usage/remote/ready/
su - cbsuser -c "/home/cbsuser/orptest.sh $orfile"

