DROP TABLESPACE HOT_AGGREGATED_CDR_IDX INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_AGGREGATED_CDR_IDX DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_aggregated_cdr_idx01.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_AGGREGATED_CDR_TBL INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_AGGREGATED_CDR_TBL DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_aggregated_cdr_tbl01.dbf' SIZE 1G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P0 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P0 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p0.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P1 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p1.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P2 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P2 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p2.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P3 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P3 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p3.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P4 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P4 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p4.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P5 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P5 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p5.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P6 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P6 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p6.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P7 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P7 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p7.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P8 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P8 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p8.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE HOT_RATED_P9 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE HOT_RATED_P9 DATAFILE 
  '/u01/app/oracle/oradata/orcl/hot_rated_p9.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P0 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P0 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p0.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P1 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p1.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P2 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P2 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p2.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P3 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P3 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p3.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P4 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P4 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p4.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P5 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P5 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p5.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P6 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P6 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p6.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P7 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P7 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p7.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P8 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P8 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p8.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE RATED_P9 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE RATED_P9 DATAFILE 
  '/u01/app/oracle/oradata/orcl/rated_p9.dbf' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P0 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P0 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p0.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P1 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p1.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P2 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P2 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p2.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P3 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P3 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p3.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P4 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P4 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p4.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P5 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P5 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p5.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P6 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P6 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p6.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P7 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P7 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p7.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P8 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P8 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p8.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE SUBS_P9 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE SUBS_P9 DATAFILE 
  '/u01/app/oracle/oradata/orcl/subs_p9.dbf' SIZE 200M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TBS_CDR_LOG_PROCESS INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBS_CDR_LOG_PROCESS DATAFILE 
  '/u01/app/oracle/oradata/orcl/cdr_log_process_01.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TBS_TEMP_RATED_CDR INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBS_TEMP_RATED_CDR DATAFILE 
  '/u01/app/oracle/oradata/orcl/temp_rated_cdr_01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TBS_TEMP_RATED_CDR_1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBS_TEMP_RATED_CDR_1 DATAFILE 
  '/u01/app/oracle/oradata/orcl/temp_rated_cdr_1_01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TBS_TEMP_RATED_CDR_IDX INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBS_TEMP_RATED_CDR_IDX DATAFILE 
  '/u01/app/oracle/oradata/orcl/temp_rated_cdr_idx_01.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE TBS_TEMP_RATED_CDR_IDX_1 INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TBS_TEMP_RATED_CDR_IDX_1 DATAFILE 
  '/u01/app/oracle/oradata/orcl/temp_rated_cdr_idx_1_01.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_COMMON INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_common01.dbf' SIZE 1G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED,
  '/u01/app/oracle/oradata/orcl/vnp_common02.dbf' SIZE 1G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_COMMON_ACCOUNT INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_ACCOUNT DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_common/account01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_COMMON_ACC_VER INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_ACC_VER DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_common/account_version01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_COMMON_PROP INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_PROP DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_common_prop01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_COMMON_SOM INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_COMMON_SOM DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_common/subs_offer_map01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


DROP TABLESPACE VNP_DATA INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_DATA DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_data01.dbf' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;



DROP TABLESPACE VNP_DATA_BALANCE_COUNTER INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE VNP_DATA_BALANCE_COUNTER DATAFILE 
  '/u01/app/oracle/oradata/orcl/vnp_data/balance_counter01.dbf' SIZE 1G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
